const assert = require('assert')
const fs = require('fs')
const path = require('path')

const productsRoute = fs.readFileSync(path.join(__dirname, '..', 'src', 'routes', 'products.ts'), 'utf8')

assert(productsRoute.includes('query.ids || query.productIds || query.product_ids'), 'product search should accept ids/productIds query filters')
assert(productsRoute.includes('p.id IN'), 'product search should constrain id lookups in SQL')
assert(productsRoute.includes('collectBoundedValues(values, 100)'), 'product search id lookup should stay bounded to the maximum page size')
assert(productsRoute.includes("include.has('family')"), 'product search should support POS family expansion')
assert(productsRoute.includes('expandProductFamilyRows'), 'product family expansion should load parents, variants, and same-name options')
assert(productsRoute.includes('p.parent_id IN'), 'product family expansion should fetch sibling variants for selected parents')
assert(productsRoute.includes("const { getOrSetJson } = require('../runtimeCache.ts')"), 'product read routes should use the shared runtime cache')
assert(productsRoute.includes("buildProductReadCacheKey('search', query)"), 'product search cache should key payloads by query and catalog snapshot')
assert(productsRoute.includes('function getCachedProductBootstrapPayload'), 'product bootstrap should cache its combined branch and product payload')
assert(productsRoute.includes("buildProductReadCacheKey('bootstrap', query)"), 'product bootstrap cache should key payloads by query and catalog snapshot')
assert(productsRoute.includes('PRODUCT_BRANCH_LIST_MEMO_MS'), 'product bootstrap should memoize branch list reads during startup bursts')
assert(productsRoute.includes('PRODUCT_CATALOG_SNAPSHOT_VERSION_MEMO_MS'), 'product snapshot version reads should use a short in-process memo for startup bursts')
assert(productsRoute.includes("snapshot_version || '').trim() || 'empty'"), 'product snapshot fallback should be stable for legacy rows with null timestamps')
assert(productsRoute.includes('function broadcastProductsUpdate'), 'product writes should invalidate the in-process snapshot memo before broadcasting')
assert(!productsRoute.includes("broadcast('products')"), 'product route writes should use broadcastProductsUpdate instead of raw product broadcasts')
assert(!productsRoute.includes("include.has('batches') || include.has('family')"), 'POS family expansion should not imply batch hydration unless batches are requested')
assert(productsRoute.includes("metadata ?? query.includeMetadata ?? query.include_metadata"), 'product first-window reads should be able to skip full filter metadata')
assert(!/ORDER BY p\.\$\{field\} COLLATE NOCASE ASC\s+LIMIT/.test(productsRoute), 'product filter metadata should not truncate brand/category/supplier options')
assert(productsRoute.includes('const productsByImageBaseName = new Map()'), 'image-only bulk import should build a product lookup map')
assert(productsRoute.includes('productsByImageBaseName.get(baseName)'), 'image-only bulk import should match each filename with one map lookup')
assert(!/allProducts\.find\(\(p\) => String\(p\?\.name \|\| ''\)\.trim\(\)\.toLowerCase\(\) === baseName\)/.test(productsRoute), 'image-only bulk import should not scan all products for every image')

console.log('productSearchPagination tests passed')
