'use strict'

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')
const http = require('http')
const https = require('https')
const Database = require('better-sqlite3')
const { Pool } = require('pg')

const SQLITE_INTERNAL_TABLES = new Set(['sqlite_sequence'])
const DEFAULT_BATCH_SIZE = 500

function trim(value) {
  return String(value || '').trim()
}

function quoteIdent(value) {
  return `"${String(value || '').replace(/"/g, '""')}"`
}

function normalizeSqliteType(type) {
  const raw = String(type || '').toUpperCase()
  if (raw.includes('INT')) return 'BIGINT'
  if (raw.includes('REAL') || raw.includes('FLOA') || raw.includes('DOUB')) return 'DOUBLE PRECISION'
  if (raw.includes('BLOB')) return 'BYTEA'
  if (raw.includes('NUM')) return 'NUMERIC'
  return 'TEXT'
}

function resolvePostgresColumnType(sqlite, table, column) {
  const baseType = normalizeSqliteType(column.type)
  const isIntegerPrimaryKey = Number(column.pk) === 1 && /INT/i.test(String(column.type || ''))
  if (isIntegerPrimaryKey) return 'BIGINT'
  if (baseType !== 'BIGINT' && baseType !== 'DOUBLE PRECISION' && baseType !== 'NUMERIC') return baseType
  try {
    const bad = sqlite.prepare(`
      SELECT 1 AS bad
      FROM ${quoteIdent(table)}
      WHERE ${quoteIdent(column.name)} IS NOT NULL
        AND typeof(${quoteIdent(column.name)}) NOT IN ('integer', 'real')
      LIMIT 1
    `).get()
    if (bad) return 'TEXT'
  } catch (_) {
    return 'TEXT'
  }
  return baseType
}

function defaultExpression(column) {
  const value = String(column.dflt_value || '').trim()
  if (!value) return ''
  if (/datetime\s*\(\s*'now'\s*\)/i.test(value)) return ' DEFAULT CURRENT_TIMESTAMP'
  if (/^CURRENT_TIMESTAMP$/i.test(value)) return ' DEFAULT CURRENT_TIMESTAMP'
  if (/^-?\d+(\.\d+)?$/.test(value)) return ` DEFAULT ${value}`
  if (/^'.*'$/.test(value)) return ` DEFAULT ${value}`
  return ''
}

function mapColumnDefinition(sqlite, table, column) {
  const name = quoteIdent(column.name)
  const isIntegerPrimaryKey = Number(column.pk) === 1 && /INT/i.test(String(column.type || ''))
  if (isIntegerPrimaryKey) return `${name} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
  const parts = [name, resolvePostgresColumnType(sqlite, table, column)]
  if (Number(column.notnull) === 1) parts.push('NOT NULL')
  parts.push(defaultExpression(column))
  return parts.join(' ').replace(/\s+/g, ' ').trim()
}

function readSqliteTables(sqlite) {
  return sqlite.prepare(`
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
      AND name NOT LIKE 'sqlite_%'
    ORDER BY name
  `).all().map((row) => row.name).filter((name) => !SQLITE_INTERNAL_TABLES.has(name))
}

async function ensureSchema(pool, sqlite, tables) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS business_os_migration_status (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_hash TEXT,
      status TEXT NOT NULL,
      summary_json JSONB DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `)

  for (const table of tables) {
    const columns = sqlite.prepare(`PRAGMA table_info(${quoteIdent(table)})`).all()
    if (!columns.length) continue
    const hasPrimary = columns.some((column) => Number(column.pk) === 1)
    const definitions = columns.map((column) => mapColumnDefinition(sqlite, table, column))
    if (!hasPrimary) definitions.unshift('id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    await pool.query(`CREATE TABLE IF NOT EXISTS ${quoteIdent(table)} (${definitions.join(', ')})`)
  }
}

function hashFile(filePath) {
  const hash = crypto.createHash('sha256')
  const fd = fs.openSync(filePath, 'r')
  const buffer = Buffer.allocUnsafe(1024 * 1024)
  try {
    while (true) {
      const bytes = fs.readSync(fd, buffer, 0, buffer.length, null)
      if (!bytes) break
      hash.update(buffer.subarray(0, bytes))
    }
  } finally {
    fs.closeSync(fd)
  }
  return hash.digest('hex')
}

async function tableHasRows(pool, table) {
  const result = await pool.query(`SELECT COUNT(*)::bigint AS count FROM ${quoteIdent(table)}`)
  return Number(result.rows?.[0]?.count || 0) > 0
}

async function insertRows(pool, table, rows) {
  if (!rows.length) return 0
  const columns = Object.keys(rows[0])
  if (!columns.length) return 0
  const values = []
  const placeholders = rows.map((row, rowIndex) => {
    const rowPlaceholders = columns.map((column, columnIndex) => {
      values.push(row[column])
      return `$${rowIndex * columns.length + columnIndex + 1}`
    })
    return `(${rowPlaceholders.join(', ')})`
  })
  await pool.query(
    `INSERT INTO ${quoteIdent(table)} (${columns.map(quoteIdent).join(', ')}) VALUES ${placeholders.join(', ')}`,
    values
  )
  return rows.length
}

async function migrateTable(pool, sqlite, table, batchSize) {
  const count = sqlite.prepare(`SELECT COUNT(*) AS count FROM ${quoteIdent(table)}`).get().count || 0
  if (count === 0) return { table, source: 0, inserted: 0, skipped: false }
  if (await tableHasRows(pool, table)) return { table, source: count, inserted: 0, skipped: true }

  let inserted = 0
  for (let offset = 0; offset < count; offset += batchSize) {
    const rows = sqlite.prepare(`SELECT * FROM ${quoteIdent(table)} LIMIT ? OFFSET ?`).all(batchSize, offset)
    inserted += await insertRows(pool, table, rows)
  }
  await resetIdentity(pool, table).catch(() => {})
  return { table, source: count, inserted, skipped: false }
}

async function resetIdentity(pool, table) {
  const sequenceResult = await pool.query(`
    SELECT pg_get_serial_sequence($1, 'id') AS sequence_name
  `, [table])
  const sequence = sequenceResult.rows?.[0]?.sequence_name
  if (!sequence) return
  await pool.query(`SELECT setval($1, COALESCE((SELECT MAX(id) FROM ${quoteIdent(table)}), 1), true)`, [sequence])
}

function hmac(key, value, encoding) {
  return crypto.createHmac('sha256', key).update(value).digest(encoding)
}

function sha256Hex(value) {
  return crypto.createHash('sha256').update(value).digest('hex')
}

function deriveSigningKey(secret, date, region) {
  const kDate = hmac(`AWS4${secret}`, date)
  const kRegion = hmac(kDate, region)
  const kService = hmac(kRegion, 's3')
  return hmac(kService, 'aws4_request')
}

function encodeS3Path(value) {
  return String(value || '').split('/').map((part) => encodeURIComponent(part)).join('/')
}

async function s3Request({ method, bucket, key = '', body = Buffer.alloc(0), contentType = 'application/octet-stream' }) {
  const endpoint = new URL(trim(process.env.S3_ENDPOINT) || 'http://minio:9000')
  const accessKey = trim(process.env.S3_ACCESS_KEY_ID || process.env.MINIO_ROOT_USER)
  const secretKey = trim(process.env.S3_SECRET_ACCESS_KEY || process.env.MINIO_ROOT_PASSWORD)
  const region = trim(process.env.S3_REGION) || 'us-east-1'
  if (!accessKey || !secretKey) throw new Error('S3 credentials are required for MinIO asset migration.')

  const now = new Date()
  const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, '')
  const shortDate = amzDate.slice(0, 8)
  const payloadHash = sha256Hex(body)
  const canonicalUri = `/${encodeURIComponent(bucket)}${key ? `/${encodeS3Path(key)}` : ''}`
  const host = endpoint.host
  const headers = {
    host,
    'x-amz-content-sha256': payloadHash,
    'x-amz-date': amzDate,
  }
  if (body.length) headers['content-type'] = contentType
  const signedHeaders = Object.keys(headers).sort().join(';')
  const canonicalHeaders = Object.keys(headers).sort().map((name) => `${name}:${headers[name]}\n`).join('')
  const canonicalRequest = [
    method,
    canonicalUri,
    '',
    canonicalHeaders,
    signedHeaders,
    payloadHash,
  ].join('\n')
  const credentialScope = `${shortDate}/${region}/s3/aws4_request`
  const stringToSign = [
    'AWS4-HMAC-SHA256',
    amzDate,
    credentialScope,
    sha256Hex(canonicalRequest),
  ].join('\n')
  const signature = hmac(deriveSigningKey(secretKey, shortDate, region), stringToSign, 'hex')
  const protocol = endpoint.protocol === 'https:' ? https : http
  const requestHeaders = {
    ...headers,
    authorization: `AWS4-HMAC-SHA256 Credential=${accessKey}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`,
    'content-length': String(body.length),
  }

  return new Promise((resolve, reject) => {
    const req = protocol.request({
      method,
      hostname: endpoint.hostname,
      port: endpoint.port || (endpoint.protocol === 'https:' ? 443 : 80),
      path: canonicalUri,
      headers: requestHeaders,
    }, (res) => {
      const chunks = []
      res.on('data', (chunk) => chunks.push(chunk))
      res.on('end', () => {
        const responseBody = Buffer.concat(chunks).toString('utf8')
        if (res.statusCode >= 200 && res.statusCode < 300) return resolve({ statusCode: res.statusCode, body: responseBody })
        if (res.statusCode === 409 && method === 'PUT' && !key) return resolve({ statusCode: res.statusCode, body: responseBody })
        reject(new Error(`S3 ${method} ${canonicalUri} failed with ${res.statusCode}: ${responseBody.slice(0, 300)}`))
      })
    })
    req.on('error', reject)
    if (body.length) req.write(body)
    req.end()
  })
}

async function ensureBucket(bucket) {
  await s3Request({ method: 'PUT', bucket })
}

async function migrateUploadsToMinio({ uploadsRoot, summary }) {
  if (trim(process.env.OBJECT_STORAGE_DRIVER).toLowerCase() !== 'minio') return
  if (!uploadsRoot || !fs.existsSync(uploadsRoot)) return
  const bucket = trim(process.env.S3_BUCKET) || 'business-os-assets'
  await ensureBucket(bucket)
  const files = collectFiles(uploadsRoot)
  for (const filePath of files) {
    const relative = path.relative(uploadsRoot, filePath).split(path.sep).join('/')
    const body = fs.readFileSync(filePath)
    await s3Request({
      method: 'PUT',
      bucket,
      key: `uploads/${relative}`,
      body,
      contentType: 'application/octet-stream',
    })
    summary.assetsUploaded += 1
  }
}

function collectFiles(root) {
  const out = []
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const fullPath = path.join(root, entry.name)
    if (entry.isDirectory()) out.push(...collectFiles(fullPath))
    else if (entry.isFile()) out.push(fullPath)
  }
  return out
}

function resolveLegacyPaths() {
  const explicitDb = trim(process.env.LEGACY_SQLITE_DB_PATH)
  const explicitUploads = trim(process.env.LEGACY_UPLOADS_PATH)
  if (explicitDb) {
    return {
      dbPath: explicitDb,
      uploadsRoot: explicitUploads || path.join(path.dirname(path.dirname(explicitDb)), 'uploads'),
    }
  }

  const legacyRoot = trim(process.env.BUSINESS_OS_LEGACY_ROOT_IN_CONTAINER) || '/legacy'
  const organizationsRoot = path.join(legacyRoot, 'business-os-data', 'organizations')
  if (fs.existsSync(organizationsRoot)) {
    const candidates = fs.readdirSync(organizationsRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => path.join(organizationsRoot, entry.name))
      .map((root) => ({ dbPath: path.join(root, 'db', 'business.db'), uploadsRoot: path.join(root, 'uploads') }))
      .filter((candidate) => fs.existsSync(candidate.dbPath))
      .sort((a, b) => fs.statSync(b.dbPath).mtimeMs - fs.statSync(a.dbPath).mtimeMs)
    if (candidates.length) return candidates[0]
  }

  const dbPath = trim(process.env.LEGACY_SQLITE_DB_PATH)
    || trim(process.env.DB_PATH)
    || '/legacy/business-os-data/organizations/org_leangcosmetics (Leang Cosmetics)/db/business.db'
  const uploadsRoot = trim(process.env.LEGACY_UPLOADS_PATH)
    || '/legacy/business-os-data/organizations/org_leangcosmetics (Leang Cosmetics)/uploads'
  return { dbPath, uploadsRoot }
}

function snapshotSqliteDatabase(dbPath) {
  const tempDir = fs.mkdtempSync(path.join('/tmp', 'business-os-sqlite-'))
  const target = path.join(tempDir, 'business.db')
  fs.copyFileSync(dbPath, target)
  for (const suffix of ['-wal', '-shm']) {
    const sidecar = `${dbPath}${suffix}`
    if (fs.existsSync(sidecar)) {
      try { fs.copyFileSync(sidecar, `${target}${suffix}`) } catch (_) {}
    }
  }
  return target
}

async function start() {
  const databaseUrl = trim(process.env.DATABASE_URL)
  if (!databaseUrl) throw new Error('DATABASE_URL is required for Docker migration.')
  const { dbPath, uploadsRoot } = resolveLegacyPaths()
  if (!fs.existsSync(dbPath)) {
    console.log(`[migrator] no legacy SQLite database found at ${dbPath}; creating migration status table only.`)
    const pool = new Pool({ connectionString: databaseUrl })
    try {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS business_os_migration_status (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          source_hash TEXT,
          status TEXT NOT NULL,
          summary_json JSONB DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
      `)
      await pool.query(
        `INSERT INTO business_os_migration_status (source_hash, status, summary_json) VALUES ($1, $2, $3::jsonb)`,
        ['fresh-install', 'completed', JSON.stringify({ freshInstall: true })]
      )
    } finally {
      await pool.end()
    }
    return
  }

  const snapshotDbPath = snapshotSqliteDatabase(dbPath)
  const sourceHash = hashFile(snapshotDbPath)
  const sqlite = new Database(snapshotDbPath, { readonly: true, fileMustExist: true })
  const pool = new Pool({ connectionString: databaseUrl })
  const batchSize = Math.max(50, Math.min(2000, Number(process.env.POSTGRES_MIGRATION_BATCH_SIZE || DEFAULT_BATCH_SIZE)))
  const summary = { sourceHash, tables: [], assetsUploaded: 0, startedAt: new Date().toISOString() }
  try {
    if (sqlite.pragma('integrity_check', { simple: true }) !== 'ok') {
      throw new Error('Legacy SQLite integrity check failed; migration aborted.')
    }
    const tables = readSqliteTables(sqlite)
    await ensureSchema(pool, sqlite, tables)
    for (const table of tables) {
      const result = await migrateTable(pool, sqlite, table, batchSize)
      summary.tables.push(result)
      console.log(`[migrator] ${table}: source=${result.source}, inserted=${result.inserted}${result.skipped ? ', skipped existing table' : ''}`)
    }
    await migrateUploadsToMinio({ uploadsRoot, summary })
    summary.finishedAt = new Date().toISOString()
    await pool.query(
      `INSERT INTO business_os_migration_status (source_hash, status, summary_json) VALUES ($1, $2, $3::jsonb)`,
      [sourceHash, 'completed', JSON.stringify(summary)]
    )
    console.log(`[migrator] completed ${summary.tables.length} tables, uploaded ${summary.assetsUploaded} assets.`)
  } catch (error) {
    summary.failedAt = new Date().toISOString()
    summary.error = error?.message || String(error)
    try {
      await pool.query(
        `INSERT INTO business_os_migration_status (source_hash, status, summary_json) VALUES ($1, $2, $3::jsonb)`,
        [sourceHash, 'failed', JSON.stringify(summary)]
      )
    } catch (_) {}
    throw error
  } finally {
    try { sqlite.close() } catch (_) {}
    await pool.end()
  }
}

if (require.main === module) {
  start().catch((error) => {
    console.error(`[migrator] failed: ${error?.message || error}`)
    process.exit(1)
  })
}

module.exports = { start }
