const PORTAL_TEXT_BY_LANGUAGE = {
  'zh-CN': {
    publicTranslation: '语言',
    followApp: '原始语言',
    externalTranslation: '外部翻译',
    translationReady: '语言已准备好',
    translationApplied: '已切换语言',
    translationOriginalApplied: '已恢复原始语言',
    translationFailed: '无法应用翻译，请重试。',
    products: '产品',
    membership: '会员',
    about: '关于',
    faq: '常见问题',
    assistant: '顾问',
    search: '搜索产品',
    searchPlaceholder: '按产品名称、说明、类别或品牌搜索',
    category: '类别',
    brand: '品牌',
    branch: '门店',
    stockStatus: '库存状态',
    all: '全部',
    allBranches: '全部门店',
    inStock: '有货',
    lowStock: '库存低',
    outOfStock: '缺货',
    noProducts: '没有符合当前筛选的产品。',
    price: '价格',
    priceHidden: '价格已隐藏',
    noDescription: '暂无说明。',
    membershipLookup: '会员查询',
    membershipPlaceholder: '输入会员编号',
    lookup: '查询会员',
    loadingPortal: '正在加载客户页面...',
    checkingMembership: '正在查询会员...',
    membershipRequired: '请输入会员编号。',
    membershipNotFound: '找不到此会员编号。',
    customer: '客户',
    memberSince: '加入日期',
    company: '公司',
    note: '备注',
    pointsBalance: '积分余额',
    pointsValue: '积分价值',
    pointsEarned: '已获得积分',
    pointsRedeemed: '已兑换积分',
    totalSales: '销售总额',
    totalReturns: '退货总额',
    purchaseHistory: '购买记录',
    returnHistory: '退货记录',
    items: '项目',
    reason: '原因',
    refund: '退款',
    noSales: '此会员暂无销售记录。',
    noReturns: '此会员暂无退货记录。',
    active: '启用',
    switch_to_light_mode: '切换到浅色模式',
    switch_to_dark_mode: '切换到深色模式',
  },
  'zh-TW': {
    publicTranslation: '語言',
    followApp: '原始語言',
    externalTranslation: '外部翻譯',
    translationReady: '語言已準備好',
    translationApplied: '已切換語言',
    translationOriginalApplied: '已恢復原始語言',
    translationFailed: '無法套用翻譯，請重試。',
    products: '產品',
    membership: '會員',
    about: '關於',
    faq: '常見問題',
    assistant: '顧問',
    search: '搜尋產品',
    searchPlaceholder: '依產品名稱、說明、類別或品牌搜尋',
    category: '類別',
    brand: '品牌',
    branch: '門市',
    stockStatus: '庫存狀態',
    all: '全部',
    allBranches: '全部門市',
    inStock: '有貨',
    lowStock: '庫存低',
    outOfStock: '缺貨',
    noProducts: '沒有符合目前篩選的產品。',
    price: '價格',
    priceHidden: '價格已隱藏',
    noDescription: '暫無說明。',
    membershipLookup: '會員查詢',
    membershipPlaceholder: '輸入會員編號',
    lookup: '查詢會員',
    loadingPortal: '正在載入客戶頁面...',
    checkingMembership: '正在查詢會員...',
    membershipRequired: '請輸入會員編號。',
    membershipNotFound: '找不到此會員編號。',
    customer: '客戶',
    memberSince: '加入日期',
    company: '公司',
    note: '備註',
    pointsBalance: '積分餘額',
    pointsValue: '積分價值',
    pointsEarned: '已獲得積分',
    pointsRedeemed: '已兌換積分',
    totalSales: '銷售總額',
    totalReturns: '退貨總額',
    purchaseHistory: '購買記錄',
    returnHistory: '退貨記錄',
    items: '項目',
    reason: '原因',
    refund: '退款',
    noSales: '此會員暫無銷售記錄。',
    noReturns: '此會員暫無退貨記錄。',
    active: '啟用',
    switch_to_light_mode: '切換到淺色模式',
    switch_to_dark_mode: '切換到深色模式',
  },
  vi: {
    publicTranslation: 'Ngôn ngữ',
    followApp: 'Ngôn ngữ gốc',
    externalTranslation: 'Dịch bên ngoài',
    translationReady: 'Ngôn ngữ đã sẵn sàng',
    translationApplied: 'Đã đổi ngôn ngữ',
    translationOriginalApplied: 'Đã khôi phục ngôn ngữ gốc',
    translationFailed: 'Không thể áp dụng bản dịch. Hãy thử lại.',
    products: 'Sản phẩm',
    membership: 'Thành viên',
    about: 'Giới thiệu',
    faq: 'Câu hỏi thường gặp',
    assistant: 'Tư vấn',
    search: 'Tìm sản phẩm',
    searchPlaceholder: 'Tìm theo tên, mô tả, danh mục hoặc thương hiệu',
    category: 'Danh mục',
    brand: 'Thương hiệu',
    branch: 'Chi nhánh',
    stockStatus: 'Tình trạng kho',
    all: 'Tất cả',
    allBranches: 'Tất cả chi nhánh',
    inStock: 'Còn hàng',
    lowStock: 'Sắp hết',
    outOfStock: 'Hết hàng',
    noProducts: 'Không có sản phẩm phù hợp bộ lọc hiện tại.',
    price: 'Giá',
    priceHidden: 'Giá đã ẩn',
    noDescription: 'Chưa có mô tả.',
    membershipLookup: 'Tra cứu thành viên',
    membershipPlaceholder: 'Nhập mã thành viên',
    lookup: 'Kiểm tra',
    loadingPortal: 'Đang tải trang khách hàng...',
    checkingMembership: 'Đang kiểm tra thành viên...',
    membershipRequired: 'Vui lòng nhập mã thành viên.',
    membershipNotFound: 'Không tìm thấy mã thành viên.',
    customer: 'Khách hàng',
    memberSince: 'Tham gia từ',
    company: 'Công ty',
    note: 'Ghi chú',
    pointsBalance: 'Số dư điểm',
    pointsValue: 'Giá trị điểm',
    pointsEarned: 'Điểm đã nhận',
    pointsRedeemed: 'Điểm đã dùng',
    totalSales: 'Tổng bán hàng',
    totalReturns: 'Tổng trả hàng',
    purchaseHistory: 'Lịch sử mua hàng',
    returnHistory: 'Lịch sử trả hàng',
    items: 'Mặt hàng',
    reason: 'Lý do',
    refund: 'Hoàn tiền',
    noSales: 'Chưa có giao dịch bán cho thành viên này.',
    noReturns: 'Chưa có giao dịch trả hàng cho thành viên này.',
    active: 'Đang dùng',
    switch_to_light_mode: 'Chuyển sang nền sáng',
    switch_to_dark_mode: 'Chuyển sang nền tối',
  },
  th: {
    publicTranslation: 'ภาษา',
    followApp: 'ภาษาต้นฉบับ',
    externalTranslation: 'แปลภายนอก',
    translationReady: 'พร้อมเปลี่ยนภาษา',
    translationApplied: 'เปลี่ยนภาษาแล้ว',
    translationOriginalApplied: 'กลับสู่ภาษาต้นฉบับแล้ว',
    translationFailed: 'ไม่สามารถแปลได้ โปรดลองอีกครั้ง',
    products: 'สินค้า',
    membership: 'สมาชิก',
    about: 'เกี่ยวกับ',
    faq: 'คำถามที่พบบ่อย',
    assistant: 'ผู้ช่วย',
    search: 'ค้นหาสินค้า',
    searchPlaceholder: 'ค้นหาตามชื่อสินค้า รายละเอียด หมวดหมู่ หรือแบรนด์',
    category: 'หมวดหมู่',
    brand: 'แบรนด์',
    branch: 'สาขา',
    stockStatus: 'สถานะสต็อก',
    all: 'ทั้งหมด',
    allBranches: 'ทุกสาขา',
    inStock: 'มีสินค้า',
    lowStock: 'สินค้าใกล้หมด',
    outOfStock: 'หมด',
    noProducts: 'ไม่พบสินค้าที่ตรงกับตัวกรองปัจจุบัน',
    price: 'ราคา',
    priceHidden: 'ซ่อนราคา',
    noDescription: 'ยังไม่มีรายละเอียด',
    membershipLookup: 'ค้นหาสมาชิก',
    membershipPlaceholder: 'กรอกหมายเลขสมาชิก',
    lookup: 'ตรวจสอบ',
    loadingPortal: 'กำลังโหลดหน้าลูกค้า...',
    checkingMembership: 'กำลังตรวจสอบสมาชิก...',
    membershipRequired: 'กรุณากรอกหมายเลขสมาชิก',
    membershipNotFound: 'ไม่พบหมายเลขสมาชิกนี้',
    customer: 'ลูกค้า',
    memberSince: 'สมาชิกตั้งแต่',
    company: 'บริษัท',
    note: 'หมายเหตุ',
    pointsBalance: 'ยอดคะแนน',
    pointsValue: 'มูลค่าคะแนน',
    pointsEarned: 'คะแนนที่ได้รับ',
    pointsRedeemed: 'คะแนนที่ใช้แล้ว',
    totalSales: 'ยอดขายรวม',
    totalReturns: 'ยอดคืนรวม',
    purchaseHistory: 'ประวัติการซื้อ',
    returnHistory: 'ประวัติการคืน',
    items: 'รายการ',
    reason: 'เหตุผล',
    refund: 'คืนเงิน',
    noSales: 'ยังไม่มีประวัติการขายสำหรับสมาชิกนี้',
    noReturns: 'ยังไม่มีประวัติการคืนสำหรับสมาชิกนี้',
    active: 'ใช้งาน',
    switch_to_light_mode: 'เปลี่ยนเป็นโหมดสว่าง',
    switch_to_dark_mode: 'เปลี่ยนเป็นโหมดมืด',
  },
  ru: {
    publicTranslation: 'Язык',
    followApp: 'Исходный язык',
    externalTranslation: 'Внешний перевод',
    translationReady: 'Языки готовы',
    translationApplied: 'Язык изменен',
    translationOriginalApplied: 'Исходный язык восстановлен',
    translationFailed: 'Не удалось применить перевод. Попробуйте еще раз.',
    products: 'Товары',
    membership: 'Клуб клиента',
    about: 'О нас',
    faq: 'Вопросы',
    assistant: 'Консультант',
    search: 'Поиск товаров',
    searchPlaceholder: 'Поиск по названию, описанию, категории или бренду',
    category: 'Категория',
    brand: 'Бренд',
    branch: 'Филиал',
    stockStatus: 'Наличие',
    all: 'Все',
    allBranches: 'Все филиалы',
    inStock: 'В наличии',
    lowStock: 'Мало',
    outOfStock: 'Нет в наличии',
    noProducts: 'Товары по текущим фильтрам не найдены.',
    price: 'Цена',
    priceHidden: 'Цена скрыта',
    noDescription: 'Описание отсутствует.',
    membershipLookup: 'Проверка клиента',
    membershipPlaceholder: 'Введите номер клиента',
    lookup: 'Проверить',
    loadingPortal: 'Загрузка клиентской страницы...',
    checkingMembership: 'Проверка клиента...',
    membershipRequired: 'Введите номер клиента.',
    membershipNotFound: 'Номер клиента не найден.',
    customer: 'Клиент',
    memberSince: 'Клиент с',
    company: 'Компания',
    note: 'Заметка',
    pointsBalance: 'Баланс баллов',
    pointsValue: 'Стоимость баллов',
    pointsEarned: 'Начислено баллов',
    pointsRedeemed: 'Использовано баллов',
    totalSales: 'Всего продаж',
    totalReturns: 'Всего возвратов',
    purchaseHistory: 'История покупок',
    returnHistory: 'История возвратов',
    items: 'Позиции',
    reason: 'Причина',
    refund: 'Возврат',
    noSales: 'Продаж для этого клиента пока нет.',
    noReturns: 'Возвратов для этого клиента пока нет.',
    active: 'Активно',
    switch_to_light_mode: 'Светлая тема',
    switch_to_dark_mode: 'Темная тема',
  },
  fr: {
    publicTranslation: 'Langue',
    followApp: 'Langue originale',
    externalTranslation: 'Traduction externe',
    translationReady: 'Langues prêtes',
    translationApplied: 'Langue changée',
    translationOriginalApplied: 'Langue originale restaurée',
    translationFailed: 'La traduction n’a pas pu être appliquée. Réessayez.',
    products: 'Produits',
    membership: 'Adhésion',
    about: 'À propos',
    faq: 'FAQ',
    assistant: 'Conseiller',
    search: 'Rechercher des produits',
    searchPlaceholder: 'Nom, description, catégorie ou marque',
    category: 'Catégorie',
    brand: 'Marque',
    branch: 'Boutique',
    stockStatus: 'Stock',
    all: 'Tout',
    allBranches: 'Toutes les boutiques',
    inStock: 'En stock',
    lowStock: 'Stock faible',
    outOfStock: 'Rupture',
    noProducts: 'Aucun produit ne correspond aux filtres.',
    price: 'Prix',
    priceHidden: 'Prix masqué',
    noDescription: 'Aucune description disponible.',
    membershipLookup: 'Recherche membre',
    membershipPlaceholder: 'Numéro de membre',
    lookup: 'Vérifier',
    loadingPortal: 'Chargement du portail client...',
    checkingMembership: 'Vérification du membre...',
    membershipRequired: 'Veuillez saisir un numéro de membre.',
    membershipNotFound: 'Numéro de membre introuvable.',
    customer: 'Client',
    memberSince: 'Membre depuis',
    company: 'Société',
    note: 'Note',
    pointsBalance: 'Solde de points',
    pointsValue: 'Valeur des points',
    pointsEarned: 'Points gagnés',
    pointsRedeemed: 'Points utilisés',
    totalSales: 'Total des ventes',
    totalReturns: 'Total des retours',
    purchaseHistory: 'Historique d’achat',
    returnHistory: 'Historique des retours',
    items: 'Articles',
    reason: 'Raison',
    refund: 'Remboursement',
    noSales: 'Aucune vente trouvée pour ce membre.',
    noReturns: 'Aucun retour trouvé pour ce membre.',
    active: 'Actif',
    switch_to_light_mode: 'Mode clair',
    switch_to_dark_mode: 'Mode sombre',
  },
  es: {
    publicTranslation: 'Idioma',
    followApp: 'Idioma original',
    externalTranslation: 'Traducción externa',
    translationReady: 'Idiomas listos',
    translationApplied: 'Idioma cambiado',
    translationOriginalApplied: 'Idioma original restaurado',
    translationFailed: 'No se pudo aplicar la traducción. Inténtalo de nuevo.',
    products: 'Productos',
    membership: 'Membresía',
    about: 'Acerca de',
    faq: 'Preguntas',
    assistant: 'Asesor',
    search: 'Buscar productos',
    searchPlaceholder: 'Nombre, descripción, categoría o marca',
    category: 'Categoría',
    brand: 'Marca',
    branch: 'Sucursal',
    stockStatus: 'Stock',
    all: 'Todo',
    allBranches: 'Todas las sucursales',
    inStock: 'Disponible',
    lowStock: 'Pocas unidades',
    outOfStock: 'Agotado',
    noProducts: 'No hay productos con estos filtros.',
    price: 'Precio',
    priceHidden: 'Precio oculto',
    noDescription: 'Sin descripción.',
    membershipLookup: 'Buscar membresía',
    membershipPlaceholder: 'Número de membresía',
    lookup: 'Consultar',
    loadingPortal: 'Cargando portal del cliente...',
    checkingMembership: 'Consultando membresía...',
    membershipRequired: 'Ingresa un número de membresía.',
    membershipNotFound: 'Número de membresía no encontrado.',
    customer: 'Cliente',
    memberSince: 'Miembro desde',
    company: 'Empresa',
    note: 'Nota',
    pointsBalance: 'Saldo de puntos',
    pointsValue: 'Valor de puntos',
    pointsEarned: 'Puntos ganados',
    pointsRedeemed: 'Puntos usados',
    totalSales: 'Total de ventas',
    totalReturns: 'Total de devoluciones',
    purchaseHistory: 'Historial de compras',
    returnHistory: 'Historial de devoluciones',
    items: 'Artículos',
    reason: 'Motivo',
    refund: 'Reembolso',
    noSales: 'Aún no hay ventas para esta membresía.',
    noReturns: 'Aún no hay devoluciones para esta membresía.',
    active: 'Activo',
    switch_to_light_mode: 'Modo claro',
    switch_to_dark_mode: 'Modo oscuro',
  },
  de: {
    publicTranslation: 'Sprache',
    followApp: 'Originalsprache',
    externalTranslation: 'Externe Übersetzung',
    translationReady: 'Sprachen bereit',
    translationApplied: 'Sprache geändert',
    translationOriginalApplied: 'Originalsprache wiederhergestellt',
    translationFailed: 'Übersetzung konnte nicht angewendet werden. Bitte erneut versuchen.',
    products: 'Produkte',
    membership: 'Mitgliedschaft',
    about: 'Über uns',
    faq: 'FAQ',
    assistant: 'Beratung',
    search: 'Produkte suchen',
    searchPlaceholder: 'Nach Name, Beschreibung, Kategorie oder Marke suchen',
    category: 'Kategorie',
    brand: 'Marke',
    branch: 'Filiale',
    stockStatus: 'Bestand',
    all: 'Alle',
    allBranches: 'Alle Filialen',
    inStock: 'Auf Lager',
    lowStock: 'Wenig Bestand',
    outOfStock: 'Ausverkauft',
    noProducts: 'Keine Produkte für die aktuellen Filter.',
    price: 'Preis',
    priceHidden: 'Preis ausgeblendet',
    noDescription: 'Keine Beschreibung verfügbar.',
    membershipLookup: 'Mitglied suchen',
    membershipPlaceholder: 'Mitgliedsnummer',
    lookup: 'Prüfen',
    active: 'Aktiv',
    switch_to_light_mode: 'Heller Modus',
    switch_to_dark_mode: 'Dunkler Modus',
  },
  ja: {
    publicTranslation: '言語',
    followApp: '元の言語',
    externalTranslation: '外部翻訳',
    translationReady: '言語を切り替えできます',
    translationApplied: '言語を変更しました',
    translationOriginalApplied: '元の言語に戻しました',
    translationFailed: '翻訳を適用できませんでした。もう一度お試しください。',
    products: '商品',
    membership: '会員',
    about: '店舗情報',
    faq: 'よくある質問',
    assistant: '相談',
    search: '商品を検索',
    searchPlaceholder: '商品名、説明、カテゴリ、ブランドで検索',
    category: 'カテゴリ',
    brand: 'ブランド',
    branch: '店舗',
    stockStatus: '在庫',
    all: 'すべて',
    allBranches: 'すべての店舗',
    inStock: '在庫あり',
    lowStock: '残りわずか',
    outOfStock: '在庫なし',
    noProducts: '現在の条件に一致する商品はありません。',
    price: '価格',
    priceHidden: '価格非表示',
    noDescription: '説明はありません。',
    membershipLookup: '会員照会',
    membershipPlaceholder: '会員番号を入力',
    lookup: '確認',
    active: '選択中',
    switch_to_light_mode: 'ライトモード',
    switch_to_dark_mode: 'ダークモード',
  },
  ko: {
    publicTranslation: '언어',
    followApp: '원래 언어',
    externalTranslation: '외부 번역',
    translationReady: '언어 준비 완료',
    translationApplied: '언어가 변경되었습니다',
    translationOriginalApplied: '원래 언어로 복원되었습니다',
    translationFailed: '번역을 적용하지 못했습니다. 다시 시도하세요.',
    products: '제품',
    membership: '멤버십',
    about: '소개',
    faq: '자주 묻는 질문',
    assistant: '상담',
    search: '제품 검색',
    searchPlaceholder: '제품명, 설명, 카테고리 또는 브랜드 검색',
    category: '카테고리',
    brand: '브랜드',
    branch: '지점',
    stockStatus: '재고 상태',
    all: '전체',
    allBranches: '모든 지점',
    inStock: '재고 있음',
    lowStock: '재고 부족',
    outOfStock: '품절',
    noProducts: '현재 필터와 일치하는 제품이 없습니다.',
    price: '가격',
    priceHidden: '가격 숨김',
    noDescription: '설명이 없습니다.',
    membershipLookup: '멤버십 조회',
    membershipPlaceholder: '멤버십 번호 입력',
    lookup: '확인',
    active: '활성',
    switch_to_light_mode: '라이트 모드',
    switch_to_dark_mode: '다크 모드',
  },
  pt: {
    publicTranslation: 'Idioma',
    followApp: 'Idioma original',
    externalTranslation: 'Tradução externa',
    translationReady: 'Idiomas prontos',
    translationApplied: 'Idioma alterado',
    translationOriginalApplied: 'Idioma original restaurado',
    translationFailed: 'Não foi possível aplicar a tradução. Tente novamente.',
    products: 'Produtos',
    membership: 'Associação',
    about: 'Sobre',
    faq: 'Perguntas',
    assistant: 'Consultor',
    search: 'Pesquisar produtos',
    searchPlaceholder: 'Nome, descrição, categoria ou marca',
    category: 'Categoria',
    brand: 'Marca',
    branch: 'Filial',
    stockStatus: 'Estoque',
    all: 'Todos',
    allBranches: 'Todas as filiais',
    inStock: 'Em estoque',
    lowStock: 'Pouco estoque',
    outOfStock: 'Esgotado',
    noProducts: 'Nenhum produto corresponde aos filtros atuais.',
    price: 'Preço',
    priceHidden: 'Preço oculto',
    noDescription: 'Sem descrição.',
    membershipLookup: 'Consultar associação',
    membershipPlaceholder: 'Número de associação',
    lookup: 'Consultar',
    active: 'Ativo',
    switch_to_light_mode: 'Modo claro',
    switch_to_dark_mode: 'Modo escuro',
  },
  it: {
    publicTranslation: 'Lingua',
    followApp: 'Lingua originale',
    externalTranslation: 'Traduzione esterna',
    translationReady: 'Lingue pronte',
    translationApplied: 'Lingua cambiata',
    translationOriginalApplied: 'Lingua originale ripristinata',
    translationFailed: 'Impossibile applicare la traduzione. Riprova.',
    products: 'Prodotti',
    membership: 'Iscrizione',
    about: 'Chi siamo',
    faq: 'FAQ',
    assistant: 'Consulente',
    search: 'Cerca prodotti',
    searchPlaceholder: 'Nome, descrizione, categoria o marca',
    category: 'Categoria',
    brand: 'Marca',
    branch: 'Filiale',
    stockStatus: 'Disponibilità',
    all: 'Tutti',
    allBranches: 'Tutte le filiali',
    inStock: 'Disponibile',
    lowStock: 'Scorte basse',
    outOfStock: 'Esaurito',
    noProducts: 'Nessun prodotto corrisponde ai filtri.',
    price: 'Prezzo',
    priceHidden: 'Prezzo nascosto',
    noDescription: 'Nessuna descrizione.',
    membershipLookup: 'Cerca iscrizione',
    membershipPlaceholder: 'Numero iscrizione',
    lookup: 'Controlla',
    active: 'Attivo',
    switch_to_light_mode: 'Modalità chiara',
    switch_to_dark_mode: 'Modalità scura',
  },
  ar: {
    publicTranslation: 'اللغة',
    followApp: 'اللغة الأصلية',
    externalTranslation: 'ترجمة خارجية',
    translationReady: 'اللغات جاهزة',
    translationApplied: 'تم تغيير اللغة',
    translationOriginalApplied: 'تمت استعادة اللغة الأصلية',
    translationFailed: 'تعذر تطبيق الترجمة. حاول مرة أخرى.',
    products: 'المنتجات',
    membership: 'العضوية',
    about: 'حول',
    faq: 'الأسئلة',
    assistant: 'المستشار',
    search: 'بحث المنتجات',
    searchPlaceholder: 'ابحث بالاسم أو الوصف أو الفئة أو العلامة',
    category: 'الفئة',
    brand: 'العلامة',
    branch: 'الفرع',
    stockStatus: 'المخزون',
    all: 'الكل',
    allBranches: 'كل الفروع',
    inStock: 'متوفر',
    lowStock: 'مخزون منخفض',
    outOfStock: 'غير متوفر',
    noProducts: 'لا توجد منتجات تطابق الفلاتر الحالية.',
    price: 'السعر',
    priceHidden: 'السعر مخفي',
    noDescription: 'لا يوجد وصف.',
    membershipLookup: 'بحث العضوية',
    membershipPlaceholder: 'أدخل رقم العضوية',
    lookup: 'تحقق',
    active: 'نشط',
  },
  hi: {
    publicTranslation: 'भाषा',
    followApp: 'मूल भाषा',
    externalTranslation: 'बाहरी अनुवाद',
    translationReady: 'भाषाएं तैयार हैं',
    translationApplied: 'भाषा बदल दी गई',
    translationOriginalApplied: 'मूल भाषा वापस आ गई',
    translationFailed: 'अनुवाद लागू नहीं हुआ। फिर कोशिश करें।',
    products: 'उत्पाद',
    membership: 'सदस्यता',
    about: 'परिचय',
    faq: 'प्रश्न',
    assistant: 'सलाहकार',
    search: 'उत्पाद खोजें',
    searchPlaceholder: 'नाम, विवरण, श्रेणी या ब्रांड से खोजें',
    category: 'श्रेणी',
    brand: 'ब्रांड',
    branch: 'शाखा',
    stockStatus: 'स्टॉक',
    all: 'सभी',
    allBranches: 'सभी शाखाएं',
    inStock: 'स्टॉक में',
    lowStock: 'कम स्टॉक',
    outOfStock: 'स्टॉक खत्म',
    noProducts: 'मौजूदा फिल्टर से कोई उत्पाद नहीं मिला।',
    price: 'कीमत',
    priceHidden: 'कीमत छिपी है',
    noDescription: 'कोई विवरण नहीं।',
    membershipLookup: 'सदस्यता खोजें',
    membershipPlaceholder: 'सदस्यता नंबर दर्ज करें',
    lookup: 'जांचें',
    active: 'सक्रिय',
  },
  id: {
    publicTranslation: 'Bahasa',
    followApp: 'Bahasa asli',
    externalTranslation: 'Terjemahan eksternal',
    translationReady: 'Bahasa siap',
    translationApplied: 'Bahasa diganti',
    translationOriginalApplied: 'Bahasa asli dipulihkan',
    translationFailed: 'Terjemahan tidak dapat diterapkan. Coba lagi.',
    products: 'Produk',
    membership: 'Keanggotaan',
    about: 'Tentang',
    faq: 'FAQ',
    assistant: 'Konsultan',
    search: 'Cari produk',
    searchPlaceholder: 'Nama, deskripsi, kategori, atau merek',
    category: 'Kategori',
    brand: 'Merek',
    branch: 'Cabang',
    stockStatus: 'Stok',
    all: 'Semua',
    allBranches: 'Semua cabang',
    inStock: 'Tersedia',
    lowStock: 'Stok rendah',
    outOfStock: 'Habis',
    noProducts: 'Tidak ada produk yang cocok dengan filter.',
    price: 'Harga',
    priceHidden: 'Harga disembunyikan',
    noDescription: 'Belum ada deskripsi.',
    membershipLookup: 'Cari keanggotaan',
    membershipPlaceholder: 'Nomor keanggotaan',
    lookup: 'Periksa',
    active: 'Aktif',
  },
  ms: {
    publicTranslation: 'Bahasa',
    followApp: 'Bahasa asal',
    externalTranslation: 'Terjemahan luar',
    translationReady: 'Bahasa sedia',
    translationApplied: 'Bahasa ditukar',
    translationOriginalApplied: 'Bahasa asal dipulihkan',
    translationFailed: 'Terjemahan tidak dapat digunakan. Cuba lagi.',
    products: 'Produk',
    membership: 'Keahlian',
    about: 'Tentang',
    faq: 'Soalan',
    assistant: 'Penasihat',
    search: 'Cari produk',
    searchPlaceholder: 'Nama, keterangan, kategori atau jenama',
    category: 'Kategori',
    brand: 'Jenama',
    branch: 'Cawangan',
    stockStatus: 'Stok',
    all: 'Semua',
    allBranches: 'Semua cawangan',
    inStock: 'Ada stok',
    lowStock: 'Stok rendah',
    outOfStock: 'Habis',
    noProducts: 'Tiada produk sepadan dengan penapis.',
    price: 'Harga',
    priceHidden: 'Harga disembunyikan',
    noDescription: 'Tiada keterangan.',
    membershipLookup: 'Cari keahlian',
    membershipPlaceholder: 'Nombor keahlian',
    lookup: 'Semak',
    active: 'Aktif',
  },
  tr: {
    publicTranslation: 'Dil',
    followApp: 'Orijinal dil',
    externalTranslation: 'Harici çeviri',
    translationReady: 'Diller hazır',
    translationApplied: 'Dil değiştirildi',
    translationOriginalApplied: 'Orijinal dil geri yüklendi',
    translationFailed: 'Çeviri uygulanamadı. Tekrar deneyin.',
    products: 'Ürünler',
    membership: 'Üyelik',
    about: 'Hakkında',
    faq: 'Sorular',
    assistant: 'Danışman',
    search: 'Ürün ara',
    searchPlaceholder: 'Ad, açıklama, kategori veya marka',
    category: 'Kategori',
    brand: 'Marka',
    branch: 'Şube',
    stockStatus: 'Stok',
    all: 'Tümü',
    allBranches: 'Tüm şubeler',
    inStock: 'Stokta',
    lowStock: 'Az stok',
    outOfStock: 'Tükendi',
    noProducts: 'Geçerli filtrelere uygun ürün yok.',
    price: 'Fiyat',
    priceHidden: 'Fiyat gizli',
    noDescription: 'Açıklama yok.',
    membershipLookup: 'Üyelik ara',
    membershipPlaceholder: 'Üyelik numarası',
    lookup: 'Kontrol et',
    active: 'Aktif',
  },
}

const PORTAL_LANGUAGE_PACKS = [
  { value: 'en', label: 'English', nativeLabel: 'English', type: 'primary', text: {} },
  { value: 'km', label: 'Khmer', nativeLabel: 'ភាសាខ្មែរ', type: 'primary', text: {} },
  { value: 'zh-CN', label: 'Chinese (Simplified)', nativeLabel: '简体中文', text: PORTAL_TEXT_BY_LANGUAGE['zh-CN'] },
  { value: 'zh-TW', label: 'Chinese (Traditional)', nativeLabel: '繁體中文', text: PORTAL_TEXT_BY_LANGUAGE['zh-TW'] },
  { value: 'vi', label: 'Vietnamese', nativeLabel: 'Tiếng Việt', text: PORTAL_TEXT_BY_LANGUAGE.vi },
  { value: 'th', label: 'Thai', nativeLabel: 'ไทย', text: PORTAL_TEXT_BY_LANGUAGE.th },
  { value: 'ru', label: 'Russian', nativeLabel: 'Русский', text: PORTAL_TEXT_BY_LANGUAGE.ru },
  { value: 'fr', label: 'French', nativeLabel: 'Français', text: PORTAL_TEXT_BY_LANGUAGE.fr },
  { value: 'es', label: 'Spanish', nativeLabel: 'Español', text: PORTAL_TEXT_BY_LANGUAGE.es },
  { value: 'de', label: 'German', nativeLabel: 'Deutsch', text: PORTAL_TEXT_BY_LANGUAGE.de },
  { value: 'ja', label: 'Japanese', nativeLabel: '日本語', text: PORTAL_TEXT_BY_LANGUAGE.ja },
  { value: 'ko', label: 'Korean', nativeLabel: '한국어', text: PORTAL_TEXT_BY_LANGUAGE.ko },
  { value: 'pt', label: 'Portuguese', nativeLabel: 'Português', text: PORTAL_TEXT_BY_LANGUAGE.pt },
  { value: 'it', label: 'Italian', nativeLabel: 'Italiano', text: PORTAL_TEXT_BY_LANGUAGE.it },
  { value: 'ar', label: 'Arabic', nativeLabel: 'العربية', dir: 'rtl', text: PORTAL_TEXT_BY_LANGUAGE.ar },
  { value: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', text: PORTAL_TEXT_BY_LANGUAGE.hi },
  { value: 'id', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia', text: PORTAL_TEXT_BY_LANGUAGE.id },
  { value: 'ms', label: 'Malay', nativeLabel: 'Bahasa Melayu', text: PORTAL_TEXT_BY_LANGUAGE.ms },
  { value: 'tr', label: 'Turkish', nativeLabel: 'Türkçe', text: PORTAL_TEXT_BY_LANGUAGE.tr },
]

const PACK_BY_VALUE = new Map(PORTAL_LANGUAGE_PACKS.map((pack) => [pack.value, pack]))
const PACK_BY_LOWER = new Map(PORTAL_LANGUAGE_PACKS.map((pack) => [pack.value.toLowerCase(), pack]))

export const FIRST_PARTY_PORTAL_LANGUAGE_OPTIONS = PORTAL_LANGUAGE_PACKS.map((pack) => ({
  value: pack.value,
  label: pack.label,
  nativeLabel: pack.nativeLabel,
  dir: pack.dir || 'ltr',
  type: pack.type || 'expanded',
}))

export function normalizeFirstPartyPortalLanguage(value) {
  const key = String(value || '').trim().toLowerCase()
  return PACK_BY_LOWER.get(key)?.value || ''
}

export function isFirstPartyPortalLanguage(value) {
  return !!normalizeFirstPartyPortalLanguage(value)
}

export function getPortalLanguageText(language, key) {
  const normalized = normalizeFirstPartyPortalLanguage(language)
  const text = PACK_BY_VALUE.get(normalized)?.text?.[key]
  return typeof text === 'string' && text.trim() ? text : ''
}
