param(
  [ValidateSet('Release', 'Install', 'Start', 'Update', 'Backup', 'Restore', 'Doctor', 'Publish')]
  [string]$Action = 'Doctor',
  [string]$Version = '',
  [string]$Image = '',
  [string]$BackupPath = ''
)

$ErrorActionPreference = 'Stop'

function Write-Step($message) { Write-Host "[INFO] $message" }
function Write-Ok($message) { Write-Host "[OK] $message" }
function Write-Warn($message) { Write-Host "[WARN] $message" }
function Fail($message, $code = 1) { Write-Host "[ERROR] $message"; exit $code }

function Resolve-Root {
  return (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
}

$Root = Resolve-Root
$ComposeFile = Join-Path $Root 'ops\docker\compose.release.yml'
$Dockerfile = Join-Path $Root 'ops\docker\Dockerfile.release'
$RuntimeDir = Join-Path $Root 'ops\runtime\docker-release'
$SecretDir = Join-Path $RuntimeDir 'secrets'
$BackupDir = Join-Path $RuntimeDir 'backups'
$EnvFile = Join-Path $RuntimeDir 'docker-release.env'
$DockerConfig = Join-Path $RuntimeDir 'docker-config'
$DefaultImage = 'ghcr.io/leangcosmetics/business-os'
$DockerKitDir = Join-Path (Join-Path $Root 'release') 'business-os-docker'

function Ensure-Dir($path) {
  if (-not (Test-Path -LiteralPath $path)) {
    New-Item -ItemType Directory -Force -Path $path | Out-Null
  }
}

function Find-Executable($names, $fallbacks = @()) {
  foreach ($name in $names) {
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Source) { return $cmd.Source }
  }
  foreach ($candidate in $fallbacks) {
    if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate }
  }
  return ''
}

function Invoke-ProcessWithTimeout($filePath, [string[]]$arguments = @(), [int]$timeoutSeconds = 20) {
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $filePath
  $psi.Arguments = (($arguments | ForEach-Object {
    $arg = [string]$_
    if ($arg -match '[\s"]') {
      '"' + ($arg -replace '"', '\"') + '"'
    } else {
      $arg
    }
  }) -join ' ')
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true

  $process = New-Object System.Diagnostics.Process
  $process.StartInfo = $psi
  try {
    [void]$process.Start()
    if (-not $process.WaitForExit($timeoutSeconds * 1000)) {
      try { $process.Kill($true) } catch { try { $process.Kill() } catch {} }
      return [pscustomobject]@{ ExitCode = 124; TimedOut = $true; Stdout = ''; Stderr = "Timed out after ${timeoutSeconds}s" }
    }
    return [pscustomobject]@{ ExitCode = $process.ExitCode; TimedOut = $false; Stdout = $process.StandardOutput.ReadToEnd(); Stderr = $process.StandardError.ReadToEnd() }
  } catch {
    return [pscustomobject]@{ ExitCode = 1; TimedOut = $false; Stdout = ''; Stderr = $_.Exception.Message }
  } finally {
    $process.Dispose()
  }
}

function Resolve-Docker {
  $docker = Find-Executable @('docker.exe', 'docker') @('C:\Program Files\Docker\Docker\resources\bin\docker.exe')
  if (-not $docker) { Fail 'Docker CLI was not found. Install Docker Desktop first.' }
  return $docker
}

function Invoke-Docker {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$DockerArgs,
    [switch]$AllowFailure
  )
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  & $docker @DockerArgs
  $code = $LASTEXITCODE
  if ($code -ne 0 -and -not $AllowFailure) { Fail "Docker command failed: docker $($DockerArgs -join ' ')" $code }
  return $code
}

function Invoke-Compose {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$ComposeArgs,
    [switch]$AllowFailure
  )
  $dockerArgs = @('compose', '--env-file', $EnvFile, '-f', $ComposeFile) + $ComposeArgs
  return Invoke-Docker -DockerArgs $dockerArgs -AllowFailure:$AllowFailure
}

function New-Secret([int]$bytes = 32) {
  $buffer = New-Object byte[] $bytes
  $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    $rng.Dispose()
  }
  return [Convert]::ToBase64String($buffer).TrimEnd('=').Replace('+', 'A').Replace('/', 'B')
}

function Read-EnvFile {
  $map = @{}
  if (-not (Test-Path -LiteralPath $EnvFile)) { return $map }
  foreach ($line in Get-Content -LiteralPath $EnvFile) {
    if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
    $parts = $line.Split('=', 2)
    $map[$parts[0]] = $parts[1]
  }
  return $map
}

function Write-EnvFile($values) {
  Ensure-Dir $RuntimeDir
  $lines = @(
    '# Generated by Business OS Docker release automation.',
    '# Do not commit this file. It contains runtime-only settings.',
    "BUSINESS_OS_IMAGE=$($values.BUSINESS_OS_IMAGE)",
    "BUSINESS_OS_DOCKER_DATA_MODE=$($values.BUSINESS_OS_DOCKER_DATA_MODE)",
    "BUSINESS_OS_PUBLIC_URL=$($values.BUSINESS_OS_PUBLIC_URL)",
    "BUSINESS_OS_ADMIN_URL=$($values.BUSINESS_OS_ADMIN_URL)",
    "POSTGRES_DB=$($values.POSTGRES_DB)",
    "POSTGRES_USER=$($values.POSTGRES_USER)",
    "POSTGRES_PASSWORD=$($values.POSTGRES_PASSWORD)",
    "MINIO_ROOT_USER=$($values.MINIO_ROOT_USER)",
    "MINIO_ROOT_PASSWORD=$($values.MINIO_ROOT_PASSWORD)",
    "S3_BUCKET=$($values.S3_BUCKET)",
    "CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE=$($values.CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE)",
    "BUSINESS_OS_LEGACY_ROOT=$($values.BUSINESS_OS_LEGACY_ROOT)",
    'APP_BIND_HOST=127.0.0.1',
    'APP_PORT=4000',
    "DATABASE_DRIVER=$($values.DATABASE_DRIVER)",
    "OBJECT_STORAGE_DRIVER=$($values.OBJECT_STORAGE_DRIVER)",
    "DATABASE_URL=$($values.DATABASE_URL)",
    "SQLITE_SAFE_WRITER_MODE=$($values.SQLITE_SAFE_WRITER_MODE)",
    "IMPORT_QUEUE_CONCURRENCY=$($values.IMPORT_QUEUE_CONCURRENCY)",
    "MEDIA_QUEUE_CONCURRENCY=$($values.MEDIA_QUEUE_CONCURRENCY)",
    "IMPORT_BATCH_PAUSE_MS=$($values.IMPORT_BATCH_PAUSE_MS)",
    "IMPORT_WORKER_REPLICAS=$($values.IMPORT_WORKER_REPLICAS)",
    "MEDIA_WORKER_REPLICAS=$($values.MEDIA_WORKER_REPLICAS)",
    'JOB_QUEUE_DRIVER=bullmq',
    'BUSINESS_OS_RUNTIME=docker'
  )
  Set-Content -LiteralPath $EnvFile -Value $lines -Encoding ASCII
  Write-Ok "Docker release env ready: $EnvFile"
}

function Ensure-Env {
  Ensure-Dir $RuntimeDir
  Ensure-Dir $SecretDir
  Ensure-Dir $BackupDir
  Ensure-Dir $DockerConfig

  $existing = Read-EnvFile
  $tag = if ($Version) { $Version } else { if ($existing.BUSINESS_OS_IMAGE) { ($existing.BUSINESS_OS_IMAGE -split ':')[-1] } else { 'latest' } }
  $imageBase = if ($Image) { $Image } else { if ($existing.BUSINESS_OS_IMAGE) { ($existing.BUSINESS_OS_IMAGE -replace ':[^/:]+$', '') } else { $DefaultImage } }
  $tokenFile = if ($existing.CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE) { $existing.CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE } else { Join-Path $SecretDir 'cloudflare-tunnel.token' }

  if (-not (Test-Path -LiteralPath $tokenFile)) {
    New-Item -ItemType File -Force -Path $tokenFile | Out-Null
    Write-Warn "Cloudflare token file created empty: $tokenFile"
    Write-Warn 'Paste the tunnel token into that file before starting the public release runtime.'
  }

  $values = [ordered]@{
    BUSINESS_OS_IMAGE = "$imageBase`:$tag"
    BUSINESS_OS_DOCKER_DATA_MODE = if ($existing.BUSINESS_OS_DOCKER_DATA_MODE) { $existing.BUSINESS_OS_DOCKER_DATA_MODE } else { 'sqlite' }
    BUSINESS_OS_PUBLIC_URL = if ($existing.BUSINESS_OS_PUBLIC_URL) { $existing.BUSINESS_OS_PUBLIC_URL } else { 'https://leangcosmetics.dpdns.org' }
    BUSINESS_OS_ADMIN_URL = if ($existing.BUSINESS_OS_ADMIN_URL) { $existing.BUSINESS_OS_ADMIN_URL } else { 'https://admin.leangcosmetics.dpdns.org' }
    POSTGRES_DB = if ($existing.POSTGRES_DB) { $existing.POSTGRES_DB } else { 'business_os' }
    POSTGRES_USER = if ($existing.POSTGRES_USER) { $existing.POSTGRES_USER } else { 'business_os' }
    POSTGRES_PASSWORD = if ($existing.POSTGRES_PASSWORD) { $existing.POSTGRES_PASSWORD } else { New-Secret 36 }
    MINIO_ROOT_USER = if ($existing.MINIO_ROOT_USER) { $existing.MINIO_ROOT_USER } else { 'businessos' }
    MINIO_ROOT_PASSWORD = if ($existing.MINIO_ROOT_PASSWORD) { $existing.MINIO_ROOT_PASSWORD } else { New-Secret 36 }
    S3_BUCKET = if ($existing.S3_BUCKET) { $existing.S3_BUCKET } else { 'business-os-assets' }
    CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE = $tokenFile
    BUSINESS_OS_LEGACY_ROOT = if ($existing.BUSINESS_OS_LEGACY_ROOT) { $existing.BUSINESS_OS_LEGACY_ROOT } else { $Root }
    DATABASE_DRIVER = if ($existing.DATABASE_DRIVER) { $existing.DATABASE_DRIVER } else { 'sqlite' }
    OBJECT_STORAGE_DRIVER = if ($existing.OBJECT_STORAGE_DRIVER) { $existing.OBJECT_STORAGE_DRIVER } else { 'local' }
    DATABASE_URL = if ($existing.DATABASE_URL) { $existing.DATABASE_URL } else { '' }
    SQLITE_SAFE_WRITER_MODE = if ($existing.SQLITE_SAFE_WRITER_MODE) { $existing.SQLITE_SAFE_WRITER_MODE } else { '1' }
    IMPORT_QUEUE_CONCURRENCY = if ($existing.IMPORT_QUEUE_CONCURRENCY) { $existing.IMPORT_QUEUE_CONCURRENCY } else { '1' }
    MEDIA_QUEUE_CONCURRENCY = if ($existing.MEDIA_QUEUE_CONCURRENCY) { $existing.MEDIA_QUEUE_CONCURRENCY } else { '2' }
    IMPORT_BATCH_PAUSE_MS = if ($existing.IMPORT_BATCH_PAUSE_MS) { $existing.IMPORT_BATCH_PAUSE_MS } else { '50' }
    IMPORT_WORKER_REPLICAS = if ($existing.IMPORT_WORKER_REPLICAS) { $existing.IMPORT_WORKER_REPLICAS } else { '1' }
    MEDIA_WORKER_REPLICAS = if ($existing.MEDIA_WORKER_REPLICAS) { $existing.MEDIA_WORKER_REPLICAS } else { '1' }
  }
  if ($values.BUSINESS_OS_DOCKER_DATA_MODE -eq 'sqlite') {
    $values.DATABASE_DRIVER = 'sqlite'
    $values.OBJECT_STORAGE_DRIVER = 'local'
    $values.DATABASE_URL = ''
    $values.SQLITE_SAFE_WRITER_MODE = '1'
    $values.IMPORT_QUEUE_CONCURRENCY = '1'
    $values.IMPORT_BATCH_PAUSE_MS = '50'
    $values.IMPORT_WORKER_REPLICAS = '1'
    $values.MEDIA_WORKER_REPLICAS = '1'
  }
  Write-EnvFile $values
  return $values
}

function Ensure-DockerReady {
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  Write-Step 'Checking Docker engine readiness...'
  $result = Invoke-ProcessWithTimeout $docker @('info', '--format', '{{.ServerVersion}}') 20
  if ($result.TimedOut) {
    Fail 'Docker CLI did not answer within 20 seconds. Open Docker Desktop, wait until it says Running, then retry.'
  }
  if ($result.ExitCode -ne 0) {
    Fail 'Docker Desktop is not running. Open Docker Desktop, wait until it says Running, then retry.'
  }
  Write-Ok 'Docker engine is reachable.'
}

function Get-VersionTag {
  if ($Version) { return $Version }
  $pkg = Get-Content -Raw (Join-Path $Root 'backend\package.json') | ConvertFrom-Json
  return "v$($pkg.version)-$(Get-Date -Format 'yyyyMMddHHmm')"
}

function Test-ReleaseContents {
  $compose = Get-Content -Raw $ComposeFile
  if ($compose -match '\.\./\.\.:/app' -or $compose -match 'node_modules') {
    Fail 'Release Compose must not bind-mount source folders or node_modules.'
  }
  if ($compose -match 'BUSINESS_OS_ENFORCE_POSTGRES:\s*"1"') {
    Fail 'Release Compose must not force Postgres until the route-level Postgres adapter is complete.'
  }
  if ($compose -notmatch 'business_os_runtime:/runtime') {
    Fail 'Release Compose must keep app data inside the Docker runtime volume.'
  }
}

function Copy-Directory($source, $destination) {
  if (-not (Test-Path -LiteralPath $source)) { return }
  Ensure-Dir $destination
  Copy-Item -Path (Join-Path $source '*') -Destination $destination -Recurse -Force
}

function Write-DockerReleaseKit($imageName) {
  $preserveRuntime = Join-Path $env:TEMP "business-os-docker-kit-runtime-$([guid]::NewGuid().ToString('N'))"
  $existingRuntime = Join-Path $DockerKitDir 'ops\runtime\docker-release'
  if (Test-Path -LiteralPath $existingRuntime) {
    Ensure-Dir $preserveRuntime
    Copy-Item -LiteralPath $existingRuntime -Destination $preserveRuntime -Recurse -Force
  }

  if (Test-Path -LiteralPath $DockerKitDir) {
    Remove-Item -LiteralPath $DockerKitDir -Recurse -Force
  }
  Ensure-Dir $DockerKitDir
  Ensure-Dir (Join-Path $DockerKitDir 'run\docker')
  Ensure-Dir (Join-Path $DockerKitDir 'ops\docker')
  Ensure-Dir (Join-Path $DockerKitDir 'ops\scripts\powershell')
  Ensure-Dir (Join-Path $DockerKitDir 'ops\scripts\runtime')

  Copy-Item -LiteralPath (Join-Path $Root 'Start Business OS.bat') -Destination (Join-Path $DockerKitDir 'Start Business OS.bat') -Force
  Copy-Directory (Join-Path $Root 'run\docker') (Join-Path $DockerKitDir 'run\docker')
  Copy-Item -LiteralPath $ComposeFile -Destination (Join-Path $DockerKitDir 'ops\docker\compose.release.yml') -Force
  Copy-Item -LiteralPath $Dockerfile -Destination (Join-Path $DockerKitDir 'ops\docker\Dockerfile.release') -Force
  Copy-Item -LiteralPath (Join-Path $Root 'ops\scripts\powershell\docker-release.ps1') -Destination (Join-Path $DockerKitDir 'ops\scripts\powershell\docker-release.ps1') -Force
  Copy-Directory (Join-Path $Root 'ops\scripts\runtime') (Join-Path $DockerKitDir 'ops\scripts\runtime')

  if (Test-Path -LiteralPath (Join-Path $preserveRuntime 'docker-release')) {
    Ensure-Dir (Join-Path $DockerKitDir 'ops\runtime')
    Copy-Item -LiteralPath (Join-Path $preserveRuntime 'docker-release') -Destination (Join-Path $DockerKitDir 'ops\runtime') -Recurse -Force
  }

  $kitEnvDir = Join-Path $DockerKitDir 'ops\runtime\docker-release'
  Ensure-Dir $kitEnvDir
  $kitSecretsDir = Join-Path $kitEnvDir 'secrets'
  Ensure-Dir $kitSecretsDir
  $kitEnvFile = Join-Path $kitEnvDir 'docker-release.env'
  $kitToken = Join-Path $kitSecretsDir 'cloudflare-tunnel.token'
  if (-not (Test-Path -LiteralPath $kitToken)) {
    New-Item -ItemType File -Force -Path $kitToken | Out-Null
  }
  if (-not (Test-Path -LiteralPath $kitEnvFile)) {
    $values = [ordered]@{
      BUSINESS_OS_IMAGE = $imageName
      BUSINESS_OS_DOCKER_DATA_MODE = 'sqlite'
      BUSINESS_OS_PUBLIC_URL = 'https://leangcosmetics.dpdns.org'
      BUSINESS_OS_ADMIN_URL = 'https://admin.leangcosmetics.dpdns.org'
      POSTGRES_DB = 'business_os'
      POSTGRES_USER = 'business_os'
      POSTGRES_PASSWORD = New-Secret 36
      MINIO_ROOT_USER = 'businessos'
      MINIO_ROOT_PASSWORD = New-Secret 36
      S3_BUCKET = 'business-os-assets'
      CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE = $kitToken
      BUSINESS_OS_LEGACY_ROOT = $DockerKitDir
      DATABASE_DRIVER = 'sqlite'
      OBJECT_STORAGE_DRIVER = 'local'
      DATABASE_URL = ''
      SQLITE_SAFE_WRITER_MODE = '1'
      IMPORT_QUEUE_CONCURRENCY = '1'
      MEDIA_QUEUE_CONCURRENCY = '2'
      IMPORT_BATCH_PAUSE_MS = '50'
      IMPORT_WORKER_REPLICAS = '1'
      MEDIA_WORKER_REPLICAS = '1'
    }
    $oldRuntimeDir = $RuntimeDir
    $oldEnvFile = $EnvFile
    try {
      $script:RuntimeDir = $kitEnvDir
      $script:EnvFile = $kitEnvFile
      Write-EnvFile $values
    } finally {
      $script:RuntimeDir = $oldRuntimeDir
      $script:EnvFile = $oldEnvFile
    }
  }

  @"
Business OS Docker Release
==========================

Use this folder on a laptop where you do not want to expose source code.

1. Double-click Start Business OS.bat.
2. If Docker Desktop is missing, install it and restart Windows if Docker asks.
3. Put the Cloudflare tunnel token in:
   ops\runtime\docker-release\secrets\cloudflare-tunnel.token
4. Start again and open:
   https://admin.leangcosmetics.dpdns.org
   https://leangcosmetics.dpdns.org/public

This folder contains launcher/support scripts and Docker configuration only.
The app itself runs from the private Docker image:
  $imageName

Live app data is stored in a Docker volume. If this folder contains a
business-os-data folder on first start, Business OS copies it into the Docker
runtime volume once and leaves the source folder untouched.
"@ | Set-Content -LiteralPath (Join-Path $DockerKitDir 'README.txt') -Encoding UTF8

  if (Test-Path -LiteralPath $preserveRuntime) {
    Remove-Item -LiteralPath $preserveRuntime -Recurse -Force -ErrorAction SilentlyContinue
  }
  Write-Ok "Docker release kit ready: $DockerKitDir"
}

function Invoke-Release {
  Ensure-DockerReady
  Test-ReleaseContents
  $tag = Get-VersionTag
  $imageName = if ($Image) { $Image } else { $DefaultImage }
  $fullImage = "$imageName`:$tag"
  Write-Step "Building Docker release image $fullImage"
  Invoke-Docker -DockerArgs @('build', '-f', $Dockerfile, '-t', $fullImage, '-t', "$imageName`:latest", $Root) | Out-Null
  Ensure-Env | Out-Null
  $envMap = Read-EnvFile
  $envMap.BUSINESS_OS_IMAGE = $fullImage
  Write-EnvFile $envMap
  Write-DockerReleaseKit $fullImage
  Write-Ok "Release image built: $fullImage"
  Write-Ok 'Docker release is runnable without source bind mounts. Data is kept in the Docker runtime volume.'
}

function Invoke-Publish {
  Ensure-DockerReady
  $envMap = Ensure-Env
  Write-Step "Pushing $($envMap.BUSINESS_OS_IMAGE)"
  Invoke-Docker -DockerArgs @('push', $envMap.BUSINESS_OS_IMAGE)
  $latest = ($envMap.BUSINESS_OS_IMAGE -replace ':[^/:]+$', ':latest')
  Invoke-Docker -DockerArgs @('push', $latest) -AllowFailure
}

function Invoke-Install {
  Ensure-DockerReady
  Ensure-Env | Out-Null
  Write-Step 'Pulling release images...'
  Invoke-Compose -ComposeArgs @('pull')
  Write-Step 'Starting database, queues, and storage...'
  Invoke-Compose -ComposeArgs @('up', '-d', 'postgres', 'redis-queue', 'redis-cache', 'minio')
  Write-Ok 'Base Docker services are installed.'
}

function Invoke-Start {
  Ensure-DockerReady
  Ensure-Env | Out-Null
  $envMap = Read-EnvFile
  if (($envMap.BUSINESS_OS_DOCKER_DATA_MODE -eq 'postgres') -or ($envMap.DATABASE_DRIVER -eq 'postgres')) {
    Write-Step 'Running Postgres migration profile...'
    Invoke-Compose -ComposeArgs @('--profile', 'postgres-migrate', 'run', '--rm', 'migrator')
  } else {
    Write-Step 'Adopting existing local data into the Docker runtime volume when needed...'
    Invoke-Compose -ComposeArgs @('--profile', 'migrate', 'run', '--rm', 'legacy-adopter')
  }
  Write-Step 'Starting Business OS Docker release runtime...'
  Invoke-Compose -ComposeArgs @('up', '-d', '--remove-orphans')
  Test-ReleaseHealth
  Write-Ok 'Docker release runtime is healthy.'
}

function Get-ComposeVolumeName($volumeKey) {
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  $names = & $docker volume ls `
    --filter 'label=com.docker.compose.project=business-os-release' `
    --filter "label=com.docker.compose.volume=$volumeKey" `
    --format '{{.Name}}' 2>$null
  if ($LASTEXITCODE -eq 0) {
    $name = @($names | Where-Object { $_ -and $_.Trim() } | Select-Object -First 1)
    if ($name) { return [string]$name }
  }
  return "business-os-release_$volumeKey"
}

function Invoke-VolumeTar($volumeName, $targetDir, $archiveName, [switch]$Restore) {
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  $targetDir = [System.IO.Path]::GetFullPath($targetDir)
  Ensure-Dir $targetDir
  if ($Restore) {
    Invoke-Docker -DockerArgs @(
      'run', '--rm',
      '-v', "${volumeName}:/runtime",
      '-v', "${targetDir}:/backup:ro",
      'alpine:3.20',
      'sh', '-lc',
      "set -e; find /runtime -mindepth 1 -maxdepth 1 -exec rm -rf {} +; tar -xzf /backup/$archiveName -C /runtime"
    )
  } else {
    Invoke-Docker -DockerArgs @(
      'run', '--rm',
      '-v', "${volumeName}:/runtime:ro",
      '-v', "${targetDir}:/backup",
      'alpine:3.20',
      'sh', '-lc',
      "set -e; cd /runtime; tar -czf /backup/$archiveName ."
    )
  }
}

function Test-ReleaseHealth {
  $envMap = Read-EnvFile
  $port = if ($envMap.APP_PORT) { $envMap.APP_PORT } else { '4000' }
  $url = "http://127.0.0.1:$port/health"
  Write-Step "Waiting for Docker release health at $url"
  $deadline = (Get-Date).AddSeconds(180)
  do {
    try {
      $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5
      if ([int]$response.StatusCode -eq 200) { return $true }
    } catch {}
    Start-Sleep -Seconds 3
  } while ((Get-Date) -lt $deadline)
  Invoke-Compose -ComposeArgs @('logs', '--tail', '120', 'app') -AllowFailure
  Fail "Docker release app did not become healthy at $url"
}

function Invoke-Backup {
  Ensure-DockerReady
  $envMap = Ensure-Env
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $target = Join-Path $BackupDir $stamp
  Ensure-Dir $target
  if (($envMap.BUSINESS_OS_DOCKER_DATA_MODE -eq 'sqlite') -or ($envMap.DATABASE_DRIVER -eq 'sqlite')) {
    $runtimeVolume = Get-ComposeVolumeName 'business_os_runtime'
    Write-Step "Backing up Docker runtime volume $runtimeVolume to $target"
    Invoke-VolumeTar $runtimeVolume $target 'runtime.tgz'
    Set-Content -LiteralPath (Join-Path $target 'backup.json') -Encoding UTF8 -Value (@{
      createdAt = (Get-Date).ToString('o')
      mode = 'sqlite-docker-volume'
      runtimeVolume = $runtimeVolume
      archive = 'runtime.tgz'
    } | ConvertTo-Json -Depth 4)
    Write-Ok "Backup created: $target"
    return
  }
  Write-Step "Backing up Postgres to $target"
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  & $docker compose --env-file $EnvFile -f $ComposeFile exec -T postgres pg_dump -U $envMap.POSTGRES_USER $envMap.POSTGRES_DB | Set-Content -LiteralPath (Join-Path $target 'postgres.sql') -Encoding UTF8
  if ($LASTEXITCODE -ne 0) { Fail 'Postgres backup failed.' }
  Invoke-Compose -ComposeArgs @('run', '--rm', '--entrypoint', 'sh', 'minio', '-lc', 'cd /data && tar -czf /tmp/minio-data.tgz .') -AllowFailure | Out-Null
  Write-Ok "Backup created: $target"
}

function Invoke-Update {
  Ensure-DockerReady
  $envMap = Ensure-Env
  $previousFile = Join-Path $RuntimeDir 'previous-image.txt'
  Set-Content -LiteralPath $previousFile -Value $envMap.BUSINESS_OS_IMAGE -Encoding ASCII
  Invoke-Backup
  Write-Step 'Pulling new release image...'
  Invoke-Compose -ComposeArgs @('pull')
  Write-Step 'Applying migration and restarting...'
  Invoke-Start
  $code = Invoke-Compose -ComposeArgs @('ps') -AllowFailure
  if ($code -ne 0) {
    $previous = Get-Content -Raw $previousFile
    Write-Warn "Update health failed. Rolling back to $previous"
    $envMap.BUSINESS_OS_IMAGE = $previous.Trim()
    Write-EnvFile $envMap
    Invoke-Compose -ComposeArgs @('up', '-d', '--remove-orphans')
    Fail 'Update rolled back because health checks failed.'
  }
  Write-Ok 'Update completed.'
}

function Invoke-Restore {
  if (-not $BackupPath) { Fail 'Set -BackupPath to a backup folder containing runtime.tgz or postgres.sql.' }
  $runtimeArchive = Join-Path $BackupPath 'runtime.tgz'
  if (Test-Path -LiteralPath $runtimeArchive) {
    Ensure-DockerReady
    Ensure-Env | Out-Null
    Write-Warn 'Restore will replace the Docker runtime data volume.'
    Invoke-Compose -ComposeArgs @('stop', 'app', 'import-worker', 'media-worker', 'cloudflared') -AllowFailure | Out-Null
    $runtimeVolume = Get-ComposeVolumeName 'business_os_runtime'
    Invoke-VolumeTar $runtimeVolume ([System.IO.Path]::GetFullPath($BackupPath)) 'runtime.tgz' -Restore
    Invoke-Compose -ComposeArgs @('up', '-d', '--remove-orphans')
    Test-ReleaseHealth
    Write-Ok 'Restore completed.'
    return
  }
  $sql = Join-Path $BackupPath 'postgres.sql'
  if (-not (Test-Path -LiteralPath $sql)) { Fail "Backup does not contain postgres.sql: $BackupPath" }
  Ensure-DockerReady
  $envMap = Ensure-Env
  Write-Warn 'Restore will replace Postgres data in the running release database.'
  Invoke-Compose -ComposeArgs @('stop', 'app', 'import-worker', 'media-worker') -AllowFailure | Out-Null
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  Get-Content -LiteralPath $sql | & $docker compose --env-file $EnvFile -f $ComposeFile exec -T postgres psql -U $envMap.POSTGRES_USER $envMap.POSTGRES_DB
  if ($LASTEXITCODE -ne 0) { Fail 'Postgres restore failed.' }
  Invoke-Compose -ComposeArgs @('up', '-d')
  Write-Ok 'Restore completed.'
}

function Invoke-Doctor {
  Ensure-Env | Out-Null
  Test-ReleaseContents
  Ensure-DockerReady
  Invoke-Docker -DockerArgs @('compose', '--env-file', $EnvFile, '-f', $ComposeFile, 'config', '--quiet') | Out-Null
  Invoke-Compose -ComposeArgs @('ps') -AllowFailure | Out-Null
  Write-Ok 'Docker release diagnostics completed.'
  Write-Ok 'Docker release uses private images plus Docker volumes for app data; no source bind mount is required.'
}

Set-Location $Root
switch ($Action) {
  'Release' { Invoke-Release }
  'Publish' { Invoke-Publish }
  'Install' { Invoke-Install }
  'Start' { Invoke-Start }
  'Update' { Invoke-Update }
  'Backup' { Invoke-Backup }
  'Restore' { Invoke-Restore }
  'Doctor' { Invoke-Doctor }
}
