param(
  [ValidateSet('Release', 'Install', 'Start', 'Update', 'Backup', 'Restore', 'Doctor', 'Publish')]
  [string]$Action = 'Doctor',
  [string]$Version = '',
  [string]$Image = '',
  [string]$BackupPath = ''
)

$ErrorActionPreference = 'Stop'

function Write-Step($message) { Write-Host "[INFO] $message" }
function Write-Ok($message) { Write-Host "[OK] $message" }
function Write-Warn($message) { Write-Host "[WARN] $message" }
function Fail($message, $code = 1) { Write-Host "[ERROR] $message"; exit $code }

function Resolve-Root {
  return (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
}

$Root = Resolve-Root
$ComposeFile = Join-Path $Root 'ops\docker\compose.release.yml'
$Dockerfile = Join-Path $Root 'ops\docker\Dockerfile.release'
$RuntimeDir = Join-Path $Root 'ops\runtime\docker-release'
$SecretDir = Join-Path $RuntimeDir 'secrets'
$BackupDir = Join-Path $RuntimeDir 'backups'
$EnvFile = Join-Path $RuntimeDir 'docker-release.env'
$DockerConfig = Join-Path $RuntimeDir 'docker-config'
$DefaultImage = 'ghcr.io/leangcosmetics/business-os'

function Ensure-Dir($path) {
  if (-not (Test-Path -LiteralPath $path)) {
    New-Item -ItemType Directory -Force -Path $path | Out-Null
  }
}

function Find-Executable($names, $fallbacks = @()) {
  foreach ($name in $names) {
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Source) { return $cmd.Source }
  }
  foreach ($candidate in $fallbacks) {
    if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate }
  }
  return ''
}

function Invoke-ProcessWithTimeout($filePath, [string[]]$arguments = @(), [int]$timeoutSeconds = 20) {
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $filePath
  $psi.Arguments = (($arguments | ForEach-Object {
    $arg = [string]$_
    if ($arg -match '[\s"]') {
      '"' + ($arg -replace '"', '\"') + '"'
    } else {
      $arg
    }
  }) -join ' ')
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true

  $process = New-Object System.Diagnostics.Process
  $process.StartInfo = $psi
  try {
    [void]$process.Start()
    if (-not $process.WaitForExit($timeoutSeconds * 1000)) {
      try { $process.Kill($true) } catch { try { $process.Kill() } catch {} }
      return [pscustomobject]@{ ExitCode = 124; TimedOut = $true; Stdout = ''; Stderr = "Timed out after ${timeoutSeconds}s" }
    }
    return [pscustomobject]@{ ExitCode = $process.ExitCode; TimedOut = $false; Stdout = $process.StandardOutput.ReadToEnd(); Stderr = $process.StandardError.ReadToEnd() }
  } catch {
    return [pscustomobject]@{ ExitCode = 1; TimedOut = $false; Stdout = ''; Stderr = $_.Exception.Message }
  } finally {
    $process.Dispose()
  }
}

function Resolve-Docker {
  $docker = Find-Executable @('docker.exe', 'docker') @('C:\Program Files\Docker\Docker\resources\bin\docker.exe')
  if (-not $docker) { Fail 'Docker CLI was not found. Install Docker Desktop first.' }
  return $docker
}

function Invoke-Docker {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$DockerArgs,
    [switch]$AllowFailure
  )
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  & $docker @DockerArgs
  $code = $LASTEXITCODE
  if ($code -ne 0 -and -not $AllowFailure) { Fail "Docker command failed: docker $($DockerArgs -join ' ')" $code }
  return $code
}

function Invoke-Compose {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$ComposeArgs,
    [switch]$AllowFailure
  )
  $dockerArgs = @('compose', '--env-file', $EnvFile, '-f', $ComposeFile) + $ComposeArgs
  return Invoke-Docker -DockerArgs $dockerArgs -AllowFailure:$AllowFailure
}

function New-Secret([int]$bytes = 32) {
  $buffer = New-Object byte[] $bytes
  $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    $rng.Dispose()
  }
  return [Convert]::ToBase64String($buffer).TrimEnd('=').Replace('+', 'A').Replace('/', 'B')
}

function Read-EnvFile {
  $map = @{}
  if (-not (Test-Path -LiteralPath $EnvFile)) { return $map }
  foreach ($line in Get-Content -LiteralPath $EnvFile) {
    if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
    $parts = $line.Split('=', 2)
    $map[$parts[0]] = $parts[1]
  }
  return $map
}

function Write-EnvFile($values) {
  Ensure-Dir $RuntimeDir
  $lines = @(
    '# Generated by Business OS Docker release automation.',
    '# Do not commit this file. It contains runtime-only settings.',
    "BUSINESS_OS_IMAGE=$($values.BUSINESS_OS_IMAGE)",
    "BUSINESS_OS_PUBLIC_URL=$($values.BUSINESS_OS_PUBLIC_URL)",
    "BUSINESS_OS_ADMIN_URL=$($values.BUSINESS_OS_ADMIN_URL)",
    "POSTGRES_DB=$($values.POSTGRES_DB)",
    "POSTGRES_USER=$($values.POSTGRES_USER)",
    "POSTGRES_PASSWORD=$($values.POSTGRES_PASSWORD)",
    "MINIO_ROOT_USER=$($values.MINIO_ROOT_USER)",
    "MINIO_ROOT_PASSWORD=$($values.MINIO_ROOT_PASSWORD)",
    "S3_BUCKET=$($values.S3_BUCKET)",
    "CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE=$($values.CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE)",
    "BUSINESS_OS_LEGACY_ROOT=$($values.BUSINESS_OS_LEGACY_ROOT)",
    'APP_BIND_HOST=127.0.0.1',
    'APP_PORT=4000',
    'DATABASE_DRIVER=postgres',
    'OBJECT_STORAGE_DRIVER=minio',
    'JOB_QUEUE_DRIVER=bullmq',
    'BUSINESS_OS_RUNTIME=docker'
  )
  Set-Content -LiteralPath $EnvFile -Value $lines -Encoding ASCII
  Write-Ok "Docker release env ready: $EnvFile"
}

function Ensure-Env {
  Ensure-Dir $RuntimeDir
  Ensure-Dir $SecretDir
  Ensure-Dir $BackupDir
  Ensure-Dir $DockerConfig

  $existing = Read-EnvFile
  $tag = if ($Version) { $Version } else { if ($existing.BUSINESS_OS_IMAGE) { ($existing.BUSINESS_OS_IMAGE -split ':')[-1] } else { 'latest' } }
  $imageBase = if ($Image) { $Image } else { if ($existing.BUSINESS_OS_IMAGE) { ($existing.BUSINESS_OS_IMAGE -replace ':[^/:]+$', '') } else { $DefaultImage } }
  $tokenFile = if ($existing.CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE) { $existing.CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE } else { Join-Path $SecretDir 'cloudflare-tunnel.token' }

  if (-not (Test-Path -LiteralPath $tokenFile)) {
    New-Item -ItemType File -Force -Path $tokenFile | Out-Null
    Write-Warn "Cloudflare token file created empty: $tokenFile"
    Write-Warn 'Paste the tunnel token into that file before starting the public release runtime.'
  }

  $values = [ordered]@{
    BUSINESS_OS_IMAGE = "$imageBase`:$tag"
    BUSINESS_OS_PUBLIC_URL = if ($existing.BUSINESS_OS_PUBLIC_URL) { $existing.BUSINESS_OS_PUBLIC_URL } else { 'https://leangcosmetics.dpdns.org' }
    BUSINESS_OS_ADMIN_URL = if ($existing.BUSINESS_OS_ADMIN_URL) { $existing.BUSINESS_OS_ADMIN_URL } else { 'https://admin.leangcosmetics.dpdns.org' }
    POSTGRES_DB = if ($existing.POSTGRES_DB) { $existing.POSTGRES_DB } else { 'business_os' }
    POSTGRES_USER = if ($existing.POSTGRES_USER) { $existing.POSTGRES_USER } else { 'business_os' }
    POSTGRES_PASSWORD = if ($existing.POSTGRES_PASSWORD) { $existing.POSTGRES_PASSWORD } else { New-Secret 36 }
    MINIO_ROOT_USER = if ($existing.MINIO_ROOT_USER) { $existing.MINIO_ROOT_USER } else { 'businessos' }
    MINIO_ROOT_PASSWORD = if ($existing.MINIO_ROOT_PASSWORD) { $existing.MINIO_ROOT_PASSWORD } else { New-Secret 36 }
    S3_BUCKET = if ($existing.S3_BUCKET) { $existing.S3_BUCKET } else { 'business-os-assets' }
    CLOUDFLARE_TUNNEL_TOKEN_HOST_FILE = $tokenFile
    BUSINESS_OS_LEGACY_ROOT = if ($existing.BUSINESS_OS_LEGACY_ROOT) { $existing.BUSINESS_OS_LEGACY_ROOT } else { $Root }
  }
  Write-EnvFile $values
  return $values
}

function Ensure-DockerReady {
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  Write-Step 'Checking Docker engine readiness...'
  $result = Invoke-ProcessWithTimeout $docker @('info', '--format', '{{.ServerVersion}}') 20
  if ($result.TimedOut) {
    Fail 'Docker CLI did not answer within 20 seconds. Open Docker Desktop, wait until it says Running, then retry.'
  }
  if ($result.ExitCode -ne 0) {
    Fail 'Docker Desktop is not running. Open Docker Desktop, wait until it says Running, then retry.'
  }
  Write-Ok 'Docker engine is reachable.'
}

function Get-VersionTag {
  if ($Version) { return $Version }
  $pkg = Get-Content -Raw (Join-Path $Root 'backend\package.json') | ConvertFrom-Json
  return "v$($pkg.version)-$(Get-Date -Format 'yyyyMMddHHmm')"
}

function Test-ReleaseContents {
  $compose = Get-Content -Raw $ComposeFile
  if ($compose -match '\.\./\.\.:/app' -or $compose -match 'node_modules') {
    Fail 'Release Compose must not bind-mount source folders or node_modules.'
  }
  if ($compose -notmatch 'DATABASE_DRIVER:\s*postgres') {
    Fail 'Release Compose must force DATABASE_DRIVER=postgres.'
  }
  if ($compose -notmatch 'OBJECT_STORAGE_DRIVER:\s*minio') {
    Fail 'Release Compose must force OBJECT_STORAGE_DRIVER=minio.'
  }
}

function Invoke-Release {
  Ensure-DockerReady
  Test-ReleaseContents
  $tag = Get-VersionTag
  $imageName = if ($Image) { $Image } else { $DefaultImage }
  $fullImage = "$imageName`:$tag"
  Write-Step "Building Docker release image $fullImage"
  Invoke-Docker -DockerArgs @('build', '-f', $Dockerfile, '-t', $fullImage, '-t', "$imageName`:latest", $Root) | Out-Null
  Ensure-Env | Out-Null
  $envMap = Read-EnvFile
  $envMap.BUSINESS_OS_IMAGE = $fullImage
  Write-EnvFile $envMap
  Write-Ok "Release image built: $fullImage"
  Write-Warn 'This release is guarded to refuse SQLite runtime. Complete the route-level Postgres data-layer cutover before public production serving.'
}

function Invoke-Publish {
  Ensure-DockerReady
  $envMap = Ensure-Env
  Write-Step "Pushing $($envMap.BUSINESS_OS_IMAGE)"
  Invoke-Docker -DockerArgs @('push', $envMap.BUSINESS_OS_IMAGE)
  $latest = ($envMap.BUSINESS_OS_IMAGE -replace ':[^/:]+$', ':latest')
  Invoke-Docker -DockerArgs @('push', $latest) -AllowFailure
}

function Invoke-Install {
  Ensure-DockerReady
  Ensure-Env | Out-Null
  Write-Step 'Pulling release images...'
  Invoke-Compose -ComposeArgs @('pull')
  Write-Step 'Starting database, queues, and storage...'
  Invoke-Compose -ComposeArgs @('up', '-d', 'postgres', 'redis-queue', 'redis-cache', 'minio')
  Write-Ok 'Base Docker services are installed.'
}

function Invoke-Start {
  Ensure-DockerReady
  Ensure-Env | Out-Null
  Write-Step 'Running first-run migrator...'
  Invoke-Compose -ComposeArgs @('--profile', 'migrate', 'run', '--rm', 'migrator') -AllowFailure
  Write-Step 'Starting Business OS Docker release runtime...'
  Invoke-Compose -ComposeArgs @('up', '-d', '--remove-orphans')
  Write-Ok 'Docker release start requested.'
}

function Invoke-Backup {
  Ensure-DockerReady
  $envMap = Ensure-Env
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $target = Join-Path $BackupDir $stamp
  Ensure-Dir $target
  Write-Step "Backing up Postgres to $target"
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  & $docker compose --env-file $EnvFile -f $ComposeFile exec -T postgres pg_dump -U $envMap.POSTGRES_USER $envMap.POSTGRES_DB | Set-Content -LiteralPath (Join-Path $target 'postgres.sql') -Encoding UTF8
  if ($LASTEXITCODE -ne 0) { Fail 'Postgres backup failed.' }
  Invoke-Compose -ComposeArgs @('run', '--rm', '--entrypoint', 'sh', 'minio', '-lc', 'cd /data && tar -czf /tmp/minio-data.tgz .') -AllowFailure | Out-Null
  Write-Ok "Backup created: $target"
}

function Invoke-Update {
  Ensure-DockerReady
  $envMap = Ensure-Env
  $previousFile = Join-Path $RuntimeDir 'previous-image.txt'
  Set-Content -LiteralPath $previousFile -Value $envMap.BUSINESS_OS_IMAGE -Encoding ASCII
  Invoke-Backup
  Write-Step 'Pulling new release image...'
  Invoke-Compose -ComposeArgs @('pull')
  Write-Step 'Applying migration and restarting...'
  Invoke-Start
  $code = Invoke-Compose -ComposeArgs @('ps') -AllowFailure
  if ($code -ne 0) {
    $previous = Get-Content -Raw $previousFile
    Write-Warn "Update health failed. Rolling back to $previous"
    $envMap.BUSINESS_OS_IMAGE = $previous.Trim()
    Write-EnvFile $envMap
    Invoke-Compose -ComposeArgs @('up', '-d', '--remove-orphans')
    Fail 'Update rolled back because health checks failed.'
  }
  Write-Ok 'Update completed.'
}

function Invoke-Restore {
  if (-not $BackupPath) { Fail 'Set -BackupPath to a backup folder containing postgres.sql.' }
  $sql = Join-Path $BackupPath 'postgres.sql'
  if (-not (Test-Path -LiteralPath $sql)) { Fail "Backup does not contain postgres.sql: $BackupPath" }
  Ensure-DockerReady
  $envMap = Ensure-Env
  Write-Warn 'Restore will replace Postgres data in the running release database.'
  Invoke-Compose -ComposeArgs @('stop', 'app', 'import-worker', 'media-worker') -AllowFailure | Out-Null
  $docker = Resolve-Docker
  $env:DOCKER_CONFIG = $DockerConfig
  Get-Content -LiteralPath $sql | & $docker compose --env-file $EnvFile -f $ComposeFile exec -T postgres psql -U $envMap.POSTGRES_USER $envMap.POSTGRES_DB
  if ($LASTEXITCODE -ne 0) { Fail 'Postgres restore failed.' }
  Invoke-Compose -ComposeArgs @('up', '-d')
  Write-Ok 'Restore completed.'
}

function Invoke-Doctor {
  Ensure-Env | Out-Null
  Test-ReleaseContents
  Ensure-DockerReady
  Invoke-Docker -DockerArgs @('compose', '--env-file', $EnvFile, '-f', $ComposeFile, 'config', '--quiet') | Out-Null
  Invoke-Compose -ComposeArgs @('ps') -AllowFailure | Out-Null
  Write-Ok 'Docker release diagnostics completed.'
  Write-Warn 'Note: release app startup is intentionally guarded until the Postgres data layer is fully cut over.'
}

Set-Location $Root
switch ($Action) {
  'Release' { Invoke-Release }
  'Publish' { Invoke-Publish }
  'Install' { Invoke-Install }
  'Start' { Invoke-Start }
  'Update' { Invoke-Update }
  'Backup' { Invoke-Backup }
  'Restore' { Invoke-Restore }
  'Doctor' { Invoke-Doctor }
}
