--
-- PostgreSQL database dump
--

\restrict Gm8Rg3K4c1s807NNyNVsGA18i5cLqeGgsUlgB7O8ilE9VwayNQyG6yE1JPOlUh1

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: btree_gin; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA public;


--
-- Name: EXTENSION btree_gin; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION btree_gin IS 'support for indexing common datatypes in GIN';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: action_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.action_history (
    id bigint NOT NULL,
    scope text DEFAULT 'global'::text,
    entity text,
    entity_id text,
    label text NOT NULL,
    undo_label text,
    redo_label text,
    reversible bigint DEFAULT 1,
    status text DEFAULT 'undoable'::text,
    undo_payload text DEFAULT '{}'::text,
    redo_payload text DEFAULT '{}'::text,
    last_error text,
    created_by_id bigint,
    created_by_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: action_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.action_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.action_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_provider_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_provider_configs (
    id bigint NOT NULL,
    name text NOT NULL,
    provider text NOT NULL,
    provider_type text DEFAULT 'chat'::text,
    account_email text,
    project_name text,
    api_key_encrypted text NOT NULL,
    default_model text,
    supported_models_json text DEFAULT '[]'::text,
    endpoint_override text,
    notes text,
    enabled bigint DEFAULT 1,
    last_status text DEFAULT 'untested'::text,
    last_error text,
    last_checked_at text,
    created_by_id bigint,
    created_by_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    priority bigint DEFAULT 50,
    requests_per_minute bigint DEFAULT 10,
    max_input_chars bigint DEFAULT 1000,
    max_completion_tokens bigint DEFAULT 1200,
    timeout_ms bigint DEFAULT 15000,
    cooldown_seconds bigint DEFAULT 20
);


--
-- Name: ai_provider_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_provider_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_provider_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_response_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_response_logs (
    id bigint NOT NULL,
    surface text DEFAULT 'portal'::text,
    provider_config_id bigint,
    provider_name text,
    provider text,
    model text,
    actor_user_id bigint,
    actor_user_name text,
    actor_label text,
    prompt_text text,
    question_text text,
    profile_json text DEFAULT '{}'::text,
    candidate_products_json text DEFAULT '[]'::text,
    recommendations_json text DEFAULT '[]'::text,
    citations_json text DEFAULT '[]'::text,
    answer_text text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ai_response_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_response_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_response_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    user_id bigint,
    user_name text,
    action text,
    entity text,
    entity_id text,
    details text,
    table_name text,
    record_id text,
    old_value text,
    new_value text,
    device_name text,
    device_tz text,
    client_time text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: branch_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.branch_stock (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    quantity double precision DEFAULT 0,
    rfid_confirmed_qty double precision DEFAULT 0
);


--
-- Name: branch_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.branch_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branch_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: branches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.branches (
    id bigint NOT NULL,
    name text NOT NULL,
    location text,
    phone text,
    manager text,
    notes text,
    is_default bigint DEFAULT 0,
    is_active bigint DEFAULT 1,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text
);


--
-- Name: branches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_os_migration_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_os_migration_status (
    id bigint NOT NULL,
    source_hash text,
    status text NOT NULL,
    summary_json jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: business_os_migration_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_os_migration_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_os_migration_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name text NOT NULL,
    color text DEFAULT '#6366f1'::text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_fields; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_fields (
    id bigint NOT NULL,
    entity_type text NOT NULL,
    field_name text NOT NULL,
    field_type text DEFAULT 'text'::text NOT NULL,
    required bigint DEFAULT 0,
    default_value text,
    options text,
    sort_order bigint DEFAULT 0,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: custom_fields_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_fields ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_fields_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_tables; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_tables (
    id bigint NOT NULL,
    name text NOT NULL,
    columns text DEFAULT '[]'::text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text
);


--
-- Name: custom_tables_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_tables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_tables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_share_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_share_submissions (
    id bigint NOT NULL,
    customer_id bigint,
    membership_number text,
    customer_name text,
    platform text,
    note text,
    screenshots_json text DEFAULT '[]'::text,
    status text DEFAULT 'pending'::text,
    reward_points double precision DEFAULT 0,
    review_note text,
    reviewed_by_id bigint,
    reviewed_by_name text,
    reviewed_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: customer_share_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_share_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_share_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    name text NOT NULL,
    phone text,
    email text,
    address text,
    company text,
    notes text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    membership_number text,
    updated_at text
);


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery_contacts (
    id bigint NOT NULL,
    name text NOT NULL,
    phone text,
    area text,
    address text,
    notes text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text
);


--
-- Name: delivery_contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery_contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: file_assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_assets (
    id bigint NOT NULL,
    original_name text NOT NULL,
    stored_name text NOT NULL,
    public_path text NOT NULL,
    mime_type text,
    media_type text DEFAULT 'image'::text,
    byte_size bigint,
    width bigint,
    height bigint,
    source text DEFAULT 'upload'::text,
    created_by_id bigint,
    created_by_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    original_byte_size bigint,
    optimized_byte_size bigint,
    optimization_status text DEFAULT 'not_optimized'::text,
    optimization_note text,
    duration_seconds double precision
);


--
-- Name: file_assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.file_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: google_drive_sync_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.google_drive_sync_entries (
    id bigint NOT NULL,
    relative_path text NOT NULL,
    item_type text DEFAULT 'file'::text,
    remote_file_id text NOT NULL,
    mime_type text,
    md5_checksum text,
    byte_size bigint DEFAULT 0,
    local_modified_at text,
    last_synced_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: google_drive_sync_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.google_drive_sync_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.google_drive_sync_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_job_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_job_batches (
    id bigint NOT NULL,
    job_id text NOT NULL,
    batch_index bigint NOT NULL,
    start_row bigint DEFAULT 0,
    end_row bigint DEFAULT 0,
    status text DEFAULT 'pending'::text,
    attempts bigint DEFAULT 0,
    error_message text,
    started_at text,
    finished_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: import_job_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_job_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_job_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_job_errors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_job_errors (
    id bigint NOT NULL,
    job_id text NOT NULL,
    batch_id bigint,
    row_number bigint,
    file_name text,
    code text,
    message text NOT NULL,
    raw_json text DEFAULT '{}'::text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: import_job_errors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_job_errors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_job_errors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_job_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_job_files (
    id bigint NOT NULL,
    job_id text NOT NULL,
    kind text NOT NULL,
    original_name text,
    stored_path text NOT NULL,
    relative_path text,
    mime_type text,
    byte_size bigint DEFAULT 0,
    status text DEFAULT 'stored'::text,
    error_message text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: import_job_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_job_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_job_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_jobs (
    id text,
    type text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    phase text DEFAULT 'created'::text,
    queue_driver text DEFAULT 'bullmq'::text,
    total_rows bigint DEFAULT 0,
    processed_rows bigint DEFAULT 0,
    failed_rows bigint DEFAULT 0,
    total_images bigint DEFAULT 0,
    processed_images bigint DEFAULT 0,
    failed_images bigint DEFAULT 0,
    warning_count bigint DEFAULT 0,
    policy_json text DEFAULT '{}'::text,
    summary_json text DEFAULT '{}'::text,
    cancel_requested bigint DEFAULT 0,
    last_error text,
    created_by_id bigint,
    created_by_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    started_at text,
    finished_at text
);


--
-- Name: inventory_movements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_movements (
    id bigint NOT NULL,
    product_id bigint,
    product_name text,
    branch_id bigint,
    branch_name text,
    movement_type text,
    quantity double precision,
    unit_cost_usd double precision DEFAULT 0,
    unit_cost_khr double precision DEFAULT 0,
    total_cost_usd double precision DEFAULT 0,
    total_cost_khr double precision DEFAULT 0,
    reason text,
    reference_id bigint,
    user_id bigint,
    user_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: inventory_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_groups (
    id bigint NOT NULL,
    organization_id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    is_default bigint DEFAULT 0,
    is_active bigint DEFAULT 1,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: organization_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    public_id text NOT NULL,
    is_active bigint DEFAULT 1,
    setup_enabled bigint DEFAULT 0,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    image_path text NOT NULL,
    sort_order bigint DEFAULT 0,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rfid_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rfid_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epc_id text NOT NULL,
    tid text,
    product_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    status text DEFAULT 'active'::text,
    last_seen text,
    last_seen_session_id bigint,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_by bigint
);


--
-- Name: rfid_scan_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rfid_scan_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id bigint NOT NULL,
    area text,
    reader_id text,
    status text DEFAULT 'active'::text,
    ledger_qty double precision DEFAULT 0,
    confirmed_qty double precision DEFAULT 0,
    missing_count bigint DEFAULT 0,
    extra_count bigint DEFAULT 0,
    wrong_location_count bigint DEFAULT 0,
    unknown_count bigint DEFAULT 0,
    started_at text DEFAULT CURRENT_TIMESTAMP,
    finished_at text,
    applied_at text,
    created_by bigint,
    created_by_name text
);


--
-- Name: rfid_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rfid_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    epc_id text NOT NULL,
    tid text,
    product_id bigint,
    branch_id bigint,
    event_type text NOT NULL,
    antenna text,
    rssi double precision,
    seen_at text DEFAULT CURRENT_TIMESTAMP,
    raw_json text,
    dedupe_key text
);


--
-- Name: rfid_session_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rfid_session_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL,
    epc_id text NOT NULL,
    tid text,
    product_id bigint,
    expected_branch_id bigint,
    seen_branch_id bigint,
    status text NOT NULL,
    review_note text,
    first_seen text DEFAULT CURRENT_TIMESTAMP,
    last_seen text DEFAULT CURRENT_TIMESTAMP,
    read_count bigint DEFAULT 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    name text NOT NULL,
    sku text,
    barcode text,
    category text,
    unit text DEFAULT 'pcs'::text,
    description text,
    selling_price_usd double precision DEFAULT 0,
    selling_price_khr double precision DEFAULT 0,
    purchase_price_usd double precision DEFAULT 0,
    purchase_price_khr double precision DEFAULT 0,
    cost_price_usd double precision DEFAULT 0,
    cost_price_khr double precision DEFAULT 0,
    stock_quantity double precision DEFAULT 0,
    rfid_confirmed_qty double precision DEFAULT 0,
    low_stock_threshold double precision DEFAULT 10,
    out_of_stock_threshold double precision DEFAULT 0,
    image_path text,
    is_active bigint DEFAULT 1,
    supplier text,
    custom_fields text DEFAULT '{}'::text,
    parent_id bigint,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    brand text,
    client_request_id text,
    special_price_usd double precision DEFAULT 0,
    special_price_khr double precision DEFAULT 0,
    is_group bigint DEFAULT 0,
    discount_enabled bigint DEFAULT 0,
    discount_type text DEFAULT 'percent'::text,
    discount_percent double precision DEFAULT 0,
    discount_amount_usd double precision DEFAULT 0,
    discount_amount_khr double precision DEFAULT 0,
    discount_label text,
    discount_badge_color text DEFAULT '#e11d48'::text,
    discount_starts_at text,
    discount_ends_at text,
    expiry_date text,
    expiry_alert_days double precision DEFAULT 30
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_items (
    id bigint NOT NULL,
    return_id bigint NOT NULL,
    sale_item_id bigint,
    product_id bigint,
    product_name text,
    quantity double precision DEFAULT 1,
    applied_price_usd double precision DEFAULT 0,
    applied_price_khr double precision DEFAULT 0,
    cost_price_usd double precision DEFAULT 0,
    cost_price_khr double precision DEFAULT 0,
    total_usd double precision DEFAULT 0,
    total_khr double precision DEFAULT 0,
    return_to_stock bigint DEFAULT 1,
    branch_id bigint
);


--
-- Name: return_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: returns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.returns (
    id bigint NOT NULL,
    return_number text,
    sale_id bigint,
    receipt_number text,
    cashier_id bigint,
    cashier_name text,
    customer_name text,
    branch_id bigint,
    branch_name text,
    reason text,
    return_type text DEFAULT 'restock'::text,
    notes text,
    total_refund_usd double precision DEFAULT 0,
    total_refund_khr double precision DEFAULT 0,
    exchange_rate double precision DEFAULT 4100,
    status text DEFAULT 'completed'::text,
    device_name text,
    device_tz text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    customer_id bigint,
    return_scope text DEFAULT 'customer'::text,
    supplier_id bigint,
    supplier_name text,
    supplier_settlement text DEFAULT 'none'::text,
    supplier_compensation_usd double precision DEFAULT 0,
    supplier_compensation_khr double precision DEFAULT 0,
    supplier_loss_usd double precision DEFAULT 0,
    supplier_loss_khr double precision DEFAULT 0,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    client_request_id text
);


--
-- Name: returns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.returns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.returns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name text NOT NULL,
    permissions text DEFAULT '{}'::text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    code text,
    is_system bigint DEFAULT 0,
    updated_at text
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_items (
    id bigint NOT NULL,
    sale_id bigint NOT NULL,
    product_id bigint,
    product_name text,
    sku text,
    quantity double precision DEFAULT 1,
    unit text,
    applied_price_usd double precision DEFAULT 0,
    applied_price_khr double precision DEFAULT 0,
    cost_price_usd double precision DEFAULT 0,
    cost_price_khr double precision DEFAULT 0,
    total_usd double precision DEFAULT 0,
    total_khr double precision DEFAULT 0,
    branch_id bigint,
    price_mode text DEFAULT 'selling'::text,
    product_discount_type text,
    product_discount_label text,
    product_discount_usd double precision DEFAULT 0,
    product_discount_khr double precision DEFAULT 0
);


--
-- Name: sale_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    receipt_number text,
    cashier_id bigint,
    cashier_name text,
    branch_id bigint,
    branch_name text,
    customer_name text,
    customer_phone text,
    customer_address text,
    payment_method text DEFAULT 'Cash'::text,
    payment_currency text DEFAULT 'USD'::text,
    exchange_rate double precision DEFAULT 4100,
    subtotal_usd double precision DEFAULT 0,
    subtotal_khr double precision DEFAULT 0,
    discount_usd double precision DEFAULT 0,
    discount_khr double precision DEFAULT 0,
    tax_usd double precision DEFAULT 0,
    tax_khr double precision DEFAULT 0,
    total_usd double precision DEFAULT 0,
    total_khr double precision DEFAULT 0,
    amount_paid_usd double precision DEFAULT 0,
    amount_paid_khr double precision DEFAULT 0,
    change_usd double precision DEFAULT 0,
    change_khr double precision DEFAULT 0,
    is_delivery bigint DEFAULT 0,
    delivery_contact_id bigint,
    delivery_contact_name text,
    delivery_contact_phone text,
    delivery_contact_address text,
    delivery_fee_usd double precision DEFAULT 0,
    delivery_fee_khr double precision DEFAULT 0,
    delivery_fee_paid_by text DEFAULT 'customer'::text,
    sale_status text DEFAULT 'completed'::text,
    notes text,
    items text DEFAULT '[]'::text,
    device_name text,
    device_tz text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    customer_id bigint,
    membership_discount_usd double precision DEFAULT 0,
    membership_discount_khr double precision DEFAULT 0,
    membership_points_redeemed double precision DEFAULT 0,
    updated_at text,
    client_request_id text
);


--
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key text,
    value text,
    updated_at text
);


--
-- Name: stock_row_moves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_row_moves (
    id bigint NOT NULL,
    source_product_id bigint NOT NULL,
    source_product_name text,
    destination_product_id bigint NOT NULL,
    destination_product_name text,
    branch_id bigint,
    branch_name text,
    quantity double precision NOT NULL,
    reason text,
    note text,
    user_id bigint,
    user_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: stock_row_moves_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_row_moves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_row_moves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_transfers (
    id bigint NOT NULL,
    from_branch_id bigint,
    to_branch_id bigint,
    product_id bigint,
    product_name text,
    quantity double precision,
    notes text,
    user_id bigint,
    user_name text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: stock_transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    name text NOT NULL,
    phone text,
    email text,
    address text,
    company text,
    contact_person text,
    notes text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text
);


--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.units (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    color text DEFAULT '#6366f1'::text,
    updated_at text
);


--
-- Name: units_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash text NOT NULL,
    device_name text,
    device_tz text,
    client_time text,
    user_agent text,
    last_ip text,
    last_seen_at text DEFAULT CURRENT_TIMESTAMP,
    expires_at text NOT NULL,
    revoked_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: user_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username text NOT NULL,
    name text NOT NULL,
    password text NOT NULL,
    role_id bigint,
    permissions text DEFAULT '{}'::text,
    otp_enabled bigint DEFAULT 0,
    otp_secret text,
    is_active bigint DEFAULT 1,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    phone text,
    email text,
    avatar_path text,
    phone_verified bigint DEFAULT 0,
    email_verified bigint DEFAULT 0,
    supabase_user_id text,
    deleted_at text,
    firebase_user_id text,
    otp_pending_secret text,
    otp_pending_created_at text,
    phone_lookup text,
    organization_id bigint,
    organization_group_id bigint,
    updated_at text
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_codes (
    id bigint NOT NULL,
    user_id bigint,
    purpose text NOT NULL,
    channel text NOT NULL,
    destination text NOT NULL,
    code_hash text NOT NULL,
    code_salt text NOT NULL,
    meta_json text DEFAULT '{}'::text,
    expires_at text NOT NULL,
    consumed_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: verification_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: action_history action_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_history
    ADD CONSTRAINT action_history_pkey PRIMARY KEY (id);


--
-- Name: ai_provider_configs ai_provider_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_provider_configs
    ADD CONSTRAINT ai_provider_configs_pkey PRIMARY KEY (id);


--
-- Name: ai_response_logs ai_response_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_response_logs
    ADD CONSTRAINT ai_response_logs_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: branch_stock branch_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branch_stock
    ADD CONSTRAINT branch_stock_pkey PRIMARY KEY (id);


--
-- Name: branches branches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (id);


--
-- Name: business_os_migration_status business_os_migration_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_os_migration_status
    ADD CONSTRAINT business_os_migration_status_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: custom_fields custom_fields_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_fields
    ADD CONSTRAINT custom_fields_pkey PRIMARY KEY (id);


--
-- Name: custom_tables custom_tables_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_tables
    ADD CONSTRAINT custom_tables_pkey PRIMARY KEY (id);


--
-- Name: customer_share_submissions customer_share_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_share_submissions
    ADD CONSTRAINT customer_share_submissions_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: delivery_contacts delivery_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_contacts
    ADD CONSTRAINT delivery_contacts_pkey PRIMARY KEY (id);


--
-- Name: file_assets file_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_assets
    ADD CONSTRAINT file_assets_pkey PRIMARY KEY (id);


--
-- Name: google_drive_sync_entries google_drive_sync_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.google_drive_sync_entries
    ADD CONSTRAINT google_drive_sync_entries_pkey PRIMARY KEY (id);


--
-- Name: import_job_batches import_job_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_job_batches
    ADD CONSTRAINT import_job_batches_pkey PRIMARY KEY (id);


--
-- Name: import_job_errors import_job_errors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_job_errors
    ADD CONSTRAINT import_job_errors_pkey PRIMARY KEY (id);


--
-- Name: import_job_files import_job_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_job_files
    ADD CONSTRAINT import_job_files_pkey PRIMARY KEY (id);


--
-- Name: inventory_movements inventory_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movements
    ADD CONSTRAINT inventory_movements_pkey PRIMARY KEY (id);


--
-- Name: organization_groups organization_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_groups
    ADD CONSTRAINT organization_groups_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: return_items return_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_items
    ADD CONSTRAINT return_items_pkey PRIMARY KEY (id);


--
-- Name: returns returns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.returns
    ADD CONSTRAINT returns_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sale_items sale_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- Name: stock_row_moves stock_row_moves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_row_moves
    ADD CONSTRAINT stock_row_moves_pkey PRIMARY KEY (id);


--
-- Name: stock_transfers stock_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT stock_transfers_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: verification_codes verification_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT verification_codes_pkey PRIMARY KEY (id);


--
-- Name: idx_action_history_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_action_history_created_pg ON public.action_history USING btree (created_at DESC, id DESC);


--
-- Name: idx_branch_stock_product_branch_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_branch_stock_product_branch_unique ON public.branch_stock USING btree (product_id, branch_id);


--
-- Name: idx_branch_stock_branch_qty_product_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_branch_stock_branch_qty_product_pg ON public.branch_stock USING btree (branch_id, quantity DESC, product_id);


--
-- Name: idx_customer_share_submissions_status_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customer_share_submissions_status_created_pg ON public.customer_share_submissions USING btree (status, created_at DESC, id DESC);


--
-- Name: idx_customers_membership_lower_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customers_membership_lower_pg ON public.customers USING btree (lower(membership_number));


--
-- Name: idx_file_assets_public_path_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_file_assets_public_path_unique ON public.file_assets USING btree (public_path);


--
-- Name: idx_google_drive_sync_entries_path_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_google_drive_sync_entries_path_unique ON public.google_drive_sync_entries USING btree (relative_path);


--
-- Name: idx_import_job_batches_job_batch_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_import_job_batches_job_batch_unique ON public.import_job_batches USING btree (job_id, batch_index);


--
-- Name: idx_inventory_movements_branch_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_movements_branch_created_pg ON public.inventory_movements USING btree (branch_id, created_at DESC, id DESC);


--
-- Name: idx_inventory_movements_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_movements_created_pg ON public.inventory_movements USING btree (created_at DESC, id DESC);


--
-- Name: idx_inventory_movements_product_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_movements_product_created_pg ON public.inventory_movements USING btree (product_id, created_at DESC, id DESC);


--
-- Name: idx_inventory_movements_user_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_movements_user_created_pg ON public.inventory_movements USING btree (user_id, created_at DESC, id DESC);


--
-- Name: idx_products_active_stock_name_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_active_stock_name_pg ON public.products USING btree (is_active, stock_quantity, name);


--
-- Name: idx_products_barcode_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_barcode_pg ON public.products USING btree (barcode);


--
-- Name: idx_products_brand_lower_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_brand_lower_pg ON public.products USING btree (lower(brand));


--
-- Name: idx_products_category_lower_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_category_lower_pg ON public.products USING btree (lower(category));


--
-- Name: idx_products_name_lower_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_name_lower_pg ON public.products USING btree (lower(name));


--
-- Name: idx_products_parent_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_parent_pg ON public.products USING btree (parent_id, is_group);


--
-- Name: idx_products_sku_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_sku_pg ON public.products USING btree (sku);


--
-- Name: idx_products_supplier_lower_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_supplier_lower_pg ON public.products USING btree (lower(supplier));


--
-- Name: idx_returns_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_returns_created_pg ON public.returns USING btree (created_at DESC, id DESC);


--
-- Name: idx_returns_status_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_returns_status_created_pg ON public.returns USING btree (status, created_at DESC, id DESC);


--
-- Name: idx_sale_items_product_branch_sale_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sale_items_product_branch_sale_pg ON public.sale_items USING btree (product_id, branch_id, sale_id);


--
-- Name: idx_sales_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_created_pg ON public.sales USING btree (created_at DESC, id DESC);


--
-- Name: idx_sales_status_created_pg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_status_created_pg ON public.sales USING btree (sale_status, created_at DESC, id DESC);


--
-- Name: idx_settings_key_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_settings_key_unique ON public.settings USING btree (key);


--
-- PostgreSQL database dump complete
--

\unrestrict Gm8Rg3K4c1s807NNyNVsGA18i5cLqeGgsUlgB7O8ilE9VwayNQyG6yE1JPOlUh1


