-- d1-table-rows: exact row count of every base table (FTS virtual tables and
-- their shadow tables are left out; their bytes are in d1-dbstat-probe).
-- cloudflare/scripts/test-storage-queries-native.cjs applies every migration
-- to an in-memory node:sqlite database and asserts this list equals the base
-- tables the migrations create, so a new table fails the gate until it is
-- added here (production's d1_migrations and _cf_* tables are not listed).
-- json_object groups of at most 16 tables keep each call within D1's limit of
-- 32 arguments per SQL function; one row of scalar sub-queries, no UNION (D1
-- compound limit). COUNT(*) scans every row once: rows_read in the encrypted
-- meta equals the total, so run it once, not on a schedule.
-- ops:min-rows 1
-- ops:max-rows 1
SELECT
  json_object(
    'action_history', (SELECT COUNT(*) FROM action_history),
    'ai_provider_configs', (SELECT COUNT(*) FROM ai_provider_configs),
    'ai_response_logs', (SELECT COUNT(*) FROM ai_response_logs),
    'audit_logs', (SELECT COUNT(*) FROM audit_logs),
    'branch_batch_stock', (SELECT COUNT(*) FROM branch_batch_stock),
    'branch_stock', (SELECT COUNT(*) FROM branch_stock),
    'branches', (SELECT COUNT(*) FROM branches),
    'bulk_delete_jobs', (SELECT COUNT(*) FROM bulk_delete_jobs),
    'business_os_migration_status', (SELECT COUNT(*) FROM business_os_migration_status),
    'cache_versions', (SELECT COUNT(*) FROM cache_versions),
    'catalog_cost_recompute_0175', (SELECT COUNT(*) FROM catalog_cost_recompute_0175),
    'catalog_cost_repair_0195_backup', (SELECT COUNT(*) FROM catalog_cost_repair_0195_backup),
    'categories', (SELECT COUNT(*) FROM categories),
    'contact_duplicate_dismissals', (SELECT COUNT(*) FROM contact_duplicate_dismissals),
    'custom_fields', (SELECT COUNT(*) FROM custom_fields),
    'custom_tables', (SELECT COUNT(*) FROM custom_tables)
  ) AS rows_1,
  json_object(
    'customer_membership_number_repair', (SELECT COUNT(*) FROM customer_membership_number_repair),
    'customer_merge_map_0166', (SELECT COUNT(*) FROM customer_merge_map_0166),
    'customer_receivables', (SELECT COUNT(*) FROM customer_receivables),
    'customer_receivables_paid_multiple_repair', (SELECT COUNT(*) FROM customer_receivables_paid_multiple_repair),
    'customer_share_submissions', (SELECT COUNT(*) FROM customer_share_submissions),
    'customers', (SELECT COUNT(*) FROM customers),
    'damaged_stock_lots', (SELECT COUNT(*) FROM damaged_stock_lots),
    'dated_stock_count_batch_actions', (SELECT COUNT(*) FROM dated_stock_count_batch_actions),
    'delivery_contacts', (SELECT COUNT(*) FROM delivery_contacts),
    'fee_operation_receipts', (SELECT COUNT(*) FROM fee_operation_receipts),
    'fees', (SELECT COUNT(*) FROM fees),
    'file_assets', (SELECT COUNT(*) FROM file_assets),
    'google_drive_sync_entries', (SELECT COUNT(*) FROM google_drive_sync_entries),
    'image_audit', (SELECT COUNT(*) FROM image_audit),
    'image_audit_state', (SELECT COUNT(*) FROM image_audit_state),
    'import_auto_merges', (SELECT COUNT(*) FROM import_auto_merges)
  ) AS rows_2,
  json_object(
    'import_job_batches', (SELECT COUNT(*) FROM import_job_batches),
    'import_job_errors', (SELECT COUNT(*) FROM import_job_errors),
    'import_job_files', (SELECT COUNT(*) FROM import_job_files),
    'import_job_image_matches', (SELECT COUNT(*) FROM import_job_image_matches),
    'import_job_image_renames', (SELECT COUNT(*) FROM import_job_image_renames),
    'import_job_row_signatures', (SELECT COUNT(*) FROM import_job_row_signatures),
    'import_job_rows', (SELECT COUNT(*) FROM import_job_rows),
    'import_job_source_rows', (SELECT COUNT(*) FROM import_job_source_rows),
    'import_jobs', (SELECT COUNT(*) FROM import_jobs),
    'import_sales_commits', (SELECT COUNT(*) FROM import_sales_commits),
    'import_stock_action_commits', (SELECT COUNT(*) FROM import_stock_action_commits),
    'import_stock_action_groups', (SELECT COUNT(*) FROM import_stock_action_groups),
    'import_stock_action_guards', (SELECT COUNT(*) FROM import_stock_action_guards),
    'inventory_movements', (SELECT COUNT(*) FROM inventory_movements),
    'legacy_deleted_sale_items', (SELECT COUNT(*) FROM legacy_deleted_sale_items),
    'legacy_inventory_effects', (SELECT COUNT(*) FROM legacy_inventory_effects)
  ) AS rows_3,
  json_object(
    'legacy_sale_date_corrections', (SELECT COUNT(*) FROM legacy_sale_date_corrections),
    'legacy_sale_item_corrections', (SELECT COUNT(*) FROM legacy_sale_item_corrections),
    'login_lockouts', (SELECT COUNT(*) FROM login_lockouts),
    'loyalty_point_adjustments', (SELECT COUNT(*) FROM loyalty_point_adjustments),
    'loyalty_points_reset_log', (SELECT COUNT(*) FROM loyalty_points_reset_log),
    'organization_groups', (SELECT COUNT(*) FROM organization_groups),
    'organizations', (SELECT COUNT(*) FROM organizations),
    'password_reset_requests', (SELECT COUNT(*) FROM password_reset_requests),
    'pending_actions', (SELECT COUNT(*) FROM pending_actions),
    'portal_accounts', (SELECT COUNT(*) FROM portal_accounts),
    'portal_auth_lockouts', (SELECT COUNT(*) FROM portal_auth_lockouts),
    'portal_password_resets', (SELECT COUNT(*) FROM portal_password_resets),
    'portal_sessions', (SELECT COUNT(*) FROM portal_sessions),
    'product_batches', (SELECT COUNT(*) FROM product_batches),
    'product_conflict_action_group_members', (SELECT COUNT(*) FROM product_conflict_action_group_members),
    'product_conflict_action_groups', (SELECT COUNT(*) FROM product_conflict_action_groups)
  ) AS rows_4,
  json_object(
    'product_conflict_action_reviews', (SELECT COUNT(*) FROM product_conflict_action_reviews),
    'product_conflict_merge_run_cases', (SELECT COUNT(*) FROM product_conflict_merge_run_cases),
    'product_conflict_merge_runs', (SELECT COUNT(*) FROM product_conflict_merge_runs),
    'product_cost_entries', (SELECT COUNT(*) FROM product_cost_entries),
    'product_duplicate_dismissals', (SELECT COUNT(*) FROM product_duplicate_dismissals),
    'product_images', (SELECT COUNT(*) FROM product_images),
    'product_merge_map_0165', (SELECT COUNT(*) FROM product_merge_map_0165),
    'product_merge_map_0168', (SELECT COUNT(*) FROM product_merge_map_0168),
    'product_merge_map_0174', (SELECT COUNT(*) FROM product_merge_map_0174),
    'product_merge_pairs_0168', (SELECT COUNT(*) FROM product_merge_pairs_0168),
    'product_merge_pairs_0174', (SELECT COUNT(*) FROM product_merge_pairs_0174),
    'product_remove_operations', (SELECT COUNT(*) FROM product_remove_operations),
    'products', (SELECT COUNT(*) FROM products),
    'promotion_rules', (SELECT COUNT(*) FROM promotion_rules),
    'promotions', (SELECT COUNT(*) FROM promotions),
    'quota_usage', (SELECT COUNT(*) FROM quota_usage)
  ) AS rows_5,
  json_object(
    'rate_limit_events', (SELECT COUNT(*) FROM rate_limit_events),
    'return_bulk_guards', (SELECT COUNT(*) FROM return_bulk_guards),
    'return_bulk_members', (SELECT COUNT(*) FROM return_bulk_members),
    'return_bulk_operations', (SELECT COUNT(*) FROM return_bulk_operations),
    'return_create_guards', (SELECT COUNT(*) FROM return_create_guards),
    'return_create_receipts', (SELECT COUNT(*) FROM return_create_receipts),
    'return_item_batch_allocations', (SELECT COUNT(*) FROM return_item_batch_allocations),
    'return_items', (SELECT COUNT(*) FROM return_items),
    'return_mutation_receipts', (SELECT COUNT(*) FROM return_mutation_receipts),
    'return_replacement_items', (SELECT COUNT(*) FROM return_replacement_items),
    'return_write_revisions', (SELECT COUNT(*) FROM return_write_revisions),
    'returns', (SELECT COUNT(*) FROM returns),
    'rfid_events', (SELECT COUNT(*) FROM rfid_events),
    'rfid_scan_sessions', (SELECT COUNT(*) FROM rfid_scan_sessions),
    'rfid_session_items', (SELECT COUNT(*) FROM rfid_session_items),
    'rfid_tags', (SELECT COUNT(*) FROM rfid_tags)
  ) AS rows_6,
  json_object(
    'roles', (SELECT COUNT(*) FROM roles),
    'sale_amendments', (SELECT COUNT(*) FROM sale_amendments),
    'sale_bulk_guards', (SELECT COUNT(*) FROM sale_bulk_guards),
    'sale_bulk_members', (SELECT COUNT(*) FROM sale_bulk_members),
    'sale_bulk_operations', (SELECT COUNT(*) FROM sale_bulk_operations),
    'sale_incident_recovery_guards', (SELECT COUNT(*) FROM sale_incident_recovery_guards),
    'sale_incident_recovery_members', (SELECT COUNT(*) FROM sale_incident_recovery_members),
    'sale_incident_recovery_receipts', (SELECT COUNT(*) FROM sale_incident_recovery_receipts),
    'sale_item_batch_allocations', (SELECT COUNT(*) FROM sale_item_batch_allocations),
    'sale_items', (SELECT COUNT(*) FROM sale_items),
    'sale_mutation_guards', (SELECT COUNT(*) FROM sale_mutation_guards),
    'sale_mutation_members', (SELECT COUNT(*) FROM sale_mutation_members),
    'sale_mutation_receipts', (SELECT COUNT(*) FROM sale_mutation_receipts),
    'sale_not_paid_repair_0173', (SELECT COUNT(*) FROM sale_not_paid_repair_0173),
    'sale_not_paid_stock_recovery_guards', (SELECT COUNT(*) FROM sale_not_paid_stock_recovery_guards),
    'sale_not_paid_stock_recovery_members', (SELECT COUNT(*) FROM sale_not_paid_stock_recovery_members)
  ) AS rows_7,
  json_object(
    'sale_not_paid_stock_recovery_receipts', (SELECT COUNT(*) FROM sale_not_paid_stock_recovery_receipts),
    'sale_record_events', (SELECT COUNT(*) FROM sale_record_events),
    'sale_write_revisions', (SELECT COUNT(*) FROM sale_write_revisions),
    'sales', (SELECT COUNT(*) FROM sales),
    'settings', (SELECT COUNT(*) FROM settings),
    'shift_session_amendments', (SELECT COUNT(*) FROM shift_session_amendments),
    'shift_sessions', (SELECT COUNT(*) FROM shift_sessions),
    'stock_lot_adjustment_operations', (SELECT COUNT(*) FROM stock_lot_adjustment_operations),
    'stock_mutation_receipts', (SELECT COUNT(*) FROM stock_mutation_receipts),
    'stock_row_moves', (SELECT COUNT(*) FROM stock_row_moves),
    'stock_session_guards', (SELECT COUNT(*) FROM stock_session_guards),
    'stock_session_members', (SELECT COUNT(*) FROM stock_session_members),
    'stock_session_operations', (SELECT COUNT(*) FROM stock_session_operations),
    'stock_session_revisions', (SELECT COUNT(*) FROM stock_session_revisions),
    'stock_transfers', (SELECT COUNT(*) FROM stock_transfers),
    'supplier_invoices', (SELECT COUNT(*) FROM supplier_invoices)
  ) AS rows_8,
  json_object(
    'branch_cutovers', (SELECT COUNT(*) FROM branch_cutovers),
    'stock_alert_events', (SELECT COUNT(*) FROM stock_alert_events),
    'suppliers', (SELECT COUNT(*) FROM suppliers),
    'system_flags', (SELECT COUNT(*) FROM system_flags),
    'telegram_scheduled_sends', (SELECT COUNT(*) FROM telegram_scheduled_sends),
    'transfer_operation_members', (SELECT COUNT(*) FROM transfer_operation_members),
    'transfer_operation_receipts', (SELECT COUNT(*) FROM transfer_operation_receipts),
    'trusted_devices', (SELECT COUNT(*) FROM trusted_devices),
    'undo_snapshots', (SELECT COUNT(*) FROM undo_snapshots),
    'units', (SELECT COUNT(*) FROM units),
    'user_aliases', (SELECT COUNT(*) FROM user_aliases),
    'user_notes', (SELECT COUNT(*) FROM user_notes),
    'user_sessions', (SELECT COUNT(*) FROM user_sessions),
    'users', (SELECT COUNT(*) FROM users),
    'verification_codes', (SELECT COUNT(*) FROM verification_codes)
  ) AS rows_9;
