import assert from 'node:assert/strict'
import fs from 'node:fs'

await (async function backupJobApiShouldExposeQueuedFlows() {
  const source = fs.readFileSync(new URL('../src/api/methods.js', import.meta.url), 'utf8')
  assert.match(source, /export\s+async\s+function\s+queueBackupFolderExport/)
  assert.match(source, /export\s+async\s+function\s+queueBackupFolderRestore/)
  assert.match(source, /export\s+const\s+queueGoogleDriveSyncNow/)
  console.log('PASS backup API exposes queued job flows')
})()

await (async function backupUiShouldPollJobsInsteadOfWaitingSilently() {
  const source = fs.readFileSync(new URL('../src/components/utils-settings/Backup.jsx', import.meta.url), 'utf8')
  assert.match(source, /JobProgressCard/)
  assert.match(source, /startJobWatcher/)
  assert.match(source, /getSystemJob/)
  assert.match(source, /queueGoogleDriveSyncNow/)
  assert.match(source, /queueBackupFolderExport/)
  assert.match(source, /queueBackupFolderRestore/)
  assert.match(source, /backup_default_path_note/)
  assert.match(source, /advancedMaintenanceOpen/)
  assert.match(source, /setPendingAuthUrl\(authUrl\)/)
  assert.match(source, /DRIVE_SYNC_DEFAULT_INTERVAL_MINUTES\s*=\s*60/)
  assert.match(source, /DRIVE_SYNC_PRESET_HOURS\s*=\s*\[3,\s*6,\s*9,\s*12,\s*24\]/)
  assert.match(source, /drive_sync_interval_minutes/)
  assert.match(source, /minutesToSyncSeconds\(form\.syncIntervalMinutes\)/)
  assert.doesNotMatch(source, /Sync every \(seconds\)/)
  assert.doesNotMatch(source, /window\.open\(authUrl/)
  assert.match(source, /<details[^>]+className=/)
  assert.doesNotMatch(source, /requiresHostAction/)
  assert.doesNotMatch(source, /host_action_required/)
  assert.doesNotMatch(source, /run host command/i)
  assert.doesNotMatch(source, /Download legacy JSON/i)
  assert.doesNotMatch(source, /await\s+window\.api\.exportBackupFolder/)
  assert.doesNotMatch(source, /await\s+window\.api\.importBackupFolder/)
  assert.doesNotMatch(source, /await\s+window\.api\.pollSystemJob/)
  console.log('PASS backup UI watches queued jobs with visible progress')
})()

await (async function finalBackupRemovesInlineJsonDownloadPath() {
  const source = fs.readFileSync(new URL('../src/api/methods.js', import.meta.url), 'utf8')
  assert.doesNotMatch(source, /export\s+async\s+function\s+exportBackup\(/)
  assert.doesNotMatch(source, /export\s+async\s+function\s+importBackup\(/)
  assert.doesNotMatch(source, /pickBackupFile/)
  assert.doesNotMatch(source, /\/api\/system\/backup\/import/)
  assert.match(source, /export\s+async\s+function\s+exportBackupFolder/)
  assert.match(source, /return\s+queueBackupFolderExport\(destinationDir\)/)
  assert.match(source, /export\s+async\s+function\s+importBackupFolder/)
  assert.match(source, /return\s+queueBackupFolderRestore\(sourceDir\)/)
  console.log('PASS final backup API removes inline JSON backup paths')
})()

await (async function notificationsShouldRenderThroughPortal() {
  const source = fs.readFileSync(new URL('../src/components/shared/NotificationCenter.jsx', import.meta.url), 'utf8')
  assert.match(source, /createPortal/)
  assert.match(source, /z-\[1000\]/)
  console.log('PASS notifications render above page controls')
})()
