import assert from 'node:assert/strict'
import fs from 'node:fs'

await (async function backupJobApiShouldExposeQueuedFlows() {
  const source = fs.readFileSync(new URL('../src/api/methods.js', import.meta.url), 'utf8')
  assert.match(source, /export\s+async\s+function\s+queueBackupFolderExport/)
  assert.match(source, /export\s+async\s+function\s+queueBackupFolderRestore/)
  assert.match(source, /export\s+const\s+queueGoogleDriveSyncNow/)
  console.log('PASS backup API exposes queued job flows')
})()

await (async function backupUiShouldPollJobsInsteadOfWaitingSilently() {
  const source = fs.readFileSync(new URL('../src/components/utils-settings/Backup.jsx', import.meta.url), 'utf8')
  assert.match(source, /JobProgressCard/)
  assert.match(source, /startJobWatcher/)
  assert.match(source, /getSystemJob/)
  assert.match(source, /queueGoogleDriveSyncNow/)
  assert.match(source, /queueBackupFolderExport/)
  assert.match(source, /queueBackupFolderRestore/)
  assert.match(source, /backup_default_path_note/)
  assert.match(source, /advancedMaintenanceOpen/)
  assert.match(source, /setPendingAuthUrl\(authUrl\)/)
  assert.match(source, /DRIVE_SYNC_DEFAULT_INTERVAL_MINUTES\s*=\s*60/)
  assert.match(source, /DRIVE_SYNC_PRESET_HOURS\s*=\s*\[3,\s*6,\s*9,\s*12,\s*24\]/)
  assert.match(source, /DRIVE_SYNC_STATUS_TIMEOUT_MS\s*=\s*5000/)
  assert.match(source, /DRIVE_SYNC_JOB_POLL_MS\s*=\s*2000/)
  assert.match(source, /drive_sync_interval_minutes/)
  assert.match(source, /dirtyFieldsRef/)
  assert.match(source, /applyDriveIntervalPreset/)
  assert.match(source, /minutesToSyncSeconds\(form\.syncIntervalMinutes\)/)
  assert.match(source, /withLoaderTimeout\(\(\)\s*=>\s*window\.api\.getGoogleDriveSyncStatus\?\.\(\),\s*'Drive sync status',\s*DRIVE_SYNC_STATUS_TIMEOUT_MS\)/)
  assert.match(source, /window\.setTimeout\(tick/)
  assert.doesNotMatch(source, /window\.setInterval\(tick/)
  assert.doesNotMatch(source, /business-os:backup:section/)
  assert.doesNotMatch(source, /Sync every \(seconds\)/)
  assert.doesNotMatch(source, /window\.open\(authUrl/)
  assert.match(source, /<details[^>]+className=/)
  assert.doesNotMatch(source, /requiresHostAction/)
  assert.doesNotMatch(source, /host_action_required/)
  assert.doesNotMatch(source, /run host command/i)
  assert.doesNotMatch(source, /Download legacy JSON/i)
  assert.doesNotMatch(source, /await\s+window\.api\.exportBackupFolder/)
  assert.doesNotMatch(source, /await\s+window\.api\.importBackupFolder/)
  assert.doesNotMatch(source, /await\s+window\.api\.pollSystemJob/)
  console.log('PASS backup UI watches queued jobs with visible progress')
})()

await (async function finalBackupRemovesInlineJsonDownloadPath() {
  const source = fs.readFileSync(new URL('../src/api/methods.js', import.meta.url), 'utf8')
  assert.doesNotMatch(source, /export\s+async\s+function\s+exportBackup\(/)
  assert.doesNotMatch(source, /export\s+async\s+function\s+importBackup\(/)
  assert.doesNotMatch(source, /pickBackupFile/)
  assert.doesNotMatch(source, /\/api\/system\/backup\/import/)
  assert.match(source, /export\s+async\s+function\s+exportBackupFolder/)
  assert.match(source, /return\s+queueBackupFolderExport\(destinationDir\)/)
  assert.match(source, /export\s+async\s+function\s+importBackupFolder/)
  assert.match(source, /return\s+queueBackupFolderRestore\(sourceDir\)/)
  console.log('PASS final backup API removes inline JSON backup paths')
})()

await (async function notificationsShouldRenderThroughPortal() {
  const source = fs.readFileSync(new URL('../src/components/shared/NotificationCenter.jsx', import.meta.url), 'utf8')
  assert.match(source, /createPortal/)
  assert.match(source, /z-\[1000\]/)
  console.log('PASS notifications render above page controls')
})()

await (async function notificationsUseIconsAndKeepUnavailableAlerts() {
  const source = fs.readFileSync(new URL('../src/components/shared/NotificationCenter.jsx', import.meta.url), 'utf8')
  assert.match(source, /TONE_ICON_COMPONENT/)
  assert.match(source, /function\s+NotificationSeverityIcon/)
  assert.match(source, /data-notification-severity-icon/)
  assert.match(source, /title=\{label\}/)
  assert.match(source, /NOTIFICATION_FILTER_OPTIONS\.map[\s\S]*\{label\}[\s\S]*section\.items\.map/)
  assert.match(source, /section\.totalPages > 1/)
  assert.match(source, /setSectionPages/)
  assert.match(source, /notificationSearch/)
  assert.match(source, /search_notifications/)
  assert.match(source, /normalizedNotificationSearch/)
  assert.match(source, /haystack\.includes\(normalizedNotificationSearch\)/)
  assert.match(source, /result\?\.unavailable && !nextSections\.length/)
  const itemRows = source.slice(source.indexOf('{section.items.map'), source.indexOf('<ExternalLink', source.indexOf('{section.items.map')))
  assert.match(itemRows, /<NotificationSeverityIcon\s+tone=\{item\.tone\}\s+label=\{label\}/)
  assert.doesNotMatch(itemRows, />\s*\{label\}\s*</)
  assert.doesNotMatch(source, /TONE_LABEL_KEYS\[item\.tone\][\s\S]{0,120}\{TONE_LABEL_KEYS\[item\.tone\]/)
  console.log('PASS notifications use icon severity chips and preserve active alerts during unavailable refreshes')
})()

await (async function dashboardShouldExposeOutOfStockAsTopKpi() {
  const source = fs.readFileSync(new URL('../src/components/dashboard/Dashboard.jsx', import.meta.url), 'utf8')
  assert.match(source, /id:\s*'out-of-stock'/)
  assert.match(source, /value:\s*outOfStockCount/)
  assert.match(source, /label:\s*t\('out_of_stock'\)/)
  console.log('PASS dashboard exposes out-of-stock as a top KPI')
})()
