import assert from 'node:assert/strict'
import fs from 'node:fs'

await (async function backupJobApiShouldExposeQueuedFlows() {
  const source = fs.readFileSync(new URL('../src/api/methods.js', import.meta.url), 'utf8')
  assert.match(source, /export\s+async\s+function\s+queueBackupFolderExport/)
  assert.match(source, /export\s+async\s+function\s+queueBackupFolderRestore/)
  assert.match(source, /export\s+const\s+queueGoogleDriveSyncNow/)
  assert.match(source, /export\s+async\s+function\s+cancelSystemJob/)
  console.log('PASS backup API exposes queued job flows')
})()

await (async function backupUiShouldPollJobsInsteadOfWaitingSilently() {
  const source = fs.readFileSync(new URL('../src/components/utils-settings/Backup.tsx', import.meta.url), 'utf8')
  assert.match(source, /JobProgressCard/)
  assert.match(source, /startJobWatcher/)
  assert.match(source, /getSystemJob/)
  assert.match(source, /queueGoogleDriveSyncNow/)
  assert.match(source, /queueBackupFolderExport/)
  assert.match(source, /queueBackupFolderRestore/)
  assert.match(source, /backup-job-cancel/)
  assert.match(source, /backup-job-progress/)
  assert.match(source, /backup-doctor-refresh/)
  assert.match(source, /backup-doctor-deep/)
  assert.match(source, /backup-export-create/)
  assert.match(source, /backup-restore-start/)
  assert.match(source, /backup-drive-save/)
  assert.match(source, /backup-drive-connect/)
  assert.match(source, /backup-drive-sync-now/)
  assert.match(source, /backup-drive-disconnect/)
  assert.match(source, /backup-drive-forget/)
  assert.match(source, /data-testid=\{`backup-drive-preset-\$\{hours\}h`\}/)
  assert.match(source, /cancelActiveBackupJob/)
  assert.match(source, /cancelActiveJob/)
  assert.match(source, /backup_default_path_note/)
  assert.match(source, /advancedMaintenanceOpen/)
  assert.match(source, /setPendingAuthUrl\(authUrl\)/)
  assert.match(source, /DRIVE_SYNC_DEFAULT_INTERVAL_MINUTES\s*=\s*6\s*\*\s*60/)
  assert.match(source, /DRIVE_SYNC_PRESET_HOURS\s*=\s*\[3,\s*6,\s*9,\s*12,\s*24\]/)
  assert.match(source, /Default is 360 minutes \(every 6 hours\)/)
  assert.match(source, /DRIVE_SYNC_STATUS_TIMEOUT_MS\s*=\s*5000/)
  assert.match(source, /DRIVE_SYNC_JOB_POLL_MS\s*=\s*2000/)
  assert.match(source, /INTEGRATION_DOCTOR_TIMEOUT_MS\s*=\s*12000/)
  assert.match(source, /INTEGRATION_DOCTOR_DEEP_TIMEOUT_MS\s*=\s*30000/)
  assert.match(source, /SYSTEM_JOB_STATUS_TIMEOUT_MS\s*=\s*10000/)
  assert.match(source, /SYSTEM_JOB_CANCEL_TIMEOUT_MS\s*=\s*12000/)
  assert.match(source, /SYSTEM_JOB_STATUS_MAX_FAILURES\s*=\s*4/)
  assert.match(source, /DRIVE_SYNC_ACTION_TIMEOUT_MS\s*=\s*12000/)
  assert.match(source, /DRIVE_SYNC_OAUTH_TIMEOUT_MS\s*=\s*15000/)
  assert.match(source, /DRIVE_SYNC_QUEUE_TIMEOUT_MS\s*=\s*12000/)
  assert.match(source, /BACKUP_JOB_QUEUE_TIMEOUT_MS\s*=\s*15000/)
  assert.match(source, /drive_sync_interval_minutes/)
  assert.match(source, /dirtyFieldsRef/)
  assert.match(source, /applyDriveIntervalPreset/)
  assert.match(source, /minutesToSyncSeconds\(form\.syncIntervalMinutes\)/)
  assert.match(source, /withLoaderTimeout\(\(\)\s*=>\s*getBackupApi\(\)\.getGoogleDriveSyncStatus\?\.\(\),\s*'Drive sync status',\s*DRIVE_SYNC_STATUS_TIMEOUT_MS\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.getIntegrationDoctor\?\.\(\{ deep \}\),\s*deep \? 'Deep integration doctor' : 'Integration doctor',\s*deep \? INTEGRATION_DOCTOR_DEEP_TIMEOUT_MS : INTEGRATION_DOCTOR_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.getSystemJob\?\.\(jobId\),\s*`\$\{reason\} status`,\s*SYSTEM_JOB_STATUS_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.cancelSystemJob\?\.\(job\.id!,\s*'Cancelled from Backup page'\),\s*'Cancel backup job',\s*SYSTEM_JOB_CANCEL_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.saveGoogleDriveSyncPreferences\?\.\(\{/)
  assert.match(source, /'Save Google Drive sync preferences',\s*DRIVE_SYNC_ACTION_TIMEOUT_MS/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.startGoogleDriveSyncOauth\?\.\(\{/)
  assert.match(source, /'Start Google Drive connection',\s*DRIVE_SYNC_OAUTH_TIMEOUT_MS/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.queueGoogleDriveSyncNow\?\.\(\),\s*'Queue Google Drive sync',\s*DRIVE_SYNC_QUEUE_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.disconnectGoogleDriveSync\?\.\(\),\s*'Disconnect Google Drive sync',\s*DRIVE_SYNC_ACTION_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.forgetGoogleDriveSyncCredentials\?\.\(\{ confirm: true \}\),\s*'Forget Google Drive credentials',\s*DRIVE_SYNC_ACTION_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.queueBackupFolderExport\?\.\(exportDestination\),\s*'Queue backup export',\s*BACKUP_JOB_QUEUE_TIMEOUT_MS,\s*\)/)
  assert.match(source, /withLoaderTimeout\(\s*\(\) => getBackupApi\(\)\.queueBackupFolderRestore\?\.\(folderImportPath\),\s*'Queue backup restore',\s*BACKUP_JOB_QUEUE_TIMEOUT_MS,\s*\)/)
  assert.match(source, /consecutiveFailures >= SYSTEM_JOB_STATUS_MAX_FAILURES/)
  assert.match(source, /const failureDelay = consecutiveFailures > 0/)
  assert.match(source, /window\.setTimeout\(tick/)
  assert.doesNotMatch(source, /window\.setInterval\(tick/)
  assert.doesNotMatch(source, /business-os:backup:section/)
  assert.doesNotMatch(source, /Sync every \(seconds\)/)
  assert.doesNotMatch(source, /window\.open\(authUrl/)
  assert.match(source, /<details[^>]+className=/)
  assert.doesNotMatch(source, /requiresHostAction/)
  assert.doesNotMatch(source, /host_action_required/)
  assert.doesNotMatch(source, /run host command/i)
  assert.doesNotMatch(source, /Download legacy JSON/i)
  assert.doesNotMatch(source, /await\s+window\.api\.exportBackupFolder/)
  assert.doesNotMatch(source, /await\s+window\.api\.importBackupFolder/)
  assert.doesNotMatch(source, /await\s+window\.api\.pollSystemJob/)
  console.log('PASS backup UI watches queued jobs with visible progress')
})()

await (async function finalBackupRemovesInlineJsonDownloadPath() {
  const source = fs.readFileSync(new URL('../src/api/methods.js', import.meta.url), 'utf8')
  assert.doesNotMatch(source, /export\s+async\s+function\s+exportBackup\(/)
  assert.doesNotMatch(source, /export\s+async\s+function\s+importBackup\(/)
  assert.doesNotMatch(source, /pickBackupFile/)
  assert.doesNotMatch(source, /\/api\/system\/backup\/import/)
  assert.match(source, /export\s+async\s+function\s+exportBackupFolder/)
  assert.match(source, /return\s+queueBackupFolderExport\(destinationDir\)/)
  assert.match(source, /export\s+async\s+function\s+importBackupFolder/)
  assert.match(source, /return\s+queueBackupFolderRestore\(sourceDir\)/)
  console.log('PASS final backup API removes inline JSON backup paths')
})()

await (async function notificationsShouldRenderThroughPortal() {
  const source = fs.readFileSync(new URL('../src/components/shared/NotificationCenter.tsx', import.meta.url), 'utf8')
  assert.match(source, /createPortal/)
  assert.match(source, /z-\[1000\]/)
  console.log('PASS notifications render above page controls')
})()

await (async function notificationsUseIconsAndKeepUnavailableAlerts() {
  const source = fs.readFileSync(new URL('../src/components/shared/NotificationCenter.tsx', import.meta.url), 'utf8')
  assert.match(source, /TONE_ICON_COMPONENT/)
  assert.match(source, /function\s+NotificationSeverityIcon/)
  assert.match(source, /data-notification-severity-icon/)
  assert.match(source, /title=\{label\}/)
  assert.match(source, /NOTIFICATION_FILTER_OPTIONS\.map[\s\S]*\{label\}[\s\S]*section\.items\.map/)
  assert.match(source, /section\.totalPages > 1/)
  assert.match(source, /setSectionPages/)
  assert.match(source, /notificationSearch/)
  assert.match(source, /search_notifications/)
  assert.match(source, /normalizedNotificationSearch/)
  assert.match(source, /haystack\.includes\(normalizedNotificationSearch\)/)
  assert.match(source, /result\?\.unavailable && !nextSections\.length/)
  const itemRows = source.slice(source.indexOf('{section.items.map'), source.indexOf('<ExternalLink', source.indexOf('{section.items.map')))
  assert.match(itemRows, /const itemTone = item\.tone \|\| 'info'/)
  assert.match(itemRows, /<NotificationSeverityIcon\s+tone=\{itemTone\}\s+label=\{label\}/)
  assert.doesNotMatch(itemRows, />\s*\{label\}\s*</)
  assert.doesNotMatch(source, /TONE_LABEL_KEYS\[item\.tone\][\s\S]{0,120}\{TONE_LABEL_KEYS\[item\.tone\]/)
  console.log('PASS notifications use icon severity chips and preserve active alerts during unavailable refreshes')
})()

await (async function dashboardShouldKeepOutOfStockInsideProductTotalsKpi() {
  const source = fs.readFileSync(new URL('../src/components/dashboard/Dashboard.jsx', import.meta.url), 'utf8')
  assert.match(source, /id:\s*'products'/)
  assert.match(source, /lowStockCount/)
  assert.match(source, /outOfStockCount/)
  assert.doesNotMatch(source, /id:\s*'out-of-stock'/)
  console.log('PASS dashboard keeps stock alerts inside total products KPI')
})()
