import assert from 'node:assert/strict'
import fs from 'node:fs'
import http from 'node:http'
import path from 'node:path'
import { build } from 'esbuild'
import postcss from 'postcss'
import tailwindcss from 'tailwindcss'
import tailwindConfig from '../tailwind.config.ts'
import { chromium } from '@playwright/test'
const root=path.resolve(import.meta.dirname,'..')
const read=(name:string)=>fs.readFileSync(path.join(root,name),'utf8')
const packs=Object.fromEntries(['en','km'].map(lang=>[lang,JSON.parse(read(`src/lang/${lang}.json`))]))
const row={id:41,section:'products',action_type:'update',entity_type:'product',entity_id:7,payload_json:JSON.stringify({name:'Changed rice 25 kg',barcode:'RICE-NEW',unit:'Bag',notes:'Long content '.repeat(100)}),summary:null,status:'open',requested_by:2,requested_by_name:'Synthetic requester',created_at:'2026-10-09T00:00:00Z'}
const fixture=`import React from 'react';import{createRoot}from'react-dom/client';import Queue from './src/components/review/ReviewQueue.tsx';const q=new URLSearchParams(location.search);window.fixtureRows=[{...${JSON.stringify(row)},section:q.get('section')||'products',entity_type:q.get('entity')||'product',status:q.get('status')||'open',requested_by:q.get('self')==='1'?1:2}];window.nav=[];window.notices=[];createRoot(document.getElementById('root')).render(<Queue/>);`
const app=`const packs=${JSON.stringify(packs)};const q=new URLSearchParams(location.search);export const useApp=()=>({t:key=>packs[q.get('lang')||'en'][key]||key,notify:(...a)=>window.notices.push(a),getPermissionTier:key=>key==='review'?(q.get('review')||'full'):q.get('denied')==='1'?'none':'full',can:(key,action)=>q.get('denied')!=='1',hasPermission:key=>q.get('denied')!=='1'&&!(key==='contacts_suppliers'&&q.get('supplierDenied')==='1'),navigateTo:(...a)=>window.nav.push(a),user:{id:1}});export const useSync=()=>({});`
const transport=`export const getPendingActions=async({status,section})=>({data:window.fixtureRows.filter(row=>(status==='all'||row.status===status)&&(!section||row.section===section))});export const approvePendingAction=async id=>{window.fixtureRows[0].status='approved';return{success:true,data:window.fixtureRows[0]}};export const approveProductCreatePendingAction=approvePendingAction;export const reconcileProductCreatePendingAction=async()=>({data:window.fixtureRows[0]});export const rejectPendingAction=async()=>{};`
const mocks:Record<string,string>={'AppContext.tsx':app,'reviewQueueTransport.ts':transport,'actorReadScope.ts':'export const captureActorReadScope=()=>({});export const isActorReadScopeCurrent=()=>true;','http.ts':'export const cacheInvalidate=()=>{};','pageActivity':'export const useIsPageActive=()=>true;'}
const bundle=(await build({stdin:{contents:fixture,loader:'tsx',resolveDir:root},bundle:true,format:'iife',write:false,plugins:[{name:'boundary-fixture',setup(b){b.onResolve({filter:/AppContext\.tsx|reviewQueueTransport\.ts|actorReadScope\.ts|\/http\.ts|\/pageActivity$/},a=>({path:Object.keys(mocks).find(key=>a.path.endsWith(key))!,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:mocks[a.path],loader:'ts'}))}}]})).outputFiles[0].text
const css=(await postcss([tailwindcss({...tailwindConfig,content:[{raw:read('src/components/review/ReviewQueue.tsx')+read('src/components/utils-settings/AuditFieldDiffLine.tsx'),extension:'tsx'}]})]).process(read('src/styles/main.css'),{from:path.join(root,'src/styles/main.css')})).css
const server=http.createServer((req,res)=>{res.setHeader('cache-control','no-store');if(req.url==='/fixture.js'){res.setHeader('content-type','text/javascript');res.end(bundle)}else{res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="root"></div><script src="/fixture.js"></script></body></html>`)}})
await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const addr=server.address();assert(addr&&typeof addr!=='string')
const executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync)
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;let failed=0
async function check(name:string,run:()=>Promise<void>){try{await run();console.log('PASS '+name)}catch(error){failed++;console.error('FAIL '+name,error)}}
try{browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
for(const lang of ['en','km'])for(const width of [375,1280])for(const denied of [false,true]){const page=await browser.newPage({viewport:{width,height:812}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${addr.port}/?lang=${lang}&denied=${denied?1:0}`);await page.getByText('Synthetic requester',{exact:false}).waitFor();
await check(`mounted ${lang} ${width} denied=${denied}`,async()=>{
assert.equal(await page.locator('h1').count(),0,'host owns the title');assert.equal(await page.getByText(packs[lang].review_queue_hint,{exact:true}).count(),0);
const sections=page.getByRole('group',{name:packs[lang].sections,exact:true});const statuses=page.getByRole('group',{name:packs[lang].status,exact:true});assert.equal(await sections.count(),1);assert.equal(await statuses.count(),1);
assert.equal(await sections.getByRole('button').count(),7,'all six canonical possible sections even without rows');assert.equal(await statuses.getByRole('button').count(),4);
assert.equal(await page.getByText('Changed rice 25 kg',{exact:true}).count(),1,'readable returned content is visible without raw JSON toggle');assert.equal(await page.locator('a').count(),denied?0:1,'destination denial hides link');await page.getByRole('button',{name:packs[lang].view_details,exact:true}).click();assert.equal(await page.getByText('Long content '.repeat(100).trim(),{exact:true}).count(),1);assert.equal(await page.getByText('Cost price USD',{exact:true}).count(),0,'no richer fetch reconstructs projected cost');
if(!denied){const link=page.locator('a');await link.focus();await page.keyboard.press('Enter');assert.deepEqual(await page.evaluate(()=> (window as any).nav),[['products','hub:products:products']]);}
const geometry=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,rows:Array.from(document.querySelectorAll('[role=group]')).map(el=>({overflow:getComputedStyle(el).overflowX,wrap:getComputedStyle(el).flexWrap,ys:Array.from(el.querySelectorAll('button')).map(b=>Math.round(b.getBoundingClientRect().top))}))}));assert.equal(geometry.overflow,false);for(const r of geometry.rows){assert.equal(r.wrap,'nowrap');assert.equal(new Set(r.ys).size,1);assert.equal(r.overflow,'auto')}
await sections.getByRole('button',{name:packs[lang].branches,exact:true}).click();assert.equal(await sections.getByRole('button').first().innerText(),packs[lang].branches);await page.getByText(packs[lang].no_pending_actions,{exact:true}).waitFor();assert.equal(await sections.getByRole('button').count(),7);
await sections.getByRole('button',{name:packs[lang].all,exact:true}).click();await statuses.getByRole('button',{name:packs[lang].approved,exact:true}).click();assert.equal(await statuses.getByRole('button').first().innerText(),packs[lang].approved);await page.getByText(packs[lang].no_pending_actions,{exact:true}).waitFor();await statuses.getByRole('button',{name:packs[lang].all,exact:true}).click();assert.equal(await statuses.getByRole('button').first().innerText(),packs[lang].all);assert.deepEqual(errors,[]);
});await page.close()}

for(const [section,entity,pageId,tab] of [['products','product','products','products'],['inventory','inventory_reason','branches','products'],['branches','branch','branches','overview'],['fees','fee','sales','fees'],['returns','return','sales','returns'],['contacts','supplier','contacts','suppliers'],['contacts','delivery_contact','contacts','delivery'],['contacts','customer','contacts','customers']]){const page=await browser.newPage();await page.goto(`http://127.0.0.1:${addr.port}/?section=${section}&entity=${entity}`);await page.getByText('Synthetic requester',{exact:false}).waitFor();await check('canonical destination '+section+'/'+entity,async()=>{const link=page.locator('a');assert.equal(await link.count(),1);assert.ok((await link.getAttribute('href'))?.endsWith(`#hub:${pageId}:${tab}`));await link.click();assert.deepEqual(await page.evaluate(()=>(window as any).nav),[[pageId,`hub:${pageId}:${tab}`]])});await page.close()}
for(const query of ['section=contacts&entity=supplier&supplierDenied=1','section=settings&entity=setting','section=unsupported&entity=thing']){const page=await browser.newPage();await page.goto(`http://127.0.0.1:${addr.port}/?${query}`);await page.getByText('Synthetic requester',{exact:false}).waitFor();await check('no unsupported or denied link '+query,async()=>{assert.equal(await page.locator('a').count(),0)});await page.close()}
for(const status of ['approved','rejected']){const page=await browser.newPage();await page.goto(`http://127.0.0.1:${addr.port}/?status=${status}`);await page.getByRole('button',{name:packs.en.all,exact:true}).last().click();await page.getByText('Synthetic requester',{exact:false}).waitFor();await check('saved outcome '+status,async()=>{assert.equal(await page.getByText('Changed rice 25 kg',{exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:packs.en.approve,exact:true}).count(),0)});await page.close()}
{const page=await browser.newPage();await page.goto(`http://127.0.0.1:${addr.port}/?self=1`);await page.getByText('Synthetic requester',{exact:false}).waitFor();await check('self approval remains refused',async()=>{assert.equal(await page.getByRole('button',{name:packs.en.approve,exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:packs.en.reject,exact:true}).count(),1)});await page.close()}
for(const review of ['view','full']){const page=await browser.newPage();await page.goto(`http://127.0.0.1:${addr.port}/?review=${review}`);await page.getByText('Synthetic requester',{exact:false}).waitFor();await check('review action '+review,async()=>{assert.equal(await page.getByRole('button',{name:packs.en.approve,exact:true}).count(),review==='full'?1:0);if(review==='full'){await page.getByRole('button',{name:packs.en.approve,exact:true}).click();await page.getByText(packs.en.no_pending_actions,{exact:true}).waitFor();assert.equal((await page.evaluate(()=>(window as any).notices))[0][1],'success')}});await page.close()}
}finally{await browser?.close();await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()))}if(failed)process.exitCode=1


