import assert from 'node:assert/strict'
import fs from 'node:fs';import path from 'node:path';import http from 'node:http'
import {build}from'esbuild';import postcss from'postcss';import tailwindcss from'tailwindcss';import config from'../tailwind.config.ts';import{chromium}from'@playwright/test'
const root=path.resolve(import.meta.dirname,'..'),read=(f:string)=>fs.readFileSync(path.join(root,f),'utf8')
const packs=Object.fromEntries(['en','km'].map(lang=>[lang,JSON.parse(read(`src/lang/${lang}.json`))]))
const fixture=`import React from'react';import{createRoot}from'react-dom/client';import Deleted from'./src/components/review/LegacyDeletedSalesSection.tsx';import Audit from'./src/components/utils-settings/AuditLog.tsx';const q=new URLSearchParams(location.search);window.calls=[];createRoot(document.getElementById('root')).render(q.get('page')==='audit'?<Audit/>:<Deleted/>);`
const app=`const q=new URLSearchParams(location.search),packs=${JSON.stringify(packs)};export const FALLBACK_APP_CONTEXT={};export const isBrokenLocalizedString=()=>false;export const useApp=()=>({t:key=>packs[q.get('lang')||'en'][key]||key,language:q.get('lang')||'en',user:{id:1,username:'synthetic',role_code:'admin'},hasPermission:()=>true});`
const api=`export const getLegacyDeletedSales=async p=>{window.calls.push(p);return{items:Array.from({length:40},(_,i)=>({id:i+1,event_key:'fixture-'+i,source_product_name:'Synthetic product '+i,cashier_name:'Synthetic cashier',quantity:1,unit_price_usd:1,total_usd:1,deleted_at:'2026-10-09T00:00:00Z'})),total_lines:40,meta:{cashiers:[{key:'test',name:'ឈ្មោះបុគ្គលិកវែង '.repeat(8)}]}}};export const getAuditLogs=async p=>{window.calls.push(p);return{items:Array.from({length:70},(_,i)=>({id:i+1,action:'update',entity:'product',user_name:'Synthetic actor',created_at:'2026-10-09T00:00:00Z',details:JSON.stringify({name:'Synthetic product '+i})})),hasMore:false,counts:{users:[],sections:[]}}};`
const bundle=(await build({stdin:{contents:fixture,loader:'tsx',resolveDir:root},bundle:true,format:'iife',write:false,plugins:[{name:'seams',setup(b){b.onResolve({filter:/AppContext(?:Core)?\.tsx|auditLogTransport\.ts|\/pageActivity$/},a=>({path:a.path.includes('auditLogTransport')?'api':a.path.includes('pageActivity')?'activity':'app',namespace:'seam'}));b.onLoad({filter:/.*/,namespace:'seam'},a=>({contents:a.path==='api'?api:a.path==='activity'?'export const useIsPageActive=()=>true;':app,loader:'ts'}))}}]})).outputFiles[0].text
const sources=['review/LegacyDeletedSalesSection.tsx','utils-settings/AuditLog.tsx','shared/SearchInput.tsx','shared/AppSelect.tsx','shared/StatsRangeRow.tsx','shared/DateTimeRangePicker.tsx','shared/FilterMenu.tsx','shared/ExportMenu.tsx','shared/PaginationControls.tsx'].map(f=>read('src/components/'+f)).join('\n')
const css=(await postcss([tailwindcss({...config,content:[{raw:sources,extension:'tsx'}]})]).process(read('src/styles/main.css'),{from:path.join(root,'src/styles/main.css')})).css
const server=http.createServer((req,res)=>{if(req.url==='/fixture.js'){res.setHeader('content-type','text/javascript');res.end(bundle)}else{res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body class="lang-${new URL(req.url||'/','http://fixture').searchParams.get('lang')||'en'}"><div id="app-root" style="height:100dvh;display:flex;flex-direction:column"><header style="height:64px;flex-shrink:0">Review & Logs host</header><main style="min-height:0;display:flex;flex:1;flex-direction:column"><div id="root" style="min-height:0;display:flex;flex:1;flex-direction:column"></div></main></div><script src="/fixture.js"></script></body></html>`)}})
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const addr=server.address();assert(addr&&typeof addr!=='string');const executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;let failed=0
async function check(name:string,run:()=>Promise<void>){try{await run();console.log('PASS '+name)}catch(e){failed++;console.error('FAIL '+name,e)}}
try{browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});for(const section of ['deleted','audit'])for(const lang of ['en','km'])for(const width of [375,1280]){const page=await browser.newPage({viewport:{width,height:812}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${addr.port}/?page=${section}&lang=${lang}`);await page.getByText('Synthetic product 0',{exact:false}).first().waitFor();
await check(`page scrolling ${section} ${lang} ${width}`,async()=>{const geo=await page.locator('.page-scroll').evaluate(el=>({h:el.clientHeight,scroll:el.scrollHeight,nested:Array.from(el.querySelectorAll('*')).filter(n=>{const c=getComputedStyle(n);return ['auto','scroll'].includes(c.overflowY)&&n.scrollHeight>n.clientHeight+2}).map(n=>n.className),overflow:document.documentElement.scrollWidth>innerWidth}));assert.ok(geo.scroll>geo.h,JSON.stringify(geo));assert.deepEqual(geo.nested,[],JSON.stringify(geo));assert.equal(geo.overflow,false);await page.locator('.page-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await page.locator('.page-scroll').evaluate(el=>el.scrollTop>0));const last=await page.getByText(section==='audit'?'Synthetic product 69':'Synthetic product 39',{exact:false}).last().boundingBox();assert(last&&last.y>=64&&last.y+last.height<=812,'last record reachable by page scroll');assert.deepEqual(errors,[])});
await check(`toolbar/date clearing ${section} ${lang} ${width}`,async()=>{await page.locator('.page-scroll').evaluate(el=>el.scrollTop=0);const input=page.locator('input[type=text]').first();await input.fill('Synthetic');await page.getByRole('button',{name:packs[lang].clear_search,exact:true}).click();assert.equal(await input.inputValue(),'');assert.equal(await page.getByRole('button',{name:packs[lang].clear,exact:true}).count(),0,'no redundant outer Clear');if(section==='audit'){const a=await input.boundingBox(),b=await page.getByRole('button',{name:packs[lang].filters,exact:true}).boundingBox();assert(a&&b&&Math.abs(a.y-b.y)<5&&a.width>=120,'Audit options stay with readable search')}if(section==='deleted'){assert.equal(await page.getByText(packs[lang].legacy_deleted_sales_hint,{exact:true}).count(),0);const cashier=page.getByRole('button',{name:packs[lang].cashier,exact:true});const a=await input.boundingBox(),b=await cashier.boundingBox();assert(a&&b);assert.ok(Math.abs(a.y-b.y)<5,'cashier and search remain one row');assert.ok(a.width>=120&&b.width>=100);await cashier.focus();await page.keyboard.press('Enter');await page.getByRole('option').last().click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await cashier.click();await page.getByRole('option').first().click()}
if(section==='deleted')await page.locator('[data-date-presets] button').nth(1).click();else{await page.getByRole('button',{name:packs[lang].time,exact:true}).click();await page.getByRole('option').nth(1).click()}assert.equal(await page.getByRole('button',{name:packs[lang].clear,exact:true}).count(),0,'choosing preset must not add outer Clear');const trigger=page.getByRole('button',{name:packs[lang].date_time_range,exact:true});await trigger.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:packs[lang].date_time_range,exact:true});await dialog.waitFor();await dialog.getByRole('button',{name:packs[lang].clear,exact:true}).click();await dialog.getByRole('button',{name:packs[lang].close,exact:true}).click();assert.equal(await page.locator('[data-date-time-range-panel]').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[])});await page.close()}}finally{await browser?.close();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()))}if(failed)process.exitCode=1

