CREATE TABLE stock_valuation_sources(source_id TEXT PRIMARY KEY REFERENCES stock_funding_sources(id),opening_json TEXT NOT NULL CHECK(json_valid(opening_json)));
CREATE TABLE stock_valuation_events(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),revision INTEGER NOT NULL CHECK(revision>=0),kind TEXT NOT NULL CHECK(kind IN ('admit','hold','dispose','repair','pending','accept','refund','payment','shipping')),loss4 INTEGER NOT NULL CHECK(loss4>=0),recovery4 INTEGER NOT NULL CHECK(recovery4>=0),expense_category TEXT,actor_id INTEGER NOT NULL REFERENCES users(id),occurred_at TEXT NOT NULL,UNIQUE(source_id,revision));
CREATE TABLE stock_valuation_segments(event_id TEXT NOT NULL REFERENCES stock_valuation_events(id),segment_id TEXT NOT NULL,allocation_id TEXT NOT NULL,fate TEXT NOT NULL CHECK(fate IN ('sellable','held','disposed')),quantity TEXT NOT NULL,gross4 INTEGER NOT NULL CHECK(gross4>=0),coverage4 INTEGER NOT NULL CHECK(coverage4>=0 AND coverage4<=gross4),loss4 INTEGER NOT NULL CHECK(loss4>=0),recovery4 INTEGER NOT NULL CHECK(recovery4>=0 AND recovery4<=loss4),reason TEXT NOT NULL,PRIMARY KEY(event_id,segment_id));
CREATE TABLE stock_valuation_agreements(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),amount4 INTEGER NOT NULL CHECK(amount4>0),targets_json TEXT NOT NULL CHECK(json_valid(targets_json) AND json_type(targets_json)='array'),proof TEXT NOT NULL);
CREATE TABLE stock_valuation_acceptances(event_id TEXT NOT NULL REFERENCES stock_valuation_events(id),agreement_id TEXT NOT NULL REFERENCES stock_valuation_agreements(id),target_segment_id TEXT NOT NULL,amount4 INTEGER NOT NULL CHECK(amount4>0),funding_event_id TEXT NOT NULL REFERENCES stock_funding_events(id),PRIMARY KEY(event_id,target_segment_id));
CREATE TABLE stock_valuation_receipts(request_id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES stock_valuation_events(id),actor_id INTEGER NOT NULL REFERENCES users(id),request_digest TEXT NOT NULL,request_json TEXT NOT NULL CHECK(json_valid(request_json) AND json_type(request_json)='object'),response_json TEXT NOT NULL CHECK(json_valid(response_json) AND json_type(response_json)='object'));
CREATE TABLE stock_valuation_guards(token TEXT PRIMARY KEY,valid INTEGER NOT NULL CHECK(valid=1));
CREATE TABLE stock_valuation_context(token TEXT PRIMARY KEY REFERENCES stock_valuation_guards(token),source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),batch_id INTEGER NOT NULL,branch_id INTEGER NOT NULL,remaining_quantity REAL NOT NULL CHECK(remaining_quantity>=0),funding_allowed INTEGER NOT NULL CHECK(funding_allowed IN (0,1)));
CREATE VIEW stock_valuation_latest AS SELECT e.* FROM stock_valuation_events e WHERE NOT EXISTS(SELECT 1 FROM stock_valuation_events n WHERE n.source_id=e.source_id AND n.revision>e.revision);
CREATE TRIGGER stock_valuation_sources_no_update BEFORE UPDATE ON stock_valuation_sources BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_sources_no_delete BEFORE DELETE ON stock_valuation_sources BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_events_no_update BEFORE UPDATE ON stock_valuation_events BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_events_no_delete BEFORE DELETE ON stock_valuation_events BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_segments_no_update BEFORE UPDATE ON stock_valuation_segments BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_segments_no_delete BEFORE DELETE ON stock_valuation_segments BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_agreements_no_update BEFORE UPDATE ON stock_valuation_agreements BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_agreements_no_delete BEFORE DELETE ON stock_valuation_agreements BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_acceptances_no_update BEFORE UPDATE ON stock_valuation_acceptances BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_acceptances_no_delete BEFORE DELETE ON stock_valuation_acceptances BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_receipts_no_update BEFORE UPDATE ON stock_valuation_receipts BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_receipts_no_delete BEFORE DELETE ON stock_valuation_receipts BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_context_owned BEFORE INSERT ON stock_valuation_context WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_guards g JOIN stock_funding_sources s ON s.id=NEW.source_id WHERE g.token=NEW.token AND g.valid=1 AND s.batch_id=NEW.batch_id AND s.branch_id=NEW.branch_id) BEGIN SELECT RAISE(ABORT,'valuation context unowned'); END;
CREATE TRIGGER stock_valuation_context_no_update BEFORE UPDATE ON stock_valuation_context BEGIN SELECT RAISE(ABORT,'valuation context immutable'); END;
CREATE TRIGGER stock_valuation_funding_owned BEFORE INSERT ON stock_funding_events WHEN EXISTS(SELECT 1 FROM stock_valuation_sources WHERE source_id=NEW.source_id) AND NOT EXISTS(SELECT 1 FROM stock_valuation_context x JOIN stock_valuation_guards g ON g.token=x.token WHERE x.source_id=NEW.source_id AND x.funding_allowed=1 AND g.valid=1) BEGIN SELECT RAISE(ABORT,'funding_joint_valuation_required'); END;
DROP TRIGGER stock_lifecycle_lot_update;
CREATE TRIGGER stock_lifecycle_lot_update BEFORE UPDATE ON branch_batch_stock
 WHEN EXISTS(SELECT 1 FROM stock_lifecycle_dependencies WHERE batch_id=OLD.batch_id) AND (NEW.quantity IS NOT OLD.quantity OR NEW.batch_id IS NOT OLD.batch_id OR NEW.branch_id IS NOT OLD.branch_id)
 AND NOT EXISTS(SELECT 1 FROM stock_lifecycle_context x JOIN stock_disposition_guards g ON g.token=x.token WHERE g.valid=1 AND x.batch_id=OLD.batch_id AND x.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.quantity=x.remaining_quantity)
 AND NOT EXISTS(SELECT 1 FROM stock_valuation_context x JOIN stock_valuation_guards g ON g.token=x.token WHERE g.valid=1 AND x.batch_id=OLD.batch_id AND x.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.quantity=x.remaining_quantity)
 BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
CREATE TRIGGER stock_valuation_admit_maintenance BEFORE INSERT ON stock_valuation_sources WHEN EXISTS(SELECT 1 FROM system_flags WHERE key='maintenance') BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
