CREATE TABLE stock_valuation_event_identities(event_id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),revision INTEGER NOT NULL CHECK(revision>=0),schema_version INTEGER NOT NULL CHECK(schema_version IN (3,4)),UNIQUE(source_id,revision));
INSERT INTO stock_valuation_event_identities SELECT id,source_id,revision,3 FROM stock_valuation_events;
CREATE TABLE stock_valuation_request_identities(request_id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES stock_valuation_event_identities(event_id),schema_version INTEGER NOT NULL CHECK(schema_version IN (3,4)));
INSERT INTO stock_valuation_request_identities SELECT request_id,event_id,3 FROM stock_valuation_receipts;
CREATE TABLE stock_valuation_events_v4(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),revision INTEGER NOT NULL CHECK(revision>0),kind TEXT NOT NULL CHECK(kind IN ('hold','dispose','repair','pending','accept','refund','payment','shipping','consume','restore','reconsume')),loss4 INTEGER NOT NULL CHECK(loss4>=0),recovery4 INTEGER NOT NULL CHECK(recovery4>=0),expense_category TEXT,actor_id INTEGER NOT NULL REFERENCES users(id),occurred_at TEXT NOT NULL,consumed_cost4 INTEGER NOT NULL,consumed_recovery4 INTEGER NOT NULL,UNIQUE(source_id,revision));
CREATE TABLE stock_valuation_segments_v4(event_id TEXT NOT NULL REFERENCES stock_valuation_events_v4(id),segment_id TEXT NOT NULL,allocation_id TEXT NOT NULL,fate TEXT NOT NULL CHECK(fate IN ('sellable','held','disposed','consumed')),quantity TEXT NOT NULL,gross4 INTEGER NOT NULL CHECK(gross4>=0),coverage4 INTEGER NOT NULL CHECK(coverage4>=0 AND coverage4<=gross4),loss4 INTEGER NOT NULL CHECK(loss4>=0),recovery4 INTEGER NOT NULL CHECK(recovery4>=0 AND recovery4<=loss4),reason TEXT NOT NULL,consumption_id TEXT,consumed_cost4 INTEGER NOT NULL CHECK(consumed_cost4>=0),consumed_recovery4 INTEGER NOT NULL CHECK(consumed_recovery4>=0 AND consumed_recovery4<=consumed_cost4),PRIMARY KEY(event_id,segment_id));
CREATE TABLE stock_valuation_acceptances_v4(event_id TEXT NOT NULL REFERENCES stock_valuation_events_v4(id),agreement_id TEXT NOT NULL REFERENCES stock_valuation_agreements(id),target_segment_id TEXT NOT NULL,amount4 INTEGER NOT NULL CHECK(amount4>0),funding_event_id TEXT NOT NULL REFERENCES stock_funding_events(id),PRIMARY KEY(event_id,target_segment_id));
CREATE TABLE stock_valuation_receipts_v4(request_id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES stock_valuation_events_v4(id),actor_id INTEGER NOT NULL REFERENCES users(id),request_digest TEXT NOT NULL,request_json TEXT NOT NULL CHECK(json_valid(request_json) AND json_type(request_json)='object'),response_json TEXT NOT NULL CHECK(json_valid(response_json) AND json_type(response_json)='object'));
CREATE TABLE stock_valuation_sale_links(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),original_event_id TEXT NOT NULL REFERENCES stock_valuation_events_v4(id),segment_id TEXT NOT NULL,sale_id INTEGER NOT NULL REFERENCES sales(id),sale_item_id INTEGER NOT NULL REFERENCES sale_items(id),sale_allocation_id INTEGER NOT NULL UNIQUE REFERENCES sale_item_batch_allocations(id),quantity TEXT NOT NULL,sale_request_id TEXT NOT NULL,sale_line_key TEXT NOT NULL,sale_intent_json TEXT NOT NULL CHECK(json_valid(sale_intent_json)),UNIQUE(sale_request_id,sale_line_key));
CREATE TABLE stock_valuation_sale_movements(event_id TEXT PRIMARY KEY REFERENCES stock_valuation_events_v4(id),consumption_id TEXT NOT NULL REFERENCES stock_valuation_sale_links(id),movement_id INTEGER NOT NULL UNIQUE REFERENCES inventory_movements(id),movement_json TEXT NOT NULL CHECK(json_valid(movement_json)));
CREATE TRIGGER stock_valuation_sale_movements_no_update BEFORE UPDATE ON stock_valuation_sale_movements BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_sale_movements_no_delete BEFORE DELETE ON stock_valuation_sale_movements BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_sale_movement_identity BEFORE UPDATE ON inventory_movements WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_movements WHERE movement_id=OLD.id) BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
CREATE TRIGGER stock_valuation_sale_movement_delete BEFORE DELETE ON inventory_movements WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_movements WHERE movement_id=OLD.id) BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
CREATE VIEW stock_valuation_history_events AS SELECT id,source_id,revision,kind,loss4,recovery4,expense_category,actor_id,occurred_at,0 AS consumed_cost4,0 AS consumed_recovery4,3 AS schema_version FROM stock_valuation_events UNION ALL SELECT id,source_id,revision,kind,loss4,recovery4,expense_category,actor_id,occurred_at,consumed_cost4,consumed_recovery4,4 AS schema_version FROM stock_valuation_events_v4;
CREATE VIEW stock_valuation_history_segments AS SELECT event_id,segment_id,allocation_id,fate,quantity,gross4,coverage4,loss4,recovery4,reason,NULL AS consumption_id,0 AS consumed_cost4,0 AS consumed_recovery4 FROM stock_valuation_segments UNION ALL SELECT * FROM stock_valuation_segments_v4;
CREATE VIEW stock_valuation_history_acceptances AS SELECT * FROM stock_valuation_acceptances UNION ALL SELECT * FROM stock_valuation_acceptances_v4;
CREATE VIEW stock_valuation_history_receipts AS SELECT * FROM stock_valuation_receipts UNION ALL SELECT * FROM stock_valuation_receipts_v4;
DROP VIEW stock_valuation_latest;
CREATE VIEW stock_valuation_latest AS SELECT e.* FROM stock_valuation_history_events e WHERE NOT EXISTS(SELECT 1 FROM stock_valuation_event_identities n WHERE n.source_id=e.source_id AND n.revision>e.revision);
CREATE VIEW stock_valuation_sale_costs AS SELECT l.sale_item_id,1 AS managed,SUM(CAST(l.quantity AS REAL)) AS quantity,SUM(s.consumed_cost4) AS cost4,SUM(s.consumed_recovery4) AS recovery4,SUM(s.consumed_cost4-s.consumed_recovery4) AS net4,json_group_array(DISTINCT l.source_id) AS source_ids_json FROM stock_valuation_sale_links l LEFT JOIN stock_valuation_latest e ON e.source_id=l.source_id LEFT JOIN stock_valuation_segments_v4 s ON s.event_id=e.id AND s.consumption_id=l.id GROUP BY l.sale_item_id;
CREATE VIEW stock_valuation_sale_recoveries AS SELECT l.sale_id,l.sale_item_id,l.id AS consumption_id,l.source_id,e.id AS event_id,e.kind,e.occurred_at,s.consumed_cost4-COALESCE(p.consumed_cost4,0) AS consumed_cost4,s.consumed_recovery4-COALESCE(p.consumed_recovery4,0) AS consumed_recovery4 FROM stock_valuation_sale_links l JOIN stock_valuation_history_events e ON e.source_id=l.source_id JOIN stock_valuation_history_segments s ON s.event_id=e.id AND s.consumption_id=l.id LEFT JOIN stock_valuation_history_events pe ON pe.source_id=e.source_id AND pe.revision=e.revision-1 LEFT JOIN stock_valuation_history_segments p ON p.event_id=pe.id AND p.consumption_id=l.id WHERE s.consumed_cost4<>COALESCE(p.consumed_cost4,0) OR s.consumed_recovery4<>COALESCE(p.consumed_recovery4,0);
ALTER TABLE stock_valuation_context ADD COLUMN operation_id TEXT;
CREATE TABLE stock_valuation_sale_operation_context(token TEXT PRIMARY KEY REFERENCES stock_valuation_guards(token),event_id TEXT NOT NULL UNIQUE REFERENCES stock_valuation_events_v4(id),source_id TEXT NOT NULL REFERENCES stock_valuation_sources(source_id),kind TEXT NOT NULL CHECK(kind IN ('consume','restore','reconsume')),segment_id TEXT NOT NULL,consumption_id TEXT NOT NULL REFERENCES stock_valuation_sale_links(id),sale_allocation_id INTEGER NOT NULL REFERENCES sale_item_batch_allocations(id),released_before REAL NOT NULL,released_after REAL NOT NULL,remaining_quantity REAL NOT NULL CHECK(remaining_quantity>=0));
CREATE TRIGGER stock_valuation_events_global_identity BEFORE INSERT ON stock_valuation_events WHEN EXISTS(SELECT 1 FROM stock_valuation_events_v4 WHERE source_id=NEW.source_id) OR EXISTS(SELECT 1 FROM stock_valuation_event_identities WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_valuation_event_identities WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'valuation_global_identity_conflict'); END;
CREATE TRIGGER stock_valuation_events_register AFTER INSERT ON stock_valuation_events BEGIN INSERT INTO stock_valuation_event_identities VALUES(NEW.id,NEW.source_id,NEW.revision,3); END;
CREATE TRIGGER stock_valuation_events_v4_global_identity BEFORE INSERT ON stock_valuation_events_v4 WHEN EXISTS(SELECT 1 FROM stock_valuation_event_identities WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_valuation_event_identities WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'valuation_global_identity_conflict'); END;
CREATE TRIGGER stock_valuation_events_v4_register AFTER INSERT ON stock_valuation_events_v4 BEGIN INSERT INTO stock_valuation_event_identities VALUES(NEW.id,NEW.source_id,NEW.revision,4); END;
CREATE TRIGGER stock_valuation_receipts_register AFTER INSERT ON stock_valuation_receipts BEGIN INSERT INTO stock_valuation_request_identities VALUES(NEW.request_id,NEW.event_id,3); END;
CREATE TRIGGER stock_valuation_receipts_v4_register AFTER INSERT ON stock_valuation_receipts_v4 BEGIN INSERT INTO stock_valuation_request_identities VALUES(NEW.request_id,NEW.event_id,4); END;
CREATE TRIGGER stock_valuation_events_v4_no_update BEFORE UPDATE ON stock_valuation_events_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_events_v4_no_delete BEFORE DELETE ON stock_valuation_events_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_segments_v4_no_update BEFORE UPDATE ON stock_valuation_segments_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_segments_v4_no_delete BEFORE DELETE ON stock_valuation_segments_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_acceptances_v4_no_update BEFORE UPDATE ON stock_valuation_acceptances_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_acceptances_v4_no_delete BEFORE DELETE ON stock_valuation_acceptances_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_receipts_v4_no_update BEFORE UPDATE ON stock_valuation_receipts_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_receipts_v4_no_delete BEFORE DELETE ON stock_valuation_receipts_v4 BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_event_identities_no_update BEFORE UPDATE ON stock_valuation_event_identities BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_event_identities_no_delete BEFORE DELETE ON stock_valuation_event_identities BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_request_identities_no_update BEFORE UPDATE ON stock_valuation_request_identities BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_request_identities_no_delete BEFORE DELETE ON stock_valuation_request_identities BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_sale_links_no_update BEFORE UPDATE ON stock_valuation_sale_links BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_sale_links_no_delete BEFORE DELETE ON stock_valuation_sale_links BEGIN SELECT RAISE(ABORT,'valuation immutable'); END;
CREATE TRIGGER stock_valuation_sale_operation_context_no_update BEFORE UPDATE ON stock_valuation_sale_operation_context BEGIN SELECT RAISE(ABORT,'valuation context immutable'); END;
CREATE TRIGGER stock_valuation_sale_operation_context_owned BEFORE INSERT ON stock_valuation_sale_operation_context WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_guards g JOIN stock_valuation_latest e ON e.id=NEW.event_id JOIN stock_valuation_sale_links l ON l.id=NEW.consumption_id JOIN sale_item_batch_allocations a ON a.id=l.sale_allocation_id JOIN stock_funding_sources f ON f.id=l.source_id JOIN stock_valuation_segments_v4 s ON s.event_id=e.id AND s.segment_id=NEW.segment_id WHERE g.token=NEW.token AND g.valid=1 AND e.kind=NEW.kind AND e.source_id=NEW.source_id AND l.source_id=NEW.source_id AND l.segment_id=NEW.segment_id AND a.id=NEW.sale_allocation_id AND a.batch_id=f.batch_id AND a.branch_id=f.branch_id AND a.quantity=CAST(l.quantity AS REAL) AND a.released_quantity=NEW.released_before AND s.consumption_id=l.id AND CAST(s.quantity AS REAL)=a.quantity AND NEW.released_after=CASE WHEN NEW.kind='restore' THEN a.quantity ELSE 0 END AND s.fate=CASE WHEN NEW.kind='restore' THEN 'sellable' ELSE 'consumed' END) BEGIN SELECT RAISE(ABORT,'valuation_sale_context_unowned'); END;
CREATE TRIGGER stock_valuation_context_v4_owned BEFORE INSERT ON stock_valuation_context WHEN NEW.operation_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM stock_valuation_latest e WHERE e.id=NEW.operation_id AND e.schema_version=4 AND e.source_id=NEW.source_id AND (e.kind NOT IN ('consume','restore','reconsume') OR EXISTS(SELECT 1 FROM stock_valuation_sale_operation_context x WHERE x.token=NEW.token AND x.event_id=e.id AND x.source_id=e.source_id AND x.remaining_quantity=NEW.remaining_quantity))) BEGIN SELECT RAISE(ABORT,'valuation_v4_context_unowned'); END;
CREATE TRIGGER stock_valuation_sale_items_identity BEFORE UPDATE ON sale_items WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_links WHERE sale_item_id=OLD.id) AND (NEW.sale_id IS NOT OLD.sale_id OR NEW.product_id IS NOT OLD.product_id OR NEW.branch_id IS NOT OLD.branch_id OR NEW.batch_id IS NOT OLD.batch_id OR NEW.quantity IS NOT OLD.quantity OR NEW.cost_price_usd IS NOT OLD.cost_price_usd OR NEW.cost_price_khr IS NOT OLD.cost_price_khr) BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
CREATE TRIGGER stock_valuation_sale_items_delete BEFORE DELETE ON sale_items WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_links WHERE sale_item_id=OLD.id) BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
CREATE TRIGGER stock_valuation_sale_allocation_identity BEFORE UPDATE ON sale_item_batch_allocations WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_links WHERE sale_allocation_id=OLD.id) AND (NEW.sale_item_id IS NOT OLD.sale_item_id OR NEW.batch_id IS NOT OLD.batch_id OR NEW.branch_id IS NOT OLD.branch_id OR NEW.quantity IS NOT OLD.quantity OR (NEW.released_quantity IS NOT OLD.released_quantity AND NOT EXISTS(SELECT 1 FROM stock_valuation_sale_operation_context x WHERE x.sale_allocation_id=OLD.id AND x.released_before=OLD.released_quantity AND x.released_after=NEW.released_quantity))) BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
CREATE TRIGGER stock_valuation_sale_allocation_delete BEFORE DELETE ON sale_item_batch_allocations WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_links WHERE sale_allocation_id=OLD.id) BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
DROP TRIGGER stock_lifecycle_lot_update;
CREATE TRIGGER stock_lifecycle_lot_update BEFORE UPDATE ON branch_batch_stock
 WHEN EXISTS(SELECT 1 FROM stock_lifecycle_dependencies WHERE batch_id=OLD.batch_id) AND (NEW.quantity IS NOT OLD.quantity OR NEW.batch_id IS NOT OLD.batch_id OR NEW.branch_id IS NOT OLD.branch_id)
 AND NOT EXISTS(SELECT 1 FROM stock_lifecycle_context x JOIN stock_disposition_guards g ON g.token=x.token WHERE g.valid=1 AND x.batch_id=OLD.batch_id AND x.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.quantity=x.remaining_quantity)
 AND NOT EXISTS(SELECT 1 FROM stock_valuation_context x JOIN stock_valuation_guards g ON g.token=x.token WHERE g.valid=1 AND x.batch_id=OLD.batch_id AND x.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.quantity=x.remaining_quantity AND ((x.operation_id IS NULL AND NOT EXISTS(SELECT 1 FROM stock_valuation_events_v4 e WHERE e.source_id=x.source_id)) OR EXISTS(SELECT 1 FROM stock_valuation_latest e WHERE e.id=x.operation_id AND e.source_id=x.source_id AND e.schema_version=4 AND (e.kind NOT IN ('consume','restore','reconsume') OR EXISTS(SELECT 1 FROM stock_valuation_sale_operation_context op WHERE op.token=x.token AND op.event_id=e.id AND op.source_id=e.source_id AND op.remaining_quantity=NEW.quantity)))))
 BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
DROP TRIGGER stock_lifecycle_lot_insert;
CREATE TRIGGER stock_lifecycle_lot_insert BEFORE INSERT ON branch_batch_stock
 WHEN EXISTS(SELECT 1 FROM stock_lifecycle_dependencies WHERE batch_id=NEW.batch_id)
 AND NOT EXISTS(SELECT 1 FROM branch_batch_stock b JOIN stock_valuation_context c ON c.batch_id=b.batch_id AND c.branch_id=b.branch_id JOIN stock_valuation_guards g ON g.token=c.token AND g.valid=1 JOIN stock_valuation_sale_operation_context op ON op.token=c.token AND op.event_id=c.operation_id JOIN stock_valuation_latest e ON e.id=op.event_id AND e.source_id=op.source_id JOIN stock_valuation_sale_links l ON l.id=op.consumption_id AND l.source_id=op.source_id AND l.sale_allocation_id=op.sale_allocation_id JOIN sale_item_batch_allocations a ON a.id=l.sale_allocation_id JOIN stock_funding_sources f ON f.id=l.source_id WHERE b.batch_id=NEW.batch_id AND b.branch_id=NEW.branch_id AND f.batch_id=b.batch_id AND f.branch_id=b.branch_id AND c.source_id=f.id AND a.batch_id=b.batch_id AND a.branch_id=b.branch_id AND op.kind='restore' AND e.kind='restore' AND e.schema_version=4 AND a.released_quantity=op.released_before AND op.released_before=0 AND op.released_after=a.quantity AND a.quantity=CAST(l.quantity AS REAL) AND NEW.quantity=a.quantity AND b.quantity+NEW.quantity=op.remaining_quantity AND c.remaining_quantity=op.remaining_quantity)
 BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;
