CREATE TABLE stock_epoch_publications(operation_id TEXT PRIMARY KEY REFERENCES stock_epoch_operations(id),published_at TEXT NOT NULL);
CREATE TABLE stock_epoch_sources(
 id TEXT PRIMARY KEY,movement_id INTEGER NOT NULL UNIQUE REFERENCES inventory_movements(id),batch_id INTEGER NOT NULL REFERENCES product_batches(id),
 product_id INTEGER NOT NULL REFERENCES products(id),branch_id INTEGER NOT NULL REFERENCES branches(id),supplier_id INTEGER NOT NULL,
 quantity TEXT NOT NULL,free_quantity TEXT NOT NULL,gross4 INTEGER NOT NULL CHECK(typeof(gross4)='integer' AND gross4 BETWEEN 0 AND 1000000000000000),
 opening_paid4 INTEGER NOT NULL CHECK(opening_paid4>=0),opening_debt4 INTEGER NOT NULL CHECK(opening_debt4>=0 AND opening_paid4+opening_debt4=gross4),
 reconciliation_proof TEXT NOT NULL,invoice_id INTEGER,actor_id INTEGER NOT NULL REFERENCES users(id),source_json TEXT NOT NULL CHECK(json_valid(source_json)),
 source_format INTEGER NOT NULL CHECK(source_format IN (4,5)),admission_operation_id TEXT REFERENCES stock_epoch_publications(operation_id) DEFERRABLE INITIALLY DEFERRED,
 CHECK((source_format=4 AND admission_operation_id IS NULL) OR (source_format=5 AND admission_operation_id IS NOT NULL))
);
INSERT INTO stock_epoch_sources SELECT *,4,NULL FROM stock_funding_sources;
CREATE INDEX stock_epoch_sources_batch ON stock_epoch_sources(batch_id,branch_id,movement_id,id);
CREATE TABLE stock_epoch_event_registry(event_id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),revision INTEGER NOT NULL CHECK(revision>=0),schema_version INTEGER NOT NULL CHECK(schema_version IN (3,4,5)),UNIQUE(source_id,revision));
INSERT INTO stock_epoch_event_registry SELECT * FROM stock_valuation_event_identities;
CREATE TABLE stock_epoch_request_registry(request_id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES stock_epoch_event_registry(event_id),schema_version INTEGER NOT NULL CHECK(schema_version IN (3,4,5)));
INSERT INTO stock_epoch_request_registry SELECT * FROM stock_valuation_request_identities;
CREATE TABLE stock_epoch_dataset(singleton INTEGER PRIMARY KEY CHECK(singleton=1),generation INTEGER NOT NULL CHECK(generation>=0));
INSERT INTO stock_epoch_dataset VALUES(1,0);
CREATE TABLE stock_epoch_operations(
 id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,actor_id INTEGER NOT NULL REFERENCES users(id),actor_permissions TEXT NOT NULL,
 dataset_generation INTEGER NOT NULL,kind TEXT NOT NULL,request_json TEXT NOT NULL CHECK(json_valid(request_json)),
 source_count INTEGER NOT NULL CHECK(source_count>0),epoch_count INTEGER NOT NULL CHECK(epoch_count>=0),assignment_count INTEGER NOT NULL CHECK(assignment_count>=0),
 FOREIGN KEY(id) REFERENCES stock_epoch_publications(operation_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE stock_epoch_operation_sources(
 operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),
 expected_revision INTEGER NOT NULL CHECK(expected_revision>=-1),expected_funding_generation INTEGER NOT NULL CHECK(expected_funding_generation>=-1),
 event_id TEXT NOT NULL UNIQUE,PRIMARY KEY(operation_id,source_id)
);
CREATE TABLE stock_epoch_events(
 id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),revision INTEGER NOT NULL CHECK(revision>=0),
 kind TEXT NOT NULL CHECK(kind IN ('adopt','admit','hold','dispose','repair','pending','accept','refund','payment','shipping','consume','restore','reconsume','return')),
 loss4 INTEGER NOT NULL CHECK(loss4>=0),recovery4 INTEGER NOT NULL CHECK(recovery4>=0),expense_category TEXT,
 actor_id INTEGER NOT NULL REFERENCES users(id),occurred_at TEXT NOT NULL,consumed_cost4 INTEGER NOT NULL,consumed_recovery4 INTEGER NOT NULL,
 operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),funding_generation INTEGER NOT NULL CHECK(funding_generation>=0),
 funding_json TEXT NOT NULL CHECK(json_valid(funding_json)),UNIQUE(source_id,revision),UNIQUE(operation_id,source_id)
);
CREATE TABLE stock_epoch_segments(
 event_id TEXT NOT NULL REFERENCES stock_epoch_events(id),segment_id TEXT NOT NULL,allocation_id TEXT NOT NULL,
 fate TEXT NOT NULL CHECK(fate IN ('sellable','held','disposed','consumed','retired')),quantity TEXT NOT NULL,
 gross4 INTEGER NOT NULL CHECK(typeof(gross4)='integer' AND gross4 BETWEEN 0 AND 1000000000000000),coverage4 INTEGER NOT NULL CHECK(typeof(coverage4)='integer' AND coverage4 BETWEEN 0 AND gross4),
 loss4 INTEGER NOT NULL CHECK(loss4>=0),recovery4 INTEGER NOT NULL CHECK(recovery4 BETWEEN 0 AND loss4),reason TEXT NOT NULL,
 consumption_id TEXT,consumed_cost4 INTEGER NOT NULL CHECK(consumed_cost4>=0),consumed_recovery4 INTEGER NOT NULL CHECK(consumed_recovery4 BETWEEN 0 AND consumed_cost4),
 PRIMARY KEY(event_id,segment_id)
);
CREATE INDEX stock_epoch_segment_lookup ON stock_epoch_segments(segment_id,event_id);
CREATE TABLE stock_epoch_receipts(request_id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES stock_epoch_events(id),actor_id INTEGER NOT NULL REFERENCES users(id),request_digest TEXT NOT NULL,request_json TEXT NOT NULL CHECK(json_valid(request_json)),response_json TEXT NOT NULL CHECK(json_valid(response_json)));
CREATE TABLE stock_epoch_lines(sale_item_id INTEGER PRIMARY KEY REFERENCES sale_items(id),original_quantity TEXT NOT NULL,sale_request_id TEXT NOT NULL,line_key TEXT NOT NULL,UNIQUE(sale_request_id,line_key));
CREATE TABLE stock_epoch_line_allocations(sale_item_id INTEGER NOT NULL REFERENCES stock_epoch_lines(sale_item_id),allocation_id INTEGER NOT NULL UNIQUE REFERENCES sale_item_batch_allocations(id),original_quantity TEXT NOT NULL,PRIMARY KEY(sale_item_id,allocation_id));
CREATE TABLE stock_epoch_epochs(id TEXT PRIMARY KEY,operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),sale_item_id INTEGER NOT NULL REFERENCES stock_epoch_lines(sale_item_id),generation INTEGER NOT NULL CHECK(generation>=0),target_quantity TEXT NOT NULL,returned_quantity TEXT NOT NULL,sale_status TEXT NOT NULL,UNIQUE(sale_item_id,generation),UNIQUE(operation_id,sale_item_id));
CREATE TABLE stock_epoch_assignments(id TEXT PRIMARY KEY,epoch_id TEXT NOT NULL REFERENCES stock_epoch_epochs(id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),allocation_id INTEGER NOT NULL REFERENCES sale_item_batch_allocations(id),segment_id TEXT NOT NULL,quantity TEXT NOT NULL,cost4 INTEGER NOT NULL CHECK(cost4>=0),UNIQUE(epoch_id,source_id,segment_id));
CREATE TABLE stock_epoch_assignment_changes(event_id TEXT NOT NULL REFERENCES stock_epoch_events(id),assignment_id TEXT NOT NULL REFERENCES stock_epoch_assignments(id),cost_delta4 INTEGER NOT NULL,recovery_delta4 INTEGER NOT NULL,PRIMARY KEY(event_id,assignment_id));
CREATE TABLE stock_epoch_provenance(sale_item_id INTEGER NOT NULL REFERENCES stock_epoch_lines(sale_item_id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),PRIMARY KEY(sale_item_id,source_id));
CREATE TABLE stock_epoch_effects(operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),allocation_id INTEGER NOT NULL REFERENCES sale_item_batch_allocations(id),movement_id INTEGER NOT NULL UNIQUE REFERENCES inventory_movements(id),movement_json TEXT NOT NULL CHECK(json_valid(movement_json)),PRIMARY KEY(operation_id,allocation_id));
CREATE TABLE stock_epoch_adoptions(source_id TEXT PRIMARY KEY REFERENCES stock_epoch_sources(id),operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),previous_event_id TEXT NOT NULL REFERENCES stock_valuation_event_identities(event_id),previous_revision INTEGER NOT NULL,funding_generation INTEGER NOT NULL,dataset_generation INTEGER NOT NULL,checkpoint_id TEXT NOT NULL);
CREATE TABLE stock_epoch_adoption_lines(source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),sale_item_id INTEGER NOT NULL REFERENCES stock_epoch_lines(sale_item_id),allocation_id INTEGER NOT NULL REFERENCES sale_item_batch_allocations(id),sale_status TEXT NOT NULL,released_quantity REAL NOT NULL,PRIMARY KEY(source_id,allocation_id));
CREATE TABLE stock_epoch_adoption_fragments(source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),segment_id TEXT NOT NULL,segment_json TEXT NOT NULL CHECK(json_valid(segment_json)),PRIMARY KEY(source_id,segment_id));
CREATE TABLE stock_epoch_verifications(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),dataset_generation INTEGER NOT NULL,head_event_id TEXT NOT NULL REFERENCES stock_epoch_event_registry(event_id),head_revision INTEGER NOT NULL,funding_generation INTEGER NOT NULL,previous_checkpoint_id TEXT REFERENCES stock_epoch_checkpoints(id),protocol INTEGER NOT NULL CHECK(protocol=1),member_count INTEGER NOT NULL CHECK(member_count>0));
CREATE TABLE stock_epoch_verified_members(verification_id TEXT NOT NULL REFERENCES stock_epoch_verifications(id),record_key TEXT NOT NULL,record_json TEXT NOT NULL CHECK(json_valid(record_json)),PRIMARY KEY(verification_id,record_key));
CREATE TABLE stock_epoch_checkpoints(id TEXT PRIMARY KEY,verification_id TEXT NOT NULL UNIQUE REFERENCES stock_epoch_verifications(id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),head_event_id TEXT NOT NULL REFERENCES stock_epoch_event_registry(event_id),head_revision INTEGER NOT NULL,dataset_generation INTEGER NOT NULL,published_at TEXT NOT NULL,UNIQUE(source_id,head_revision));
CREATE TABLE stock_epoch_restore_runs(id TEXT PRIMARY KEY,expected_generation INTEGER NOT NULL,next_generation INTEGER NOT NULL CHECK(next_generation=expected_generation+1),actor_id INTEGER NOT NULL REFERENCES users(id),actor_permissions TEXT NOT NULL,manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),expected_members INTEGER NOT NULL CHECK(expected_members>0));
CREATE TABLE stock_epoch_restore_members(run_id TEXT NOT NULL REFERENCES stock_epoch_restore_runs(id),table_name TEXT NOT NULL,row_key TEXT NOT NULL,row_json TEXT NOT NULL CHECK(json_valid(row_json)),PRIMARY KEY(run_id,table_name,row_key));
CREATE TABLE stock_epoch_restore_verifications(run_id TEXT NOT NULL REFERENCES stock_epoch_restore_runs(id),table_name TEXT NOT NULL,member_count INTEGER NOT NULL CHECK(member_count>=0),verified_json TEXT NOT NULL CHECK(json_valid(verified_json)),PRIMARY KEY(run_id,table_name));
CREATE TRIGGER stock_disposition_sources_epoch_no_replace BEFORE INSERT ON stock_disposition_sources WHEN EXISTS(SELECT 1 FROM stock_disposition_sources WHERE (NEW.batch_id IS NOT NULL AND batch_id IS NEW.batch_id) OR (NEW.movement_id IS NOT NULL AND movement_id IS NEW.movement_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_disposition_allocations_epoch_no_replace BEFORE INSERT ON stock_disposition_allocations WHEN EXISTS(SELECT 1 FROM stock_disposition_allocations WHERE (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_disposition_events_epoch_no_replace BEFORE INSERT ON stock_disposition_events WHEN EXISTS(SELECT 1 FROM stock_disposition_events WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.generation IS NOT NULL AND generation IS NEW.generation) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_disposition_fees_epoch_no_replace BEFORE INSERT ON stock_disposition_fees WHEN EXISTS(SELECT 1 FROM stock_disposition_fees WHERE (NEW.fee_id IS NOT NULL AND fee_id IS NEW.fee_id) OR (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_disposition_receipts_epoch_no_replace BEFORE INSERT ON stock_disposition_receipts WHEN EXISTS(SELECT 1 FROM stock_disposition_receipts WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_funding_invoice_openings_epoch_no_replace BEFORE INSERT ON stock_funding_invoice_openings WHEN EXISTS(SELECT 1 FROM stock_funding_invoice_openings WHERE (NEW.invoice_id IS NOT NULL AND invoice_id IS NEW.invoice_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_funding_sources_epoch_no_replace BEFORE INSERT ON stock_funding_sources WHEN EXISTS(SELECT 1 FROM stock_funding_sources WHERE (NEW.batch_id IS NOT NULL AND batch_id IS NEW.batch_id) OR (NEW.movement_id IS NOT NULL AND movement_id IS NEW.movement_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_funding_claims_epoch_no_replace BEFORE INSERT ON stock_funding_claims WHEN EXISTS(SELECT 1 FROM stock_funding_claims WHERE (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_funding_events_epoch_no_replace BEFORE INSERT ON stock_funding_events WHEN EXISTS(SELECT 1 FROM stock_funding_events WHERE ((kind IN ('accept','cancel')) AND NEW.claim_id IS NOT NULL AND claim_id IS NEW.claim_id) OR (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.generation IS NOT NULL AND generation IS NEW.generation) OR (NEW.fee_id IS NOT NULL AND fee_id IS NEW.fee_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_funding_receipts_epoch_no_replace BEFORE INSERT ON stock_funding_receipts WHEN EXISTS(SELECT 1 FROM stock_funding_receipts WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_sources_epoch_no_replace BEFORE INSERT ON stock_valuation_sources WHEN EXISTS(SELECT 1 FROM stock_valuation_sources WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_events_epoch_no_replace BEFORE INSERT ON stock_valuation_events WHEN EXISTS(SELECT 1 FROM stock_valuation_events WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.revision IS NOT NULL AND revision IS NEW.revision) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_segments_epoch_no_replace BEFORE INSERT ON stock_valuation_segments WHEN EXISTS(SELECT 1 FROM stock_valuation_segments WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id AND NEW.segment_id IS NOT NULL AND segment_id IS NEW.segment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_agreements_epoch_no_replace BEFORE INSERT ON stock_valuation_agreements WHEN EXISTS(SELECT 1 FROM stock_valuation_agreements WHERE (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_acceptances_epoch_no_replace BEFORE INSERT ON stock_valuation_acceptances WHEN EXISTS(SELECT 1 FROM stock_valuation_acceptances WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id AND NEW.target_segment_id IS NOT NULL AND target_segment_id IS NEW.target_segment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_receipts_epoch_no_replace BEFORE INSERT ON stock_valuation_receipts WHEN EXISTS(SELECT 1 FROM stock_valuation_receipts WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_context_epoch_no_replace BEFORE INSERT ON stock_valuation_context WHEN EXISTS(SELECT 1 FROM stock_valuation_context WHERE (NEW.token IS NOT NULL AND token IS NEW.token)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_event_identities_epoch_no_replace BEFORE INSERT ON stock_valuation_event_identities WHEN EXISTS(SELECT 1 FROM stock_valuation_event_identities WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.revision IS NOT NULL AND revision IS NEW.revision) OR (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_request_identities_epoch_no_replace BEFORE INSERT ON stock_valuation_request_identities WHEN EXISTS(SELECT 1 FROM stock_valuation_request_identities WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_events_v4_epoch_no_replace BEFORE INSERT ON stock_valuation_events_v4 WHEN EXISTS(SELECT 1 FROM stock_valuation_events_v4 WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.revision IS NOT NULL AND revision IS NEW.revision) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_segments_v4_epoch_no_replace BEFORE INSERT ON stock_valuation_segments_v4 WHEN EXISTS(SELECT 1 FROM stock_valuation_segments_v4 WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id AND NEW.segment_id IS NOT NULL AND segment_id IS NEW.segment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_acceptances_v4_epoch_no_replace BEFORE INSERT ON stock_valuation_acceptances_v4 WHEN EXISTS(SELECT 1 FROM stock_valuation_acceptances_v4 WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id AND NEW.target_segment_id IS NOT NULL AND target_segment_id IS NEW.target_segment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_receipts_v4_epoch_no_replace BEFORE INSERT ON stock_valuation_receipts_v4 WHEN EXISTS(SELECT 1 FROM stock_valuation_receipts_v4 WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_sale_links_epoch_no_replace BEFORE INSERT ON stock_valuation_sale_links WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_links WHERE (NEW.sale_request_id IS NOT NULL AND sale_request_id IS NEW.sale_request_id AND NEW.sale_line_key IS NOT NULL AND sale_line_key IS NEW.sale_line_key) OR (NEW.sale_allocation_id IS NOT NULL AND sale_allocation_id IS NEW.sale_allocation_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_sale_movements_epoch_no_replace BEFORE INSERT ON stock_valuation_sale_movements WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_movements WHERE (NEW.movement_id IS NOT NULL AND movement_id IS NEW.movement_id) OR (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_valuation_sale_operation_context_epoch_no_replace BEFORE INSERT ON stock_valuation_sale_operation_context WHEN EXISTS(SELECT 1 FROM stock_valuation_sale_operation_context WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.token IS NOT NULL AND token IS NEW.token)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_funding_sources_epoch_collision BEFORE INSERT ON stock_funding_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_sources WHERE id=NEW.id OR movement_id=NEW.movement_id OR batch_id=NEW.batch_id) BEGIN SELECT RAISE(ABORT,'epoch source identity'); END;
CREATE TRIGGER stock_funding_sources_epoch_register AFTER INSERT ON stock_funding_sources BEGIN INSERT INTO stock_epoch_sources SELECT *,4,NULL FROM stock_funding_sources WHERE id=NEW.id; END;
CREATE TRIGGER stock_epoch_source_owned BEFORE INSERT ON stock_epoch_sources WHEN (NEW.source_format=4 AND NOT EXISTS(SELECT 1 FROM stock_funding_sources s WHERE s.id=NEW.id AND s.movement_id=NEW.movement_id AND s.source_json=NEW.source_json)) OR (NEW.source_format=5 AND NOT EXISTS(SELECT 1 FROM inventory_movements m JOIN product_batches b ON b.id=m.batch_id WHERE m.id=NEW.movement_id AND m.batch_id=NEW.batch_id AND m.product_id=NEW.product_id AND m.branch_id=NEW.branch_id AND b.supplier_id=NEW.supplier_id AND m.movement_type IN ('add','in') AND m.quantity=CAST(NEW.quantity AS REAL) AND COALESCE(m.free_quantity,0)=CAST(NEW.free_quantity AS REAL) AND m.total_cost_usd=NEW.gross4/10000.0)) BEGIN SELECT RAISE(ABORT,'epoch source preimage'); END;
CREATE TRIGGER stock_valuation_event_identities_epoch_owned BEFORE INSERT ON stock_valuation_event_identities WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_history_events e WHERE e.id=NEW.event_id AND e.source_id=NEW.source_id AND e.revision=NEW.revision AND e.schema_version=NEW.schema_version) BEGIN SELECT RAISE(ABORT,'epoch old registry unowned'); END;
CREATE TRIGGER stock_valuation_request_identities_epoch_owned BEFORE INSERT ON stock_valuation_request_identities WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_history_receipts r JOIN stock_valuation_history_events e ON e.id=r.event_id WHERE r.request_id=NEW.request_id AND r.event_id=NEW.event_id AND e.schema_version=NEW.schema_version) BEGIN SELECT RAISE(ABORT,'epoch old request unowned'); END;
CREATE TRIGGER stock_epoch_event_registry_owned BEFORE INSERT ON stock_epoch_event_registry WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_event_identities i JOIN stock_valuation_history_events e ON e.id=i.event_id AND e.source_id=i.source_id AND e.revision=i.revision AND e.schema_version=i.schema_version WHERE i.event_id=NEW.event_id AND i.source_id=NEW.source_id AND i.revision=NEW.revision AND i.schema_version=NEW.schema_version) AND NOT EXISTS(SELECT 1 FROM stock_epoch_events e WHERE NEW.schema_version=5 AND e.id=NEW.event_id AND e.source_id=NEW.source_id AND e.revision=NEW.revision) BEGIN SELECT RAISE(ABORT,'epoch registry unowned'); END;
CREATE TRIGGER stock_valuation_event_identities_epoch_register AFTER INSERT ON stock_valuation_event_identities BEGIN INSERT INTO stock_epoch_event_registry VALUES(NEW.event_id,NEW.source_id,NEW.revision,NEW.schema_version); END;
CREATE TRIGGER stock_epoch_events_register AFTER INSERT ON stock_epoch_events BEGIN INSERT INTO stock_epoch_event_registry VALUES(NEW.id,NEW.source_id,NEW.revision,5); END;
CREATE TRIGGER stock_epoch_request_registry_owned BEFORE INSERT ON stock_epoch_request_registry WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_request_identities i WHERE i.request_id=NEW.request_id AND i.event_id=NEW.event_id AND i.schema_version=NEW.schema_version) AND NOT EXISTS(SELECT 1 FROM stock_epoch_receipts r WHERE NEW.schema_version=5 AND r.request_id=NEW.request_id AND r.event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'epoch request unowned'); END;
CREATE TRIGGER stock_valuation_request_identities_epoch_register AFTER INSERT ON stock_valuation_request_identities BEGIN INSERT INTO stock_epoch_request_registry VALUES(NEW.request_id,NEW.event_id,NEW.schema_version); END;
CREATE TRIGGER stock_epoch_receipts_register AFTER INSERT ON stock_epoch_receipts BEGIN INSERT INTO stock_epoch_request_registry VALUES(NEW.request_id,NEW.event_id,5); END;
CREATE TRIGGER stock_epoch_operation_actor BEFORE INSERT ON stock_epoch_operations WHEN NEW.dataset_generation<>(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.actor_id AND is_active=1 AND permissions=NEW.actor_permissions) BEGIN SELECT RAISE(ABORT,'epoch actor or dataset changed'); END;
CREATE TRIGGER stock_epoch_member_preimage BEFORE INSERT ON stock_epoch_operation_sources WHEN NEW.expected_revision<>(SELECT COALESCE(MAX(revision),-1) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) OR NEW.expected_funding_generation<>COALESCE((SELECT funding_generation FROM stock_epoch_events WHERE source_id=NEW.source_id ORDER BY revision DESC LIMIT 1),(SELECT MAX(generation) FROM stock_funding_events WHERE source_id=NEW.source_id),-1) BEGIN SELECT RAISE(ABORT,'epoch source changed'); END;
CREATE TRIGGER stock_epoch_event_member BEFORE INSERT ON stock_epoch_events WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operation_sources m JOIN stock_epoch_operations o ON o.id=m.operation_id WHERE m.operation_id=NEW.operation_id AND m.source_id=NEW.source_id AND m.event_id=NEW.id AND m.expected_revision+1=NEW.revision AND o.actor_id=NEW.actor_id AND o.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1)) BEGIN SELECT RAISE(ABORT,'epoch event member'); END;
CREATE TRIGGER stock_epoch_source_batch_owned BEFORE INSERT ON stock_epoch_sources WHEN NEW.source_format=5 AND EXISTS(SELECT 1 FROM stock_funding_sources s WHERE s.batch_id=NEW.batch_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_adoptions a WHERE a.source_id=s.id)) BEGIN SELECT RAISE(ABORT,'epoch shared batch requires complete adoption'); END;
CREATE TRIGGER stock_epoch_publish_registries BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_events e WHERE e.operation_id=NEW.operation_id AND (NOT EXISTS(SELECT 1 FROM stock_epoch_event_registry r WHERE r.event_id=e.id AND r.source_id=e.source_id AND r.revision=e.revision AND r.schema_version=5) OR NOT EXISTS(SELECT 1 FROM stock_epoch_receipts r JOIN stock_epoch_request_registry i ON i.request_id=r.request_id AND i.event_id=r.event_id AND i.schema_version=5 WHERE r.event_id=e.id))) BEGIN SELECT RAISE(ABORT,'epoch registration incomplete'); END;
CREATE TRIGGER stock_epoch_publish_source_admission BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_sources s JOIN product_batches b ON b.id=s.batch_id WHERE s.admission_operation_id=NEW.operation_id AND (NOT EXISTS(SELECT 1 FROM stock_epoch_events e WHERE e.operation_id=NEW.operation_id AND e.source_id=s.id AND e.kind='admit' AND e.revision=0) OR b.received_quantity<>(SELECT SUM(CAST(quantity AS REAL)) FROM stock_epoch_sources WHERE batch_id=s.batch_id) OR b.received_cost_usd<>(SELECT SUM(gross4)/10000.0 FROM stock_epoch_sources WHERE batch_id=s.batch_id) OR EXISTS(SELECT 1 FROM inventory_movements m WHERE m.batch_id=s.batch_id AND m.movement_type IN ('add','in') AND NOT EXISTS(SELECT 1 FROM stock_epoch_sources x WHERE x.movement_id=m.id)))) BEGIN SELECT RAISE(ABORT,'epoch source admission incomplete'); END;
CREATE TRIGGER stock_epoch_adoption_line_exact BEFORE INSERT ON stock_epoch_adoption_lines WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_sale_links l JOIN sale_item_batch_allocations a ON a.id=l.sale_allocation_id JOIN sale_items i ON i.id=l.sale_item_id JOIN sales s ON s.id=l.sale_id WHERE l.source_id=NEW.source_id AND l.sale_item_id=NEW.sale_item_id AND l.sale_allocation_id=NEW.allocation_id AND a.released_quantity=NEW.released_quantity AND s.sale_status=NEW.sale_status AND a.sale_item_id=i.id AND a.quantity=CAST(l.quantity AS REAL)) BEGIN SELECT RAISE(ABORT,'epoch adoption line changed'); END;
CREATE TRIGGER stock_epoch_adoption_fragment_exact BEFORE INSERT ON stock_epoch_adoption_fragments WHEN NOT EXISTS(SELECT 1 FROM stock_valuation_history_segments s JOIN stock_valuation_latest e ON e.id=s.event_id WHERE e.source_id=NEW.source_id AND s.segment_id=NEW.segment_id AND json_object('event_id',s.event_id,'segment_id',s.segment_id,'allocation_id',s.allocation_id,'fate',s.fate,'quantity',s.quantity,'gross4',s.gross4,'coverage4',s.coverage4,'loss4',s.loss4,'recovery4',s.recovery4,'reason',s.reason,'consumption_id',s.consumption_id,'consumed_cost4',s.consumed_cost4,'consumed_recovery4',s.consumed_recovery4)=NEW.segment_json) BEGIN SELECT RAISE(ABORT,'epoch adoption fragment changed'); END;
CREATE TRIGGER stock_epoch_publish_adoption_complete BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_adoptions d WHERE d.operation_id=NEW.operation_id AND (d.funding_generation<>(SELECT MAX(generation) FROM stock_funding_events WHERE source_id=d.source_id) OR d.previous_event_id<>(SELECT id FROM stock_valuation_latest WHERE source_id=d.source_id) OR EXISTS(SELECT 1 FROM stock_valuation_sale_links l WHERE l.source_id=d.source_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_adoption_lines m JOIN sale_item_batch_allocations a ON a.id=m.allocation_id JOIN sale_items i ON i.id=m.sale_item_id JOIN sales s ON s.id=i.sale_id JOIN stock_epoch_epochs e ON e.sale_item_id=m.sale_item_id AND e.operation_id=d.operation_id WHERE m.source_id=l.source_id AND m.allocation_id=l.sale_allocation_id AND m.sale_item_id=l.sale_item_id AND m.sale_status=s.sale_status AND m.released_quantity=a.released_quantity)) OR EXISTS(SELECT 1 FROM stock_valuation_history_segments s WHERE s.event_id=d.previous_event_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_adoption_fragments f WHERE f.source_id=d.source_id AND f.segment_id=s.segment_id)) OR EXISTS(SELECT 1 FROM stock_valuation_sale_links l JOIN stock_valuation_sale_links sibling ON sibling.sale_id=l.sale_id WHERE l.source_id=d.source_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_adoptions a WHERE a.source_id=sibling.source_id AND a.operation_id=d.operation_id)))) BEGIN SELECT RAISE(ABORT,'epoch adoption membership incomplete'); END;
CREATE TRIGGER stock_valuation_events_epoch_identity BEFORE INSERT ON stock_valuation_events WHEN EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) OR EXISTS(SELECT 1 FROM stock_epoch_adoptions WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'epoch global identity'); END;
CREATE TRIGGER stock_valuation_events_v4_epoch_identity BEFORE INSERT ON stock_valuation_events_v4 WHEN EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) OR EXISTS(SELECT 1 FROM stock_epoch_adoptions WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'epoch global identity'); END;
CREATE TRIGGER stock_epoch_events_epoch_identity BEFORE INSERT ON stock_epoch_events WHEN EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'epoch global identity'); END;
CREATE TRIGGER stock_valuation_receipts_epoch_request BEFORE INSERT ON stock_valuation_receipts WHEN EXISTS(SELECT 1 FROM stock_epoch_request_registry WHERE request_id=NEW.request_id OR event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'epoch request identity'); END;
CREATE TRIGGER stock_valuation_receipts_v4_epoch_request BEFORE INSERT ON stock_valuation_receipts_v4 WHEN EXISTS(SELECT 1 FROM stock_epoch_request_registry WHERE request_id=NEW.request_id OR event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'epoch request identity'); END;
CREATE TRIGGER stock_epoch_receipts_epoch_request BEFORE INSERT ON stock_epoch_receipts WHEN EXISTS(SELECT 1 FROM stock_epoch_request_registry WHERE request_id=NEW.request_id OR event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'epoch request identity'); END;
CREATE TRIGGER stock_funding_events_epoch_adopted BEFORE INSERT ON stock_funding_events WHEN EXISTS(SELECT 1 FROM stock_epoch_adoptions WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'epoch old funding writer'); END;
CREATE TRIGGER stock_epoch_epoch_identity BEFORE INSERT ON stock_epoch_epochs WHEN NEW.generation<>(SELECT COALESCE(MAX(generation)+1,0) FROM stock_epoch_epochs WHERE sale_item_id=NEW.sale_item_id) OR NOT EXISTS(SELECT 1 FROM stock_epoch_lines l JOIN sale_items i ON i.id=l.sale_item_id JOIN sales s ON s.id=i.sale_id WHERE l.sale_item_id=NEW.sale_item_id AND s.sale_status=NEW.sale_status AND CAST(NEW.target_quantity AS REAL)=CASE WHEN NEW.sale_status='cancelled' THEN 0 ELSE MAX(0,CAST(l.original_quantity AS REAL)-CAST(NEW.returned_quantity AS REAL)) END) BEGIN SELECT RAISE(ABORT,'epoch active target'); END;
CREATE TRIGGER stock_epoch_assignment_owned BEFORE INSERT ON stock_epoch_assignments WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_epochs e JOIN stock_epoch_line_allocations l ON l.sale_item_id=e.sale_item_id JOIN sale_item_batch_allocations a ON a.id=l.allocation_id JOIN stock_epoch_sources s ON s.id=NEW.source_id WHERE e.id=NEW.epoch_id AND a.id=NEW.allocation_id AND a.batch_id=s.batch_id AND a.branch_id=s.branch_id AND CAST(NEW.quantity AS REAL)>0 AND CAST(NEW.quantity AS REAL)<=CAST(e.target_quantity AS REAL)) BEGIN SELECT RAISE(ABORT,'epoch assignment unowned'); END;
CREATE TRIGGER stock_epoch_publish_complete BEFORE INSERT ON stock_epoch_publications WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN users u ON u.id=o.actor_id WHERE o.id=NEW.operation_id AND u.is_active=1 AND u.permissions=o.actor_permissions AND o.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) AND o.source_count=(SELECT COUNT(*) FROM stock_epoch_operation_sources WHERE operation_id=o.id) AND o.source_count=(SELECT COUNT(*) FROM stock_epoch_events WHERE operation_id=o.id) AND o.source_count=(SELECT COUNT(*) FROM stock_epoch_receipts r JOIN stock_epoch_events e ON e.id=r.event_id WHERE e.operation_id=o.id) AND o.epoch_count=(SELECT COUNT(*) FROM stock_epoch_epochs WHERE operation_id=o.id) AND o.assignment_count=(SELECT COUNT(*) FROM stock_epoch_assignments a JOIN stock_epoch_epochs e ON e.id=a.epoch_id WHERE e.operation_id=o.id)) OR EXISTS(SELECT 1 FROM stock_epoch_epochs e WHERE e.operation_id=NEW.operation_id AND CAST(e.target_quantity AS REAL)<>COALESCE((SELECT SUM(CAST(quantity AS REAL)) FROM stock_epoch_assignments WHERE epoch_id=e.id),0)) BEGIN SELECT RAISE(ABORT,'epoch publication incomplete'); END;
CREATE TRIGGER stock_epoch_dataset_held BEFORE UPDATE ON stock_epoch_dataset BEGIN SELECT RAISE(ABORT,'epoch authenticated restore publication required'); END;
CREATE TRIGGER stock_epoch_dataset_no_delete BEFORE DELETE ON stock_epoch_dataset BEGIN SELECT RAISE(ABORT,'epoch dataset immutable'); END;
CREATE TRIGGER stock_epoch_restore_authority BEFORE INSERT ON stock_epoch_restore_runs WHEN NEW.expected_generation<>(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.actor_id AND is_active=1 AND permissions=NEW.actor_permissions) BEGIN SELECT RAISE(ABORT,'epoch restore authority changed'); END;
CREATE TRIGGER stock_epoch_restore_auth_excluded BEFORE INSERT ON stock_epoch_restore_members WHEN NEW.table_name IN ('users','roles','sessions','auth_sessions','stock_epoch_dataset') OR NEW.table_name GLOB '*_context' OR NEW.table_name GLOB '*_guards' BEGIN SELECT RAISE(ABORT,'epoch restore current authority preserved'); END;
CREATE VIEW stock_epoch_prefix_records AS SELECT t.id AS source_id,'stock_funding_sources:'||json_array(t.id) AS record_key,json_object('id',t.id,'movement_id',t.movement_id,'batch_id',t.batch_id,'product_id',t.product_id,'branch_id',t.branch_id,'supplier_id',t.supplier_id,'quantity',t.quantity,'free_quantity',t.free_quantity,'gross4',t.gross4,'opening_paid4',t.opening_paid4,'opening_debt4',t.opening_debt4,'reconciliation_proof',t.reconciliation_proof,'invoice_id',t.invoice_id,'actor_id',t.actor_id,'source_json',t.source_json) AS record_json FROM stock_funding_sources t
UNION ALL
SELECT t.source_id AS source_id,'stock_funding_claims:'||json_array(t.id) AS record_key,json_object('id',t.id,'source_id',t.source_id,'amount4',t.amount4,'proof',t.proof) AS record_json FROM stock_funding_claims t
UNION ALL
SELECT t.source_id AS source_id,'stock_funding_events:'||json_array(t.id) AS record_key,json_object('id',t.id,'source_id',t.source_id,'generation',t.generation,'kind',t.kind,'amount4',t.amount4,'claim_id',t.claim_id,'fee_id',t.fee_id,'gross4',t.gross4,'paid4',t.paid4,'debt4',t.debt4,'credit4',t.credit4,'asset4',t.asset4,'cash_in4',t.cash_in4,'cash_out4',t.cash_out4,'shipping4',t.shipping4,'proof',t.proof,'cash_method',t.cash_method,'cash_reference',t.cash_reference,'cash_recorded_at',t.cash_recorded_at,'actor_id',t.actor_id,'occurred_at',t.occurred_at) AS record_json FROM stock_funding_events t
UNION ALL
SELECT (SELECT source_id FROM stock_funding_events WHERE id=t.event_id) AS source_id,'stock_funding_receipts:'||json_array(t.request_id) AS record_key,json_object('request_id',t.request_id,'actor_id',t.actor_id,'request_digest',t.request_digest,'request_json',t.request_json,'response_json',t.response_json,'event_id',t.event_id) AS record_json FROM stock_funding_receipts t
UNION ALL
SELECT t.source_id AS source_id,'stock_valuation_sources:'||json_array(t.source_id) AS record_key,json_object('source_id',t.source_id,'opening_json',t.opening_json) AS record_json FROM stock_valuation_sources t
UNION ALL
SELECT t.source_id AS source_id,'stock_valuation_events:'||json_array(t.id) AS record_key,json_object('id',t.id,'source_id',t.source_id,'revision',t.revision,'kind',t.kind,'loss4',t.loss4,'recovery4',t.recovery4,'expense_category',t.expense_category,'actor_id',t.actor_id,'occurred_at',t.occurred_at) AS record_json FROM stock_valuation_events t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_segments:'||json_array(t.event_id,t.segment_id) AS record_key,json_object('event_id',t.event_id,'segment_id',t.segment_id,'allocation_id',t.allocation_id,'fate',t.fate,'quantity',t.quantity,'gross4',t.gross4,'coverage4',t.coverage4,'loss4',t.loss4,'recovery4',t.recovery4,'reason',t.reason) AS record_json FROM stock_valuation_segments t
UNION ALL
SELECT t.source_id AS source_id,'stock_valuation_agreements:'||json_array(t.id) AS record_key,json_object('id',t.id,'source_id',t.source_id,'amount4',t.amount4,'targets_json',t.targets_json,'proof',t.proof) AS record_json FROM stock_valuation_agreements t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_acceptances:'||json_array(t.event_id,t.target_segment_id) AS record_key,json_object('event_id',t.event_id,'agreement_id',t.agreement_id,'target_segment_id',t.target_segment_id,'amount4',t.amount4,'funding_event_id',t.funding_event_id) AS record_json FROM stock_valuation_acceptances t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_receipts:'||json_array(t.request_id) AS record_key,json_object('request_id',t.request_id,'event_id',t.event_id,'actor_id',t.actor_id,'request_digest',t.request_digest,'request_json',t.request_json,'response_json',t.response_json) AS record_json FROM stock_valuation_receipts t
UNION ALL
SELECT t.source_id AS source_id,'stock_valuation_events_v4:'||json_array(t.id) AS record_key,json_object('id',t.id,'source_id',t.source_id,'revision',t.revision,'kind',t.kind,'loss4',t.loss4,'recovery4',t.recovery4,'expense_category',t.expense_category,'actor_id',t.actor_id,'occurred_at',t.occurred_at,'consumed_cost4',t.consumed_cost4,'consumed_recovery4',t.consumed_recovery4) AS record_json FROM stock_valuation_events_v4 t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_segments_v4:'||json_array(t.event_id,t.segment_id) AS record_key,json_object('event_id',t.event_id,'segment_id',t.segment_id,'allocation_id',t.allocation_id,'fate',t.fate,'quantity',t.quantity,'gross4',t.gross4,'coverage4',t.coverage4,'loss4',t.loss4,'recovery4',t.recovery4,'reason',t.reason,'consumption_id',t.consumption_id,'consumed_cost4',t.consumed_cost4,'consumed_recovery4',t.consumed_recovery4) AS record_json FROM stock_valuation_segments_v4 t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_acceptances_v4:'||json_array(t.event_id,t.target_segment_id) AS record_key,json_object('event_id',t.event_id,'agreement_id',t.agreement_id,'target_segment_id',t.target_segment_id,'amount4',t.amount4,'funding_event_id',t.funding_event_id) AS record_json FROM stock_valuation_acceptances_v4 t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_receipts_v4:'||json_array(t.request_id) AS record_key,json_object('request_id',t.request_id,'event_id',t.event_id,'actor_id',t.actor_id,'request_digest',t.request_digest,'request_json',t.request_json,'response_json',t.response_json) AS record_json FROM stock_valuation_receipts_v4 t
UNION ALL
SELECT t.source_id AS source_id,'stock_valuation_sale_links:'||json_array(t.id) AS record_key,json_object('id',t.id,'source_id',t.source_id,'original_event_id',t.original_event_id,'segment_id',t.segment_id,'sale_id',t.sale_id,'sale_item_id',t.sale_item_id,'sale_allocation_id',t.sale_allocation_id,'quantity',t.quantity,'sale_request_id',t.sale_request_id,'sale_line_key',t.sale_line_key,'sale_intent_json',t.sale_intent_json) AS record_json FROM stock_valuation_sale_links t
UNION ALL
SELECT (SELECT source_id FROM stock_valuation_history_events WHERE id=t.event_id) AS source_id,'stock_valuation_sale_movements:'||json_array(t.event_id) AS record_key,json_object('event_id',t.event_id,'consumption_id',t.consumption_id,'movement_id',t.movement_id,'movement_json',t.movement_json) AS record_json FROM stock_valuation_sale_movements t;
CREATE TRIGGER stock_epoch_verified_member_exact BEFORE INSERT ON stock_epoch_verified_members WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_verifications v JOIN stock_epoch_prefix_records r ON r.source_id=v.source_id WHERE v.id=NEW.verification_id AND r.record_key=NEW.record_key AND r.record_json=NEW.record_json) BEGIN SELECT RAISE(ABORT,'epoch prefix member changed'); END;
CREATE TRIGGER stock_epoch_checkpoint_complete BEFORE INSERT ON stock_epoch_checkpoints WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_verifications v WHERE v.id=NEW.verification_id AND v.source_id=NEW.source_id AND v.head_event_id=NEW.head_event_id AND v.head_revision=NEW.head_revision AND v.dataset_generation=NEW.dataset_generation AND v.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) AND v.head_revision=(SELECT MAX(revision) FROM stock_epoch_event_registry WHERE source_id=v.source_id) AND v.funding_generation=(SELECT MAX(generation) FROM stock_funding_events WHERE source_id=v.source_id) AND v.member_count=(SELECT COUNT(*) FROM stock_epoch_prefix_records WHERE source_id=v.source_id) AND v.member_count=(SELECT COUNT(*) FROM stock_epoch_verified_members WHERE verification_id=v.id) AND NOT EXISTS(SELECT 1 FROM stock_epoch_prefix_records r WHERE r.source_id=v.source_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_verified_members m WHERE m.verification_id=v.id AND m.record_key=r.record_key AND m.record_json=r.record_json))) BEGIN SELECT RAISE(ABORT,'epoch prefix publication incomplete'); END;
CREATE TRIGGER stock_epoch_adoption_checkpoint BEFORE INSERT ON stock_epoch_adoptions WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_checkpoints c JOIN stock_epoch_operation_sources m ON m.source_id=c.source_id WHERE c.id=NEW.checkpoint_id AND c.source_id=NEW.source_id AND c.head_event_id=NEW.previous_event_id AND c.head_revision=NEW.previous_revision AND c.dataset_generation=NEW.dataset_generation AND m.operation_id=NEW.operation_id AND m.expected_revision=NEW.previous_revision AND m.expected_funding_generation=NEW.funding_generation AND NEW.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1)) BEGIN SELECT RAISE(ABORT,'epoch adoption preimage'); END;
DROP VIEW stock_funding_dependencies;
CREATE VIEW stock_funding_dependencies AS SELECT id AS source_id,movement_id,batch_id,product_id,branch_id,supplier_id FROM stock_epoch_sources;
CREATE VIEW stock_epoch_current_epochs AS SELECT e.* FROM stock_epoch_epochs e JOIN stock_epoch_publications p ON p.operation_id=e.operation_id WHERE NOT EXISTS(SELECT 1 FROM stock_epoch_epochs n JOIN stock_epoch_publications np ON np.operation_id=n.operation_id WHERE n.sale_item_id=e.sale_item_id AND n.generation>e.generation);
CREATE VIEW stock_epoch_current_costs AS SELECT l.sale_item_id,1 AS managed,l.original_quantity AS quantity,e.target_quantity AS active_quantity,COALESCE(SUM(a.cost4),0) AS cost4,COALESCE(SUM((SELECT SUM(c.recovery_delta4) FROM stock_epoch_assignment_changes c JOIN stock_epoch_events v ON v.id=c.event_id JOIN stock_epoch_publications p ON p.operation_id=v.operation_id WHERE c.assignment_id=a.id)),0) AS recovery4 FROM stock_epoch_lines l JOIN stock_epoch_current_epochs e ON e.sale_item_id=l.sale_item_id LEFT JOIN stock_epoch_assignments a ON a.epoch_id=e.id GROUP BY l.sale_item_id;
CREATE VIEW stock_epoch_sale_activity AS SELECT i.sale_id,e.sale_item_id,v.source_id,v.id AS event_id,v.kind,v.occurred_at,SUM(c.cost_delta4) AS consumed_cost4,SUM(c.recovery_delta4) AS consumed_recovery4 FROM stock_epoch_assignment_changes c JOIN stock_epoch_assignments a ON a.id=c.assignment_id JOIN stock_epoch_epochs e ON e.id=a.epoch_id JOIN sale_items i ON i.id=e.sale_item_id JOIN stock_epoch_events v ON v.id=c.event_id JOIN stock_epoch_publications p ON p.operation_id=v.operation_id GROUP BY e.sale_item_id,v.id;
CREATE VIEW stock_epoch_history_events AS SELECT * FROM stock_valuation_history_events UNION ALL SELECT id,source_id,revision,kind,loss4,recovery4,expense_category,actor_id,occurred_at,consumed_cost4,consumed_recovery4,5 AS schema_version FROM stock_epoch_events;
CREATE VIEW stock_epoch_latest AS SELECT e.* FROM stock_epoch_history_events e WHERE NOT EXISTS(SELECT 1 FROM stock_epoch_event_registry n WHERE n.source_id=e.source_id AND n.revision>e.revision);
CREATE TRIGGER stock_epoch_publications_no_replace BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE (NEW.operation_id IS NOT NULL AND operation_id IS NEW.operation_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_publications_no_update BEFORE UPDATE ON stock_epoch_publications BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_publications_no_delete BEFORE DELETE ON stock_epoch_publications BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_sources_no_replace BEFORE INSERT ON stock_epoch_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_sources WHERE (NEW.movement_id IS NOT NULL AND movement_id IS NEW.movement_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_sources_no_update BEFORE UPDATE ON stock_epoch_sources BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_sources_no_delete BEFORE DELETE ON stock_epoch_sources BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_event_registry_no_replace BEFORE INSERT ON stock_epoch_event_registry WHEN EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.revision IS NOT NULL AND revision IS NEW.revision) OR (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_event_registry_no_update BEFORE UPDATE ON stock_epoch_event_registry BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_event_registry_no_delete BEFORE DELETE ON stock_epoch_event_registry BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_request_registry_no_replace BEFORE INSERT ON stock_epoch_request_registry WHEN EXISTS(SELECT 1 FROM stock_epoch_request_registry WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_request_registry_no_update BEFORE UPDATE ON stock_epoch_request_registry BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_request_registry_no_delete BEFORE DELETE ON stock_epoch_request_registry BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_dataset_no_replace BEFORE INSERT ON stock_epoch_dataset WHEN EXISTS(SELECT 1 FROM stock_epoch_dataset WHERE (NEW.singleton IS NOT NULL AND singleton IS NEW.singleton)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_operations_no_replace BEFORE INSERT ON stock_epoch_operations WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_operations_no_update BEFORE UPDATE ON stock_epoch_operations BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_operations_no_delete BEFORE DELETE ON stock_epoch_operations BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_operation_sources_no_replace BEFORE INSERT ON stock_epoch_operation_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_operation_sources WHERE (NEW.operation_id IS NOT NULL AND operation_id IS NEW.operation_id AND NEW.source_id IS NOT NULL AND source_id IS NEW.source_id) OR (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_operation_sources_no_update BEFORE UPDATE ON stock_epoch_operation_sources BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_operation_sources_no_delete BEFORE DELETE ON stock_epoch_operation_sources BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_events_no_replace BEFORE INSERT ON stock_epoch_events WHEN EXISTS(SELECT 1 FROM stock_epoch_events WHERE (NEW.operation_id IS NOT NULL AND operation_id IS NEW.operation_id AND NEW.source_id IS NOT NULL AND source_id IS NEW.source_id) OR (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.revision IS NOT NULL AND revision IS NEW.revision) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_events_no_update BEFORE UPDATE ON stock_epoch_events BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_events_no_delete BEFORE DELETE ON stock_epoch_events BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_segments_no_replace BEFORE INSERT ON stock_epoch_segments WHEN EXISTS(SELECT 1 FROM stock_epoch_segments WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id AND NEW.segment_id IS NOT NULL AND segment_id IS NEW.segment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_segments_no_update BEFORE UPDATE ON stock_epoch_segments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_segments_no_delete BEFORE DELETE ON stock_epoch_segments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_receipts_no_replace BEFORE INSERT ON stock_epoch_receipts WHEN EXISTS(SELECT 1 FROM stock_epoch_receipts WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id) OR (NEW.request_id IS NOT NULL AND request_id IS NEW.request_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_receipts_no_update BEFORE UPDATE ON stock_epoch_receipts BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_receipts_no_delete BEFORE DELETE ON stock_epoch_receipts BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_lines_no_replace BEFORE INSERT ON stock_epoch_lines WHEN EXISTS(SELECT 1 FROM stock_epoch_lines WHERE (NEW.sale_request_id IS NOT NULL AND sale_request_id IS NEW.sale_request_id AND NEW.line_key IS NOT NULL AND line_key IS NEW.line_key) OR (NEW.sale_item_id IS NOT NULL AND sale_item_id IS NEW.sale_item_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_lines_no_update BEFORE UPDATE ON stock_epoch_lines BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_lines_no_delete BEFORE DELETE ON stock_epoch_lines BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_line_allocations_no_replace BEFORE INSERT ON stock_epoch_line_allocations WHEN EXISTS(SELECT 1 FROM stock_epoch_line_allocations WHERE (NEW.sale_item_id IS NOT NULL AND sale_item_id IS NEW.sale_item_id AND NEW.allocation_id IS NOT NULL AND allocation_id IS NEW.allocation_id) OR (NEW.allocation_id IS NOT NULL AND allocation_id IS NEW.allocation_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_line_allocations_no_update BEFORE UPDATE ON stock_epoch_line_allocations BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_line_allocations_no_delete BEFORE DELETE ON stock_epoch_line_allocations BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_epochs_no_replace BEFORE INSERT ON stock_epoch_epochs WHEN EXISTS(SELECT 1 FROM stock_epoch_epochs WHERE (NEW.operation_id IS NOT NULL AND operation_id IS NEW.operation_id AND NEW.sale_item_id IS NOT NULL AND sale_item_id IS NEW.sale_item_id) OR (NEW.sale_item_id IS NOT NULL AND sale_item_id IS NEW.sale_item_id AND NEW.generation IS NOT NULL AND generation IS NEW.generation) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_epochs_no_update BEFORE UPDATE ON stock_epoch_epochs BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_epochs_no_delete BEFORE DELETE ON stock_epoch_epochs BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_assignments_no_replace BEFORE INSERT ON stock_epoch_assignments WHEN EXISTS(SELECT 1 FROM stock_epoch_assignments WHERE (NEW.epoch_id IS NOT NULL AND epoch_id IS NEW.epoch_id AND NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.segment_id IS NOT NULL AND segment_id IS NEW.segment_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_assignments_no_update BEFORE UPDATE ON stock_epoch_assignments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_assignments_no_delete BEFORE DELETE ON stock_epoch_assignments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_assignment_changes_no_replace BEFORE INSERT ON stock_epoch_assignment_changes WHEN EXISTS(SELECT 1 FROM stock_epoch_assignment_changes WHERE (NEW.event_id IS NOT NULL AND event_id IS NEW.event_id AND NEW.assignment_id IS NOT NULL AND assignment_id IS NEW.assignment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_assignment_changes_no_update BEFORE UPDATE ON stock_epoch_assignment_changes BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_assignment_changes_no_delete BEFORE DELETE ON stock_epoch_assignment_changes BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_provenance_no_replace BEFORE INSERT ON stock_epoch_provenance WHEN EXISTS(SELECT 1 FROM stock_epoch_provenance WHERE (NEW.sale_item_id IS NOT NULL AND sale_item_id IS NEW.sale_item_id AND NEW.source_id IS NOT NULL AND source_id IS NEW.source_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_provenance_no_update BEFORE UPDATE ON stock_epoch_provenance BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_provenance_no_delete BEFORE DELETE ON stock_epoch_provenance BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_effects_no_replace BEFORE INSERT ON stock_epoch_effects WHEN EXISTS(SELECT 1 FROM stock_epoch_effects WHERE (NEW.operation_id IS NOT NULL AND operation_id IS NEW.operation_id AND NEW.allocation_id IS NOT NULL AND allocation_id IS NEW.allocation_id) OR (NEW.movement_id IS NOT NULL AND movement_id IS NEW.movement_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_effects_no_update BEFORE UPDATE ON stock_epoch_effects BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_effects_no_delete BEFORE DELETE ON stock_epoch_effects BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_adoptions_no_replace BEFORE INSERT ON stock_epoch_adoptions WHEN EXISTS(SELECT 1 FROM stock_epoch_adoptions WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_adoptions_no_update BEFORE UPDATE ON stock_epoch_adoptions BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_adoptions_no_delete BEFORE DELETE ON stock_epoch_adoptions BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_adoption_lines_no_replace BEFORE INSERT ON stock_epoch_adoption_lines WHEN EXISTS(SELECT 1 FROM stock_epoch_adoption_lines WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.allocation_id IS NOT NULL AND allocation_id IS NEW.allocation_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_adoption_lines_no_update BEFORE UPDATE ON stock_epoch_adoption_lines BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_adoption_lines_no_delete BEFORE DELETE ON stock_epoch_adoption_lines BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_adoption_fragments_no_replace BEFORE INSERT ON stock_epoch_adoption_fragments WHEN EXISTS(SELECT 1 FROM stock_epoch_adoption_fragments WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.segment_id IS NOT NULL AND segment_id IS NEW.segment_id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_adoption_fragments_no_update BEFORE UPDATE ON stock_epoch_adoption_fragments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_adoption_fragments_no_delete BEFORE DELETE ON stock_epoch_adoption_fragments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_verifications_no_replace BEFORE INSERT ON stock_epoch_verifications WHEN EXISTS(SELECT 1 FROM stock_epoch_verifications WHERE (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_verifications_no_update BEFORE UPDATE ON stock_epoch_verifications BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_verifications_no_delete BEFORE DELETE ON stock_epoch_verifications BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_verified_members_no_replace BEFORE INSERT ON stock_epoch_verified_members WHEN EXISTS(SELECT 1 FROM stock_epoch_verified_members WHERE (NEW.verification_id IS NOT NULL AND verification_id IS NEW.verification_id AND NEW.record_key IS NOT NULL AND record_key IS NEW.record_key)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_verified_members_no_update BEFORE UPDATE ON stock_epoch_verified_members BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_verified_members_no_delete BEFORE DELETE ON stock_epoch_verified_members BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_checkpoints_no_replace BEFORE INSERT ON stock_epoch_checkpoints WHEN EXISTS(SELECT 1 FROM stock_epoch_checkpoints WHERE (NEW.source_id IS NOT NULL AND source_id IS NEW.source_id AND NEW.head_revision IS NOT NULL AND head_revision IS NEW.head_revision) OR (NEW.verification_id IS NOT NULL AND verification_id IS NEW.verification_id) OR (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_checkpoints_no_update BEFORE UPDATE ON stock_epoch_checkpoints BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_checkpoints_no_delete BEFORE DELETE ON stock_epoch_checkpoints BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_restore_runs_no_replace BEFORE INSERT ON stock_epoch_restore_runs WHEN EXISTS(SELECT 1 FROM stock_epoch_restore_runs WHERE (NEW.id IS NOT NULL AND id IS NEW.id)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_restore_runs_no_update BEFORE UPDATE ON stock_epoch_restore_runs BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_restore_runs_no_delete BEFORE DELETE ON stock_epoch_restore_runs BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_restore_members_no_replace BEFORE INSERT ON stock_epoch_restore_members WHEN EXISTS(SELECT 1 FROM stock_epoch_restore_members WHERE (NEW.run_id IS NOT NULL AND run_id IS NEW.run_id AND NEW.table_name IS NOT NULL AND table_name IS NEW.table_name AND NEW.row_key IS NOT NULL AND row_key IS NEW.row_key)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_restore_members_no_update BEFORE UPDATE ON stock_epoch_restore_members BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_restore_members_no_delete BEFORE DELETE ON stock_epoch_restore_members BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_restore_verifications_no_replace BEFORE INSERT ON stock_epoch_restore_verifications WHEN EXISTS(SELECT 1 FROM stock_epoch_restore_verifications WHERE (NEW.run_id IS NOT NULL AND run_id IS NEW.run_id AND NEW.table_name IS NOT NULL AND table_name IS NEW.table_name)) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_restore_verifications_no_update BEFORE UPDATE ON stock_epoch_restore_verifications BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
CREATE TRIGGER stock_epoch_restore_verifications_no_delete BEFORE DELETE ON stock_epoch_restore_verifications BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;
