ALTER TABLE stock_epoch_operations ADD COLUMN protocol INTEGER NOT NULL DEFAULT 1 CHECK(protocol IN (1,2));
ALTER TABLE stock_epoch_operations ADD COLUMN ordinary_id TEXT;
ALTER TABLE stock_epoch_operations ADD COLUMN role_id INTEGER;
ALTER TABLE stock_epoch_operations ADD COLUMN role_code TEXT;
ALTER TABLE stock_epoch_operations ADD COLUMN role_permissions TEXT;
ALTER TABLE stock_epoch_operations ADD COLUMN actor_name TEXT;
ALTER TABLE stock_epoch_segments ADD COLUMN source_id TEXT REFERENCES stock_epoch_sources(id);
ALTER TABLE stock_epoch_segments ADD COLUMN branch_id INTEGER REFERENCES branches(id);
ALTER TABLE stock_epoch_segments ADD COLUMN parent_segment_id TEXT;
CREATE TABLE stock_epoch_operation_contracts(operation_id TEXT PRIMARY KEY REFERENCES stock_epoch_operations(id),request_digest TEXT NOT NULL,ordinary_receipt_json TEXT NOT NULL CHECK(json_valid(ordinary_receipt_json)),audit_id INTEGER NOT NULL UNIQUE REFERENCES audit_logs(id));
CREATE TABLE stock_epoch_source_states(event_id TEXT PRIMARY KEY REFERENCES stock_epoch_events(id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),funding_generation INTEGER NOT NULL CHECK(typeof(funding_generation)='integer' AND funding_generation>=0),
gross4 INTEGER NOT NULL CHECK(typeof(gross4)='integer' AND gross4 BETWEEN 0 AND 1000000000000000),paid4 INTEGER NOT NULL CHECK(typeof(paid4)='integer' AND paid4 BETWEEN 0 AND 1000000000000000),debt4 INTEGER NOT NULL CHECK(typeof(debt4)='integer' AND debt4 BETWEEN 0 AND 1000000000000000),credit4 INTEGER NOT NULL CHECK(typeof(credit4)='integer' AND credit4 BETWEEN 0 AND 1000000000000000),asset4 INTEGER NOT NULL CHECK(typeof(asset4)='integer' AND asset4 BETWEEN 0 AND 1000000000000000),cash_in4 INTEGER NOT NULL CHECK(typeof(cash_in4)='integer' AND cash_in4 BETWEEN 0 AND 1000000000000000),cash_out4 INTEGER NOT NULL CHECK(typeof(cash_out4)='integer' AND cash_out4 BETWEEN 0 AND 1000000000000000),shipping4 INTEGER NOT NULL CHECK(typeof(shipping4)='integer' AND shipping4 BETWEEN 0 AND 1000000000000000),
sellable_quantity TEXT NOT NULL CHECK(CAST(sellable_quantity AS REAL)>=0),held_quantity TEXT NOT NULL CHECK(CAST(held_quantity AS REAL)>=0),disposed_quantity TEXT NOT NULL CHECK(CAST(disposed_quantity AS REAL)>=0),consumed_quantity TEXT NOT NULL CHECK(CAST(consumed_quantity AS REAL)>=0),
sellable_net4 INTEGER NOT NULL CHECK(typeof(sellable_net4)='integer' AND sellable_net4 BETWEEN 0 AND 1000000000000000),held_net4 INTEGER NOT NULL CHECK(typeof(held_net4)='integer' AND held_net4 BETWEEN 0 AND 1000000000000000),loss4 INTEGER NOT NULL CHECK(typeof(loss4)='integer' AND loss4 BETWEEN 0 AND 1000000000000000),loss_recovery4 INTEGER NOT NULL CHECK(typeof(loss_recovery4)='integer' AND loss_recovery4 BETWEEN 0 AND 1000000000000000),consumed_cost4 INTEGER NOT NULL CHECK(typeof(consumed_cost4)='integer' AND consumed_cost4 BETWEEN 0 AND 1000000000000000),consumed_recovery4 INTEGER NOT NULL CHECK(typeof(consumed_recovery4)='integer' AND consumed_recovery4 BETWEEN 0 AND 1000000000000000),pending4 INTEGER NOT NULL CHECK(typeof(pending4)='integer' AND pending4 BETWEEN 0 AND 1000000000000000),
CHECK(gross4=paid4+debt4+credit4-asset4-cash_in4),CHECK(gross4=sellable_net4+held_net4+loss4-loss_recovery4+consumed_cost4-consumed_recovery4+credit4),CHECK(loss_recovery4<=loss4 AND consumed_recovery4<=consumed_cost4 AND credit4<=gross4));
CREATE TABLE stock_epoch_source_heads(source_id TEXT PRIMARY KEY REFERENCES stock_epoch_sources(id),event_id TEXT NOT NULL UNIQUE REFERENCES stock_epoch_source_states(event_id),revision INTEGER NOT NULL,funding_generation INTEGER NOT NULL,dataset_generation INTEGER NOT NULL);
CREATE TABLE stock_epoch_current_fragments(source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),segment_id TEXT NOT NULL,event_id TEXT NOT NULL,allocation_id TEXT NOT NULL,branch_id INTEGER NOT NULL REFERENCES branches(id),fate TEXT NOT NULL,assignment_id TEXT UNIQUE REFERENCES stock_epoch_assignments(id),PRIMARY KEY(source_id,segment_id),FOREIGN KEY(event_id,segment_id) REFERENCES stock_epoch_segments(event_id,segment_id));
CREATE INDEX stock_epoch_current_eligible ON stock_epoch_current_fragments(source_id,branch_id,segment_id) WHERE fate='sellable';
CREATE INDEX stock_epoch_current_lineage ON stock_epoch_current_fragments(source_id,allocation_id,segment_id);
CREATE TABLE stock_epoch_lot_heads(batch_id INTEGER NOT NULL REFERENCES product_batches(id),branch_id INTEGER NOT NULL REFERENCES branches(id),product_id INTEGER NOT NULL REFERENCES products(id),operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),quantity TEXT NOT NULL,received_quantity TEXT NOT NULL,received_gross4 INTEGER NOT NULL CHECK(typeof(received_gross4)='integer' AND received_gross4 BETWEEN 0 AND 1000000000000000),dataset_generation INTEGER NOT NULL,PRIMARY KEY(batch_id,branch_id));
CREATE TABLE stock_epoch_lot_effects(operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),line_id TEXT NOT NULL,product_id INTEGER NOT NULL REFERENCES products(id),branch_id INTEGER NOT NULL REFERENCES branches(id),batch_id INTEGER REFERENCES product_batches(id),batch_key TEXT NOT NULL,previous_operation_id TEXT REFERENCES stock_epoch_operations(id),quantity_before TEXT NOT NULL,quantity_after TEXT NOT NULL,received_before TEXT NOT NULL,received_after TEXT NOT NULL,gross_before4 INTEGER NOT NULL CHECK(typeof(gross_before4)='integer' AND gross_before4 BETWEEN 0 AND 1000000000000000),gross_after4 INTEGER NOT NULL CHECK(typeof(gross_after4)='integer' AND gross_after4 BETWEEN 0 AND 1000000000000000),branch_before REAL NOT NULL,branch_after REAL NOT NULL,product_before REAL NOT NULL,product_after REAL NOT NULL,PRIMARY KEY(operation_id,line_id),UNIQUE(operation_id,product_id,branch_id,batch_key));

CREATE TRIGGER stock_epoch_protocol_actor BEFORE INSERT ON stock_epoch_operations WHEN NEW.protocol=2 AND (NEW.kind NOT IN ('stock_session','hold','repair') OR NEW.ordinary_id IS NULL OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN roles r ON r.id=u.role_id WHERE u.id=NEW.actor_id AND u.is_active=1 AND u.deleted_at IS NULL AND u.permissions IS NEW.actor_permissions AND u.role_id IS NEW.role_id AND r.code IS NEW.role_code AND r.permissions IS NEW.role_permissions) OR NEW.dataset_generation<>(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) OR EXISTS(SELECT 1 FROM system_flags WHERE key='maintenance')) BEGIN SELECT RAISE(ABORT,'epoch operation authority'); END;

CREATE TRIGGER stock_epoch_lot_effect_preimage BEFORE INSERT ON stock_epoch_lot_effects WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN products p ON p.id=NEW.product_id JOIN branch_stock b ON b.product_id=p.id AND b.branch_id=NEW.branch_id WHERE o.id=NEW.operation_id AND o.protocol=2 AND o.kind='stock_session' AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications x WHERE x.operation_id=o.id) AND p.stock_quantity=NEW.product_before AND b.quantity=NEW.branch_before AND o.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) AND ((NEW.batch_id IS NULL AND NEW.previous_operation_id IS NULL AND NEW.quantity_before='0' AND NEW.received_before='0' AND NEW.gross_before4=0 AND NOT EXISTS(SELECT 1 FROM product_batches z WHERE z.variant_product_id=NEW.product_id AND z.batch_key=NEW.batch_key)) OR EXISTS(SELECT 1 FROM stock_epoch_lot_heads h JOIN product_batches pb ON pb.id=h.batch_id JOIN branch_batch_stock bs ON bs.batch_id=pb.id AND bs.branch_id=h.branch_id WHERE h.batch_id=NEW.batch_id AND h.branch_id=NEW.branch_id AND h.product_id=NEW.product_id AND h.operation_id=NEW.previous_operation_id AND pb.batch_key=NEW.batch_key AND h.quantity=NEW.quantity_before AND h.received_quantity=NEW.received_before AND h.received_gross4=NEW.gross_before4 AND bs.quantity=CAST(h.quantity AS REAL) AND pb.received_quantity=CAST(h.received_quantity AS REAL) AND pb.received_cost_usd=h.received_gross4/10000.0))) BEGIN SELECT RAISE(ABORT,'epoch lot preimage'); END;

CREATE VIEW stock_epoch_receipt_members AS SELECT o.id AS operation_id,o.ordinary_id,o.actor_id,m.line_id,m.movement_id,m.product_id,m.branch_id,m.batch_id,m.quantity,m.unit_cost_usd,json_extract(j.value,'$.payment_status') AS payment_status,json_extract(j.value,'$.supplier_id') AS supplier_id,json_extract(j.value,'$.quantity') AS request_quantity,json_extract(j.value,'$.unit_cost_usd') AS request_unit_cost FROM stock_epoch_operations o JOIN stock_session_operations s ON s.id=o.ordinary_id JOIN stock_session_members m ON m.operation_id=s.id JOIN json_each(s.request_json,'$.items') j ON json_extract(j.value,'$.line_id')=m.line_id WHERE o.protocol=2 AND o.kind='stock_session' AND m.quantity>0;

CREATE TRIGGER stock_epoch_source_receipt BEFORE INSERT ON stock_epoch_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_operations o WHERE o.id=NEW.admission_operation_id AND o.protocol=2) AND NOT EXISTS(SELECT 1 FROM stock_epoch_receipt_members m JOIN stock_session_operations p ON p.id=m.ordinary_id JOIN inventory_movements v ON v.id=m.movement_id JOIN suppliers supplier ON supplier.id=m.supplier_id WHERE m.operation_id=NEW.admission_operation_id AND m.movement_id=NEW.movement_id AND m.product_id=NEW.product_id AND m.branch_id=NEW.branch_id AND m.batch_id=NEW.batch_id AND m.supplier_id=NEW.supplier_id AND m.quantity=m.request_quantity AND m.quantity=CAST(NEW.quantity AS REAL) AND m.unit_cost_usd=m.request_unit_cost AND v.product_id=m.product_id AND v.batch_id=m.batch_id AND v.branch_id=m.branch_id AND v.quantity=m.quantity AND COALESCE(v.free_quantity,0)=0 AND NEW.free_quantity='0' AND v.movement_type='add' AND v.total_cost_usd=NEW.gross4/10000.0 AND typeof(NEW.opening_paid4)='integer' AND typeof(NEW.opening_debt4)='integer' AND NEW.opening_paid4=CASE m.payment_status WHEN 'paid' THEN NEW.gross4 ELSE 0 END AND NEW.opening_debt4=CASE m.payment_status WHEN 'credit' THEN NEW.gross4 ELSE 0 END AND m.payment_status IN ('paid','credit') AND NEW.invoice_id IS NULL AND NEW.actor_id=m.actor_id AND p.actor_id=m.actor_id AND p.request_json=(SELECT request_json FROM stock_epoch_operations WHERE id=m.operation_id) AND NOT EXISTS(SELECT 1 FROM supplier_invoices i WHERE (i.supplier_id=m.supplier_id OR i.supplier_id IS NULL) AND (i.branch_id=m.branch_id OR i.branch_id IS NULL))) BEGIN SELECT RAISE(ABORT,'epoch receipt source mismatch'); END;

CREATE TRIGGER stock_epoch_state_identity BEFORE INSERT ON stock_epoch_source_states WHEN (NOT EXISTS(SELECT 1 FROM stock_epoch_events e JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_sources s ON s.id=e.source_id WHERE e.id=NEW.event_id AND e.source_id=NEW.source_id AND e.funding_generation=NEW.funding_generation AND o.protocol=2 AND e.kind='admit' AND e.revision=0 AND NEW.gross4=s.gross4 AND NEW.paid4=s.opening_paid4 AND NEW.debt4=s.opening_debt4 AND NEW.credit4=0 AND NEW.asset4=0 AND NEW.cash_in4=0 AND NEW.cash_out4=0 AND NEW.shipping4=0 AND NEW.pending4=0 AND NEW.sellable_quantity=s.quantity AND NEW.held_quantity='0' AND NEW.disposed_quantity='0' AND NEW.consumed_quantity='0' AND NEW.sellable_net4=s.gross4 AND NEW.held_net4=0 AND NEW.loss4=0 AND NEW.loss_recovery4=0 AND NEW.consumed_cost4=0 AND NEW.consumed_recovery4=0 AND e.funding_json=json_object('gross4',NEW.gross4,'paid4',NEW.paid4,'debt4',NEW.debt4,'credit4',NEW.credit4,'asset4',NEW.asset4,'cash_in4',NEW.cash_in4,'cash_out4',NEW.cash_out4,'shipping4',NEW.shipping4))) AND NOT EXISTS(SELECT 1 FROM stock_epoch_events e JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_commands c ON c.operation_id=o.id JOIN stock_epoch_source_states v ON v.event_id=c.before_event_id WHERE e.id=NEW.event_id AND e.source_id=NEW.source_id AND v.source_id=NEW.source_id AND o.protocol=2 AND o.kind IN ('hold','repair') AND e.kind=o.kind AND NEW.funding_generation=v.funding_generation AND NEW.gross4=v.gross4 AND NEW.paid4=v.paid4 AND NEW.debt4=v.debt4 AND NEW.credit4=v.credit4 AND NEW.asset4=v.asset4 AND NEW.cash_in4=v.cash_in4 AND NEW.cash_out4=v.cash_out4 AND NEW.shipping4=v.shipping4 AND NEW.pending4=v.pending4 AND e.funding_json=(SELECT funding_json FROM stock_epoch_events WHERE id=c.before_event_id)) BEGIN SELECT RAISE(ABORT,'epoch typed source state'); END;

CREATE TRIGGER stock_epoch_source_head_owned BEFORE INSERT ON stock_epoch_source_heads WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_events e JOIN stock_epoch_source_states s ON s.event_id=e.id JOIN stock_epoch_operations o ON o.id=e.operation_id WHERE e.id=NEW.event_id AND e.source_id=NEW.source_id AND s.source_id=NEW.source_id AND e.revision=NEW.revision AND e.funding_generation=NEW.funding_generation AND o.protocol=2 AND o.dataset_generation=NEW.dataset_generation AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch source head unowned'); END;
CREATE TRIGGER stock_epoch_fragment_head_owned BEFORE INSERT ON stock_epoch_current_fragments WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_segments s JOIN stock_epoch_events e ON e.id=s.event_id JOIN stock_epoch_operations o ON o.id=e.operation_id WHERE s.event_id=NEW.event_id AND s.segment_id=NEW.segment_id AND s.source_id=NEW.source_id AND e.source_id=NEW.source_id AND s.allocation_id=NEW.allocation_id AND s.branch_id=NEW.branch_id AND s.fate=NEW.fate AND s.consumption_id IS NEW.assignment_id AND o.protocol=2 AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch fragment head unowned'); END;

CREATE TRIGGER stock_epoch_lot_head_insert BEFORE INSERT ON stock_epoch_lot_heads WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_lot_effects f JOIN stock_epoch_operations o ON o.id=f.operation_id JOIN stock_session_members m ON m.operation_id=o.ordinary_id AND m.line_id=f.line_id WHERE f.operation_id=NEW.operation_id AND m.batch_id=NEW.batch_id AND f.product_id=NEW.product_id AND f.branch_id=NEW.branch_id AND f.quantity_after=NEW.quantity AND f.received_after=NEW.received_quantity AND f.gross_after4=NEW.received_gross4 AND o.dataset_generation=NEW.dataset_generation AND o.protocol=2 AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch lot head unowned'); END;
CREATE TRIGGER stock_epoch_lot_head_update BEFORE UPDATE ON stock_epoch_lot_heads WHEN (NEW.batch_id IS NOT OLD.batch_id OR NEW.branch_id IS NOT OLD.branch_id OR NEW.product_id IS NOT OLD.product_id OR NOT EXISTS(SELECT 1 FROM stock_epoch_lot_effects f JOIN stock_epoch_operations o ON o.id=f.operation_id JOIN stock_session_members m ON m.operation_id=o.ordinary_id AND m.line_id=f.line_id WHERE f.operation_id=NEW.operation_id AND m.batch_id=NEW.batch_id AND f.product_id=NEW.product_id AND f.branch_id=NEW.branch_id AND f.quantity_after=NEW.quantity AND f.received_after=NEW.received_quantity AND f.gross_after4=NEW.received_gross4 AND o.dataset_generation=NEW.dataset_generation AND o.protocol=2 AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) OR NOT EXISTS(SELECT 1 FROM stock_epoch_lot_effects f WHERE f.operation_id=NEW.operation_id AND f.previous_operation_id=OLD.operation_id AND f.quantity_before=OLD.quantity AND f.received_before=OLD.received_quantity AND f.gross_before4=OLD.received_gross4 AND f.branch_id=OLD.branch_id AND f.product_id=OLD.product_id AND f.batch_id=OLD.batch_id)) AND NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_operations o ON o.id=c.operation_id WHERE c.operation_id=NEW.operation_id AND o.protocol=2 AND o.kind IN ('hold','repair') AND c.batch_id=OLD.batch_id AND c.branch_id=OLD.branch_id AND c.product_id=OLD.product_id AND c.previous_lot_operation_id=OLD.operation_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.product_id=OLD.product_id AND CAST(OLD.quantity AS REAL)=CAST(c.quantity_before AS REAL) AND CAST(NEW.quantity AS REAL)=CAST(c.quantity_after AS REAL) AND NEW.received_quantity=OLD.received_quantity AND NEW.received_gross4=OLD.received_gross4 AND NEW.dataset_generation=OLD.dataset_generation AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch lot head preimage'); END;
CREATE TRIGGER stock_epoch_lot_head_delete BEFORE DELETE ON stock_epoch_lot_heads BEGIN SELECT RAISE(ABORT,'epoch lot head immutable'); END;

DROP TRIGGER stock_lifecycle_batch_update;
CREATE TRIGGER stock_lifecycle_batch_update BEFORE UPDATE ON product_batches
 WHEN EXISTS(SELECT 1 FROM stock_lifecycle_dependencies WHERE batch_id=OLD.id) AND (NEW.id IS NOT OLD.id OR NEW.variant_product_id IS NOT OLD.variant_product_id OR NEW.received_at IS NOT OLD.received_at OR NEW.received_quantity IS NOT OLD.received_quantity OR NEW.received_cost_usd IS NOT OLD.received_cost_usd OR NEW.received_branch_id IS NOT OLD.received_branch_id OR NEW.supplier_id IS NOT OLD.supplier_id OR NEW.supplier_name IS NOT OLD.supplier_name OR NEW.payment_status IS NOT OLD.payment_status OR NEW.credit_due_date IS NOT OLD.credit_due_date OR NEW.unit_cost_usd IS NOT OLD.unit_cost_usd OR NEW.is_active IS NOT OLD.is_active OR NEW.batch_key IS NOT OLD.batch_key OR NEW.lot_code IS NOT OLD.lot_code)
 AND NOT EXISTS(SELECT 1 FROM stock_epoch_lot_effects f JOIN stock_epoch_operations o ON o.id=f.operation_id LEFT JOIN stock_epoch_publications p ON p.operation_id=o.id WHERE o.protocol=2 AND o.kind='stock_session' AND p.operation_id IS NULL AND f.batch_id=OLD.id AND f.product_id=OLD.variant_product_id AND CAST(f.received_before AS REAL)=OLD.received_quantity AND CAST(f.received_after AS REAL)=NEW.received_quantity AND f.gross_before4/10000.0=OLD.received_cost_usd AND f.gross_after4/10000.0=NEW.received_cost_usd AND NEW.id IS OLD.id AND NEW.variant_product_id IS OLD.variant_product_id AND NEW.received_at IS OLD.received_at AND NEW.received_branch_id IS OLD.received_branch_id AND NEW.supplier_id IS OLD.supplier_id AND NEW.supplier_name IS OLD.supplier_name AND NEW.payment_status IS OLD.payment_status AND NEW.credit_due_date IS OLD.credit_due_date AND NEW.unit_cost_usd IS OLD.unit_cost_usd AND NEW.is_active IS OLD.is_active AND NEW.batch_key IS OLD.batch_key AND NEW.lot_code IS OLD.lot_code)
 BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;

DROP TRIGGER stock_lifecycle_lot_update;
CREATE TRIGGER stock_lifecycle_lot_update BEFORE UPDATE ON branch_batch_stock
 WHEN EXISTS(SELECT 1 FROM stock_lifecycle_dependencies WHERE batch_id=OLD.batch_id) AND (NEW.quantity IS NOT OLD.quantity OR NEW.batch_id IS NOT OLD.batch_id OR NEW.branch_id IS NOT OLD.branch_id)
 AND NOT EXISTS(SELECT 1 FROM stock_lifecycle_context x JOIN stock_disposition_guards g ON g.token=x.token WHERE g.valid=1 AND x.batch_id=OLD.batch_id AND x.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.quantity=x.remaining_quantity)
 AND NOT EXISTS(SELECT 1 FROM stock_valuation_context x JOIN stock_valuation_guards g ON g.token=x.token WHERE g.valid=1 AND x.batch_id=OLD.batch_id AND x.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND NEW.quantity=x.remaining_quantity AND ((x.operation_id IS NULL AND NOT EXISTS(SELECT 1 FROM stock_valuation_events_v4 e WHERE e.source_id=x.source_id)) OR EXISTS(SELECT 1 FROM stock_valuation_latest e WHERE e.id=x.operation_id AND e.source_id=x.source_id AND e.schema_version=4 AND (e.kind NOT IN ('consume','restore','reconsume') OR EXISTS(SELECT 1 FROM stock_valuation_sale_operation_context op WHERE op.token=x.token AND op.event_id=e.id AND op.source_id=e.source_id AND op.remaining_quantity=NEW.quantity)))))
 AND NOT EXISTS(SELECT 1 FROM stock_epoch_lot_effects f JOIN stock_epoch_operations o ON o.id=f.operation_id LEFT JOIN stock_epoch_publications p ON p.operation_id=o.id WHERE o.protocol=2 AND o.kind='stock_session' AND p.operation_id IS NULL AND f.batch_id=OLD.batch_id AND f.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND CAST(f.quantity_before AS REAL)=OLD.quantity AND CAST(f.quantity_after AS REAL)=NEW.quantity)
 AND NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_operations o ON o.id=c.operation_id WHERE o.protocol=2 AND o.kind IN ('hold','repair') AND c.batch_id=OLD.batch_id AND c.branch_id=OLD.branch_id AND NEW.batch_id=OLD.batch_id AND NEW.branch_id=OLD.branch_id AND OLD.quantity=CAST(c.quantity_before AS REAL) AND NEW.quantity=CAST(c.quantity_after AS REAL) AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id))
 BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;

DROP TRIGGER stock_lifecycle_lot_insert;
CREATE TRIGGER stock_lifecycle_lot_insert BEFORE INSERT ON branch_batch_stock
 WHEN EXISTS(SELECT 1 FROM stock_lifecycle_dependencies WHERE batch_id=NEW.batch_id)
 AND NOT EXISTS(SELECT 1 FROM branch_batch_stock b JOIN stock_valuation_context c ON c.batch_id=b.batch_id AND c.branch_id=b.branch_id JOIN stock_valuation_guards g ON g.token=c.token AND g.valid=1 JOIN stock_valuation_sale_operation_context op ON op.token=c.token AND op.event_id=c.operation_id JOIN stock_valuation_latest e ON e.id=op.event_id AND e.source_id=op.source_id JOIN stock_valuation_sale_links l ON l.id=op.consumption_id AND l.source_id=op.source_id AND l.sale_allocation_id=op.sale_allocation_id JOIN sale_item_batch_allocations a ON a.id=l.sale_allocation_id JOIN stock_funding_sources f ON f.id=l.source_id WHERE b.batch_id=NEW.batch_id AND b.branch_id=NEW.branch_id AND f.batch_id=b.batch_id AND f.branch_id=b.branch_id AND c.source_id=f.id AND a.batch_id=b.batch_id AND a.branch_id=b.branch_id AND op.kind='restore' AND e.kind='restore' AND e.schema_version=4 AND a.released_quantity=op.released_before AND op.released_before=0 AND op.released_after=a.quantity AND a.quantity=CAST(l.quantity AS REAL) AND NEW.quantity=a.quantity AND b.quantity+NEW.quantity=op.remaining_quantity AND c.remaining_quantity=op.remaining_quantity)
 AND NOT EXISTS(SELECT 1 FROM stock_epoch_lot_effects f JOIN stock_epoch_operations o ON o.id=f.operation_id LEFT JOIN stock_epoch_publications p ON p.operation_id=o.id JOIN branch_batch_stock b ON b.batch_id=f.batch_id AND b.branch_id=f.branch_id WHERE o.protocol=2 AND o.kind='stock_session' AND p.operation_id IS NULL AND f.batch_id=NEW.batch_id AND f.branch_id=NEW.branch_id AND b.quantity=CAST(f.quantity_before AS REAL) AND b.quantity+NEW.quantity=CAST(f.quantity_after AS REAL))
 BEGIN SELECT RAISE(ABORT,'stock_lifecycle_dependency'); END;

DROP TRIGGER stock_valuation_events_epoch_identity;
CREATE TRIGGER stock_valuation_events_epoch_identity BEFORE INSERT ON stock_valuation_events WHEN EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) OR EXISTS(SELECT 1 FROM stock_epoch_adoptions WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'valuation_global_identity_conflict'); END;

DROP TRIGGER stock_valuation_events_v4_epoch_identity;
CREATE TRIGGER stock_valuation_events_v4_epoch_identity BEFORE INSERT ON stock_valuation_events_v4 WHEN EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE event_id=NEW.id OR (source_id=NEW.source_id AND revision=NEW.revision)) OR NEW.revision<>(SELECT COALESCE(MAX(revision)+1,0) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) OR EXISTS(SELECT 1 FROM stock_epoch_adoptions WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'valuation_global_identity_conflict'); END;

CREATE TRIGGER stock_epoch_operation_sources_closed_insert BEFORE INSERT ON stock_epoch_operation_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_events_closed_insert BEFORE INSERT ON stock_epoch_events WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_segments_closed_insert BEFORE INSERT ON stock_epoch_segments WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=(SELECT operation_id FROM stock_epoch_events WHERE id=NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_receipts_closed_insert BEFORE INSERT ON stock_epoch_receipts WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=(SELECT operation_id FROM stock_epoch_events WHERE id=NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_epochs_closed_insert BEFORE INSERT ON stock_epoch_epochs WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_assignments_closed_insert BEFORE INSERT ON stock_epoch_assignments WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=(SELECT operation_id FROM stock_epoch_epochs WHERE id=NEW.epoch_id)) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_assignment_changes_closed_insert BEFORE INSERT ON stock_epoch_assignment_changes WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=(SELECT operation_id FROM stock_epoch_events WHERE id=NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_effects_closed_insert BEFORE INSERT ON stock_epoch_effects WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_adoptions_closed_insert BEFORE INSERT ON stock_epoch_adoptions WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_operation_contracts_closed_insert BEFORE INSERT ON stock_epoch_operation_contracts WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_source_states_closed_insert BEFORE INSERT ON stock_epoch_source_states WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=(SELECT operation_id FROM stock_epoch_events WHERE id=NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_lot_effects_closed_insert BEFORE INSERT ON stock_epoch_lot_effects WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_operation_contracts_no_replace BEFORE INSERT ON stock_epoch_operation_contracts WHEN EXISTS(SELECT 1 FROM stock_epoch_operation_contracts WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;

CREATE TRIGGER stock_epoch_operation_contracts_no_update BEFORE UPDATE ON stock_epoch_operation_contracts BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_operation_contracts_no_delete BEFORE DELETE ON stock_epoch_operation_contracts BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_source_states_no_replace BEFORE INSERT ON stock_epoch_source_states WHEN EXISTS(SELECT 1 FROM stock_epoch_source_states WHERE event_id=NEW.event_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;

CREATE TRIGGER stock_epoch_source_states_no_update BEFORE UPDATE ON stock_epoch_source_states BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_source_states_no_delete BEFORE DELETE ON stock_epoch_source_states BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_source_heads_no_replace BEFORE INSERT ON stock_epoch_source_heads WHEN EXISTS(SELECT 1 FROM stock_epoch_source_heads WHERE source_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;

CREATE TRIGGER stock_epoch_source_heads_no_update BEFORE UPDATE ON stock_epoch_source_heads BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_source_heads_no_delete BEFORE DELETE ON stock_epoch_source_heads BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_current_fragments_no_replace BEFORE INSERT ON stock_epoch_current_fragments WHEN EXISTS(SELECT 1 FROM stock_epoch_current_fragments WHERE source_id=NEW.source_id AND segment_id=NEW.segment_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;

CREATE TRIGGER stock_epoch_current_fragments_no_update BEFORE UPDATE ON stock_epoch_current_fragments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_current_fragments_no_delete BEFORE DELETE ON stock_epoch_current_fragments BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_lot_effects_no_replace BEFORE INSERT ON stock_epoch_lot_effects WHEN EXISTS(SELECT 1 FROM stock_epoch_lot_effects WHERE operation_id=NEW.operation_id AND line_id=NEW.line_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;

CREATE TRIGGER stock_epoch_lot_effects_no_update BEFORE UPDATE ON stock_epoch_lot_effects BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_lot_effects_no_delete BEFORE DELETE ON stock_epoch_lot_effects BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_publication_protocol2 BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2 AND kind='stock_session') BEGIN
SELECT CASE WHEN EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN users u ON u.id=o.actor_id LEFT JOIN roles r ON r.id=u.role_id JOIN stock_session_operations s ON s.id=o.ordinary_id JOIN stock_epoch_operation_contracts c ON c.operation_id=o.id JOIN audit_logs a ON a.id=c.audit_id WHERE o.id=NEW.operation_id AND o.kind='stock_session' AND u.is_active=1 AND u.deleted_at IS NULL AND u.permissions IS o.actor_permissions AND u.role_id IS o.role_id AND r.code IS o.role_code AND r.permissions IS o.role_permissions AND o.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) AND s.actor_id=o.actor_id AND s.request_json=o.request_json AND s.receipt_json=c.ordinary_receipt_json AND a.user_id=o.actor_id AND a.entity='stock_session' AND a.entity_id=s.id AND a.action='stock_session_create' AND a.details=s.receipt_json AND a.new_value=s.receipt_json AND o.source_count=(SELECT COUNT(*) FROM json_each(s.request_json,'$.items') j WHERE json_extract(j.value,'$.quantity')>0) AND o.source_count=(SELECT COUNT(*) FROM stock_epoch_receipt_members m WHERE m.operation_id=o.id)) THEN 1 ELSE RAISE(ABORT,'epoch ordinary operation incomplete') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_receipt_members m WHERE m.operation_id=NEW.operation_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_sources s JOIN stock_epoch_events e ON e.source_id=s.id JOIN stock_epoch_source_states v ON v.event_id=e.id JOIN stock_epoch_source_heads h ON h.source_id=s.id JOIN stock_epoch_segments g ON g.event_id=e.id JOIN stock_epoch_current_fragments c ON c.source_id=s.id AND c.segment_id=g.segment_id WHERE s.admission_operation_id=m.operation_id AND s.movement_id=m.movement_id AND e.operation_id=m.operation_id AND e.kind='admit' AND v.source_id=s.id AND h.event_id=e.id AND h.revision=e.revision AND h.funding_generation=e.funding_generation AND h.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) AND g.segment_id='origin' AND g.source_id=s.id AND g.quantity=s.quantity AND g.gross4=s.gross4 AND g.coverage4=0 AND g.fate='sellable' AND g.consumption_id IS NULL AND g.consumed_cost4=0 AND g.consumed_recovery4=0 AND c.event_id=g.event_id AND c.fate=g.fate AND c.branch_id=m.branch_id)) AND NOT EXISTS(SELECT 1 FROM stock_epoch_sources s WHERE s.admission_operation_id=NEW.operation_id AND NOT EXISTS(SELECT 1 FROM stock_epoch_receipt_members m WHERE m.operation_id=NEW.operation_id AND m.movement_id=s.movement_id)) THEN 1 ELSE RAISE(ABORT,'epoch required source incomplete') END;
SELECT CASE WHEN (SELECT COUNT(*) FROM stock_epoch_segments g JOIN stock_epoch_events e ON e.id=g.event_id WHERE e.operation_id=NEW.operation_id)=(SELECT source_count FROM stock_epoch_operations WHERE id=NEW.operation_id) AND (SELECT COUNT(*) FROM stock_epoch_source_states v JOIN stock_epoch_events e ON e.id=v.event_id WHERE e.operation_id=NEW.operation_id)=(SELECT source_count FROM stock_epoch_operations WHERE id=NEW.operation_id) AND (SELECT COUNT(*) FROM stock_epoch_lot_effects WHERE operation_id=NEW.operation_id)=(SELECT source_count FROM stock_epoch_operations WHERE id=NEW.operation_id) THEN 1 ELSE RAISE(ABORT,'epoch extra or missing child') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_receipt_members m LEFT JOIN stock_epoch_lot_effects f ON f.operation_id=m.operation_id AND f.line_id=m.line_id LEFT JOIN stock_epoch_lot_heads h ON h.batch_id=m.batch_id AND h.branch_id=m.branch_id LEFT JOIN product_batches b ON b.id=m.batch_id LEFT JOIN branch_batch_stock bs ON bs.batch_id=m.batch_id AND bs.branch_id=m.branch_id LEFT JOIN branch_stock a ON a.product_id=m.product_id AND a.branch_id=m.branch_id LEFT JOIN products p ON p.id=m.product_id WHERE m.operation_id=NEW.operation_id AND (f.line_id IS NULL OR h.batch_id IS NULL OR b.id IS NULL OR bs.batch_id IS NULL OR a.product_id IS NULL OR p.id IS NULL OR f.product_id<>m.product_id OR f.branch_id<>m.branch_id OR f.batch_key<>b.batch_key OR CAST(f.quantity_after AS REAL)<>CAST(f.quantity_before AS REAL)+m.quantity OR CAST(f.received_after AS REAL)<>CAST(f.received_before AS REAL)+m.quantity OR f.gross_after4-f.gross_before4<>(SELECT gross4 FROM stock_epoch_sources WHERE movement_id=m.movement_id) OR f.branch_after<>f.branch_before+m.quantity OR f.product_after<>f.product_before+m.quantity OR h.operation_id<>NEW.operation_id OR h.quantity<>f.quantity_after OR h.received_quantity<>f.received_after OR h.received_gross4<>f.gross_after4 OR bs.quantity<>CAST(f.quantity_after AS REAL) OR b.received_quantity<>CAST(f.received_after AS REAL) OR b.received_cost_usd<>f.gross_after4/10000.0 OR a.quantity<>f.branch_after OR p.stock_quantity<>f.product_after)) THEN 1 ELSE RAISE(ABORT,'epoch physical publication incomplete') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM system_flags WHERE key='maintenance') THEN 1 ELSE RAISE(ABORT,'epoch maintenance active') END;
END;

CREATE TRIGGER stock_epoch_protocol2_scope BEFORE INSERT ON stock_epoch_operations WHEN NEW.protocol=2 AND (NEW.kind NOT IN ('stock_session','hold','repair') OR NEW.epoch_count<>0 OR NEW.assignment_count<>0 OR NEW.source_count>25 OR (NEW.kind<>'stock_session' AND NEW.source_count<>1) OR (NEW.kind='stock_session' AND EXISTS(SELECT 1 FROM json_each(NEW.request_json,'$.items') j WHERE json_extract(j.value,'$.kind')<>'receive'))) BEGIN SELECT RAISE(ABORT,'epoch transition not implemented'); END;
CREATE TRIGGER stock_epoch_protocol2_event_scope BEFORE INSERT ON stock_epoch_events WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2) AND (NEW.kind NOT IN ('admit','hold','repair') OR (NEW.kind='admit' AND (NEW.revision<>0 OR NEW.funding_generation<>0)) OR NEW.loss4<>0 OR NEW.recovery4<>0 OR NEW.consumed_cost4<>0 OR NEW.consumed_recovery4<>0) BEGIN SELECT RAISE(ABORT,'epoch transition not implemented'); END;
CREATE TRIGGER stock_epoch_protocol2_source_closed BEFORE INSERT ON stock_epoch_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.admission_operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;
CREATE TRIGGER stock_epoch_protocol2_source_quantity BEFORE INSERT ON stock_epoch_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.admission_operation_id AND protocol=2) AND (json_valid(NEW.quantity)=0 OR json_type(NEW.quantity) NOT IN ('integer','real') OR json_extract(NEW.quantity,'$')<=0 OR json_extract(NEW.quantity,'$')>1000000000 OR NEW.free_quantity<>'0') BEGIN SELECT RAISE(ABORT,'epoch receipt quantity invalid'); END;
CREATE TRIGGER stock_epoch_protocol2_history BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2 AND kind='stock_session') AND NOT EXISTS(SELECT 1 FROM stock_epoch_operations e JOIN stock_session_operations s ON s.id=e.ordinary_id JOIN action_history h ON h.id=s.history_id JOIN undo_snapshots u ON u.id=s.snapshot_id WHERE e.id=NEW.operation_id AND h.entity='stock_session' AND h.entity_id=s.id AND h.status='undoable' AND h.created_by_id=s.actor_id AND json_extract(h.undo_payload,'$.operation_id')=s.id AND json_extract(h.undo_payload,'$.snapshot_id')=s.snapshot_id AND json_extract(h.redo_payload,'$.operation_id')=s.id AND json_extract(h.redo_payload,'$.snapshot_id')=s.snapshot_id AND u.created_by_id=s.actor_id AND json_extract(u.payload_json,'$.operationId')=s.id AND json_extract(u.payload_json,'$.version')=2 AND json_type(u.payload_json,'$.after')='object' AND json_extract(u.payload_json,'$.after')=json_extract(u.payload_json,'$.expected') AND json_extract(s.receipt_json,'$.actionHistoryId')=s.history_id AND json_extract(s.receipt_json,'$.snapshotId')=s.snapshot_id) BEGIN SELECT RAISE(ABORT,'epoch receipt history incomplete'); END;

DROP TRIGGER stock_epoch_publish_source_admission;
CREATE TRIGGER stock_epoch_publish_source_admission BEFORE INSERT ON stock_epoch_publications WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2) AND EXISTS(SELECT 1 FROM stock_epoch_sources s JOIN product_batches b ON b.id=s.batch_id WHERE s.admission_operation_id=NEW.operation_id AND (NOT EXISTS(SELECT 1 FROM stock_epoch_events e WHERE e.operation_id=NEW.operation_id AND e.source_id=s.id AND e.kind='admit' AND e.revision=0) OR b.received_quantity<>(SELECT SUM(CAST(quantity AS REAL)) FROM stock_epoch_sources WHERE batch_id=s.batch_id) OR b.received_cost_usd<>(SELECT SUM(gross4)/10000.0 FROM stock_epoch_sources WHERE batch_id=s.batch_id) OR EXISTS(SELECT 1 FROM inventory_movements m WHERE m.batch_id=s.batch_id AND m.movement_type IN ('add','in') AND NOT EXISTS(SELECT 1 FROM stock_epoch_sources x WHERE x.movement_id=m.id)))) BEGIN SELECT RAISE(ABORT,'epoch source admission incomplete'); END;

CREATE TABLE stock_epoch_fragment_inputs(event_id TEXT NOT NULL REFERENCES stock_epoch_events(id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),before_event_id TEXT NOT NULL,before_segment_id TEXT NOT NULL,PRIMARY KEY(event_id,source_id,before_event_id,before_segment_id),UNIQUE(event_id,source_id,before_segment_id),FOREIGN KEY(before_event_id,before_segment_id) REFERENCES stock_epoch_segments(event_id,segment_id));

CREATE TABLE stock_epoch_commands(operation_id TEXT PRIMARY KEY REFERENCES stock_epoch_operations(id),source_id TEXT NOT NULL REFERENCES stock_epoch_sources(id),before_event_id TEXT NOT NULL REFERENCES stock_epoch_source_states(event_id),previous_lot_operation_id TEXT NOT NULL REFERENCES stock_epoch_operations(id),batch_id INTEGER NOT NULL REFERENCES product_batches(id),branch_id INTEGER NOT NULL REFERENCES branches(id),product_id INTEGER NOT NULL REFERENCES products(id),quantity_before TEXT NOT NULL,quantity_after TEXT NOT NULL CHECK(quantity_after>=0),branch_before TEXT NOT NULL,branch_after TEXT NOT NULL CHECK(branch_after>=0),product_before TEXT NOT NULL,product_after TEXT NOT NULL CHECK(product_after>=0),delta_quantity REAL NOT NULL,request_digest TEXT NOT NULL,response_json TEXT NOT NULL CHECK(json_valid(response_json)),movement_id INTEGER UNIQUE REFERENCES inventory_movements(id),audit_id INTEGER UNIQUE REFERENCES audit_logs(id));

CREATE INDEX stock_epoch_source_fragment_identity ON stock_epoch_segments(source_id,segment_id,event_id);

CREATE TRIGGER stock_epoch_input_owned BEFORE INSERT ON stock_epoch_fragment_inputs WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_events e JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_current_fragments h ON h.source_id=e.source_id JOIN stock_epoch_segments s ON s.event_id=h.event_id AND s.segment_id=h.segment_id WHERE e.id=NEW.event_id AND e.source_id=NEW.source_id AND h.event_id=NEW.before_event_id AND h.segment_id=NEW.before_segment_id AND s.source_id=NEW.source_id AND o.protocol=2 AND o.kind IN ('hold','repair') AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch fragment preimage'); END;

CREATE TRIGGER stock_epoch_command_preimage BEFORE INSERT ON stock_epoch_commands WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN stock_epoch_events e ON e.operation_id=o.id JOIN stock_epoch_source_heads h ON h.source_id=e.source_id JOIN stock_epoch_sources s ON s.id=h.source_id JOIN stock_epoch_lot_heads l ON l.batch_id=s.batch_id AND l.branch_id=s.branch_id JOIN branch_batch_stock b ON b.batch_id=l.batch_id AND b.branch_id=l.branch_id JOIN branch_stock a ON a.product_id=s.product_id AND a.branch_id=s.branch_id JOIN products p ON p.id=s.product_id WHERE o.id=NEW.operation_id AND o.protocol=2 AND o.kind IN ('hold','repair') AND h.event_id=NEW.before_event_id AND h.source_id=NEW.source_id AND l.operation_id=NEW.previous_lot_operation_id AND s.batch_id=NEW.batch_id AND s.branch_id=NEW.branch_id AND s.product_id=NEW.product_id AND b.quantity=NEW.quantity_before AND a.quantity=NEW.branch_before AND p.stock_quantity=NEW.product_before AND CAST(l.quantity AS REAL)=NEW.quantity_before AND e.revision=h.revision+1 AND e.funding_generation=h.funding_generation AND o.dataset_generation=h.dataset_generation AND json_extract(o.request_json,'$.source_id')=NEW.source_id AND json_extract(o.request_json,'$.expected_revision')=h.revision AND json_extract(o.request_json,'$.expected_generation')=h.funding_generation AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications x WHERE x.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch command preimage'); END;

DROP TRIGGER stock_epoch_source_heads_no_update;
CREATE TRIGGER stock_epoch_source_heads_no_update BEFORE UPDATE ON stock_epoch_source_heads WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_events e JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_commands c ON c.operation_id=o.id JOIN stock_epoch_source_states v ON v.event_id=e.id WHERE e.id=NEW.event_id AND e.source_id=OLD.source_id AND NEW.source_id=OLD.source_id AND c.source_id=OLD.source_id AND c.before_event_id=OLD.event_id AND NEW.revision=OLD.revision+1 AND e.revision=NEW.revision AND NEW.funding_generation=OLD.funding_generation AND v.funding_generation=NEW.funding_generation AND NEW.dataset_generation=OLD.dataset_generation AND o.dataset_generation=NEW.dataset_generation AND o.protocol=2 AND o.kind IN ('hold','repair') AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch source head unowned'); END;

DROP TRIGGER stock_epoch_current_fragments_no_delete;
CREATE TRIGGER stock_epoch_current_fragments_no_delete BEFORE DELETE ON stock_epoch_current_fragments WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_fragment_inputs i JOIN stock_epoch_events e ON e.id=i.event_id JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_segments s ON s.event_id=e.id AND s.segment_id=i.before_segment_id WHERE i.source_id=OLD.source_id AND i.before_event_id=OLD.event_id AND i.before_segment_id=OLD.segment_id AND s.fate='retired' AND s.quantity='0' AND s.gross4=0 AND s.coverage4=0 AND o.protocol=2 AND o.kind IN ('hold','repair') AND NOT EXISTS(SELECT 1 FROM stock_epoch_publications p WHERE p.operation_id=o.id)) BEGIN SELECT RAISE(ABORT,'epoch fragment retirement unowned'); END;

DROP TRIGGER stock_epoch_member_preimage;
CREATE TRIGGER stock_epoch_member_preimage BEFORE INSERT ON stock_epoch_operation_sources WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2) AND (NEW.expected_revision<>(SELECT COALESCE(MAX(revision),-1) FROM stock_epoch_event_registry WHERE source_id=NEW.source_id) OR NEW.expected_funding_generation<>COALESCE((SELECT funding_generation FROM stock_epoch_events WHERE source_id=NEW.source_id ORDER BY revision DESC LIMIT 1),(SELECT MAX(generation) FROM stock_funding_events WHERE source_id=NEW.source_id),-1) ) BEGIN SELECT RAISE(ABORT,'epoch source changed'); END;

CREATE TRIGGER stock_epoch_typed_member_preimage BEFORE INSERT ON stock_epoch_operation_sources WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2) AND NOT ((NEW.expected_revision=-1 AND NEW.expected_funding_generation=-1 AND NOT EXISTS(SELECT 1 FROM stock_epoch_event_registry WHERE source_id=NEW.source_id)) OR EXISTS(SELECT 1 FROM stock_epoch_source_heads h JOIN stock_epoch_events e ON e.id=h.event_id JOIN stock_epoch_publications p ON p.operation_id=e.operation_id WHERE h.source_id=NEW.source_id AND h.revision=NEW.expected_revision AND h.funding_generation=NEW.expected_funding_generation AND h.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1))) BEGIN SELECT RAISE(ABORT,'epoch source changed'); END;

CREATE TRIGGER stock_epoch_fragment_inputs_closed_insert BEFORE INSERT ON stock_epoch_fragment_inputs WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=(SELECT operation_id FROM stock_epoch_events WHERE id=NEW.event_id)) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_fragment_inputs_no_delete BEFORE DELETE ON stock_epoch_fragment_inputs BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_commands_closed_insert BEFORE INSERT ON stock_epoch_commands WHEN EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch publication closed'); END;

CREATE TRIGGER stock_epoch_commands_no_delete BEFORE DELETE ON stock_epoch_commands BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_fragment_inputs_no_update BEFORE UPDATE ON stock_epoch_fragment_inputs BEGIN SELECT RAISE(ABORT,'epoch immutable'); END;

CREATE TRIGGER stock_epoch_commands_no_update BEFORE UPDATE ON stock_epoch_commands WHEN NEW.operation_id IS NOT OLD.operation_id OR NEW.source_id IS NOT OLD.source_id OR NEW.before_event_id IS NOT OLD.before_event_id OR NEW.previous_lot_operation_id IS NOT OLD.previous_lot_operation_id OR NEW.batch_id IS NOT OLD.batch_id OR NEW.branch_id IS NOT OLD.branch_id OR NEW.product_id IS NOT OLD.product_id OR NEW.quantity_before IS NOT OLD.quantity_before OR NEW.quantity_after IS NOT OLD.quantity_after OR NEW.branch_before IS NOT OLD.branch_before OR NEW.branch_after IS NOT OLD.branch_after OR NEW.product_before IS NOT OLD.product_before OR NEW.product_after IS NOT OLD.product_after OR NEW.delta_quantity IS NOT OLD.delta_quantity OR NEW.request_digest IS NOT OLD.request_digest OR NEW.response_json IS NOT OLD.response_json OR (OLD.movement_id IS NOT NULL AND NEW.movement_id IS NOT OLD.movement_id) OR (OLD.audit_id IS NOT NULL AND NEW.audit_id IS NOT OLD.audit_id) OR EXISTS(SELECT 1 FROM stock_epoch_publications WHERE operation_id=OLD.operation_id) BEGIN SELECT RAISE(ABORT,'epoch command immutable'); END;

CREATE TRIGGER stock_epoch_quantity_shape BEFORE INSERT ON stock_epoch_segments WHEN NEW.source_id IS NOT NULL AND (json_valid(NEW.quantity)=0 OR json_type(NEW.quantity) NOT IN ('integer','real') OR NEW.quantity GLOB '*[^0-9.]*' OR length(NEW.quantity)-length(replace(NEW.quantity,'.',''))>1 OR (instr(NEW.quantity,'.')>0 AND length(NEW.quantity)-instr(NEW.quantity,'.')>24) OR CAST(NEW.quantity AS REAL)<0 OR CAST(NEW.quantity AS REAL)>1000000000 OR (CAST(NEW.quantity AS REAL)=0 AND (NEW.gross4<>0 OR NEW.coverage4<>0))) BEGIN SELECT RAISE(ABORT,'epoch fragment quantity'); END;

CREATE VIEW stock_epoch_quantity_terms AS
SELECT i.event_id,'partition:'||i.before_segment_id AS group_key,0 AS side,g.quantity FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id
UNION ALL SELECT i.event_id,'partition:'||i.before_segment_id,1,g.quantity FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.event_id AND g.parent_segment_id=i.before_segment_id AND g.fate<>'retired'
UNION ALL SELECT e.id,'fate:sellable',0,v.sellable_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=e.id
UNION ALL SELECT i.event_id,'fate:sellable',0,g.quantity FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE g.fate='sellable'
UNION ALL SELECT e.id,'fate:sellable',1,v.sellable_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=c.before_event_id
UNION ALL SELECT e.id,'fate:sellable',1,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id WHERE g.fate='sellable'
UNION ALL SELECT e.id,'fate:held',0,v.held_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=e.id
UNION ALL SELECT i.event_id,'fate:held',0,g.quantity FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE g.fate='held'
UNION ALL SELECT e.id,'fate:held',1,v.held_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=c.before_event_id
UNION ALL SELECT e.id,'fate:held',1,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id WHERE g.fate='held'
UNION ALL SELECT e.id,'fate:disposed',0,v.disposed_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=e.id
UNION ALL SELECT i.event_id,'fate:disposed',0,g.quantity FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE g.fate='disposed'
UNION ALL SELECT e.id,'fate:disposed',1,v.disposed_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=c.before_event_id
UNION ALL SELECT e.id,'fate:disposed',1,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id WHERE g.fate='disposed'
UNION ALL SELECT e.id,'fate:consumed',0,v.consumed_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=e.id
UNION ALL SELECT i.event_id,'fate:consumed',0,g.quantity FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE g.fate='consumed'
UNION ALL SELECT e.id,'fate:consumed',1,v.consumed_quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states v ON v.event_id=c.before_event_id
UNION ALL SELECT e.id,'fate:consumed',1,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id WHERE g.fate='consumed'
UNION ALL SELECT e.id,'physical:lot',0,c.quantity_after FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id
UNION ALL SELECT e.id,'physical:lot',1,c.quantity_before FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id
UNION ALL SELECT e.id,'physical:lot',CASE WHEN e.kind='hold' THEN 0 ELSE 1 END,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id AND g.segment_id=json_extract(o.request_json,'$.child_segment_id')
UNION ALL SELECT e.id,'physical:branch',0,c.branch_after FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id
UNION ALL SELECT e.id,'physical:branch',1,c.branch_before FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id
UNION ALL SELECT e.id,'physical:branch',CASE WHEN e.kind='hold' THEN 0 ELSE 1 END,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id AND g.segment_id=json_extract(o.request_json,'$.child_segment_id')
UNION ALL SELECT e.id,'physical:product',0,c.product_after FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id
UNION ALL SELECT e.id,'physical:product',1,c.product_before FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id
UNION ALL SELECT e.id,'physical:product',CASE WHEN e.kind='hold' THEN 0 ELSE 1 END,g.quantity FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id AND g.segment_id=json_extract(o.request_json,'$.child_segment_id');

CREATE VIEW stock_epoch_quantity_parts AS SELECT event_id,group_key,side,CAST(quantity AS INTEGER) AS whole,CAST(substr(CASE WHEN instr(quantity,'.')>0 THEN substr(quantity,instr(quantity,'.')+1) ELSE '' END||'000000000000000000000000',1,6) AS INTEGER) AS p1,CAST(substr(CASE WHEN instr(quantity,'.')>0 THEN substr(quantity,instr(quantity,'.')+1) ELSE '' END||'000000000000000000000000',7,6) AS INTEGER) AS p2,CAST(substr(CASE WHEN instr(quantity,'.')>0 THEN substr(quantity,instr(quantity,'.')+1) ELSE '' END||'000000000000000000000000',13,6) AS INTEGER) AS p3,CAST(substr(CASE WHEN instr(quantity,'.')>0 THEN substr(quantity,instr(quantity,'.')+1) ELSE '' END||'000000000000000000000000',19,6) AS INTEGER) AS p4 FROM stock_epoch_quantity_terms;

CREATE VIEW stock_epoch_quantity_sums AS SELECT event_id,group_key,side,SUM(whole) AS whole,SUM(p1) AS p1,SUM(p2) AS p2,SUM(p3) AS p3,SUM(p4) AS p4 FROM stock_epoch_quantity_parts GROUP BY event_id,group_key,side;

CREATE VIEW stock_epoch_quantity_proofs AS SELECT event_id,group_key,side,json_array(whole+((p1+((p2+((p3+(p4/1000000))/1000000))/1000000))/1000000),(p1+((p2+((p3+(p4/1000000))/1000000))/1000000))%1000000,(p2+((p3+(p4/1000000))/1000000))%1000000,(p3+(p4/1000000))%1000000,p4%1000000) AS exact_quantity FROM stock_epoch_quantity_sums;

CREATE TRIGGER stock_epoch_publish_partition BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2 AND kind IN ('hold','repair')) BEGIN
SELECT CASE WHEN EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN users u ON u.id=o.actor_id LEFT JOIN roles r ON r.id=u.role_id JOIN stock_epoch_commands c ON c.operation_id=o.id JOIN stock_epoch_events e ON e.operation_id=o.id JOIN stock_epoch_source_states v ON v.event_id=e.id JOIN stock_epoch_source_heads h ON h.source_id=e.source_id JOIN stock_epoch_receipts receipt ON receipt.event_id=e.id JOIN audit_logs a ON a.id=c.audit_id WHERE o.id=NEW.operation_id AND o.kind=e.kind AND o.source_count=1 AND o.epoch_count=0 AND o.assignment_count=0 AND u.is_active=1 AND u.deleted_at IS NULL AND u.permissions IS o.actor_permissions AND u.role_id IS o.role_id AND r.code IS o.role_code AND r.permissions IS o.role_permissions AND h.event_id=e.id AND h.revision=e.revision AND h.funding_generation=e.funding_generation AND h.dataset_generation=o.dataset_generation AND o.dataset_generation=(SELECT generation FROM stock_epoch_dataset WHERE singleton=1) AND receipt.actor_id=o.actor_id AND receipt.request_id=o.request_id AND receipt.request_json=o.request_json AND receipt.request_digest=c.request_digest AND receipt.response_json=c.response_json AND a.user_id=o.actor_id AND a.entity='stock_epoch' AND a.entity_id=e.id AND a.action=e.kind AND a.details=c.response_json AND a.new_value=c.response_json AND json_extract(c.response_json,'$.source_id')=e.source_id AND json_extract(c.response_json,'$.event_id')=e.id AND json_extract(c.response_json,'$.revision')=e.revision AND json_extract(c.response_json,'$.kind')=e.kind) THEN 1 ELSE RAISE(ABORT,'epoch transition publication incomplete') END;
SELECT CASE WHEN (SELECT COUNT(*) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_events e ON e.id=i.event_id WHERE e.operation_id=NEW.operation_id)=1 AND NOT EXISTS(SELECT 1 FROM stock_epoch_fragment_inputs i JOIN stock_epoch_events e ON e.id=i.event_id JOIN stock_epoch_operations o ON o.id=e.operation_id JOIN stock_epoch_segments b ON b.event_id=i.before_event_id AND b.segment_id=i.before_segment_id WHERE e.operation_id=NEW.operation_id AND (i.source_id<>e.source_id OR i.before_segment_id<>json_extract(o.request_json,'$.segment_id') OR b.fate<>CASE e.kind WHEN 'hold' THEN 'sellable' ELSE 'held' END OR EXISTS(SELECT 1 FROM stock_epoch_current_fragments h WHERE h.source_id=i.source_id AND h.segment_id=i.before_segment_id) OR NOT EXISTS(SELECT 1 FROM stock_epoch_segments g WHERE g.event_id=e.id AND g.segment_id=i.before_segment_id AND g.parent_segment_id=i.before_segment_id AND g.fate='retired' AND g.quantity='0' AND g.gross4=0 AND g.coverage4=0) OR b.gross4<>(SELECT SUM(gross4) FROM stock_epoch_segments g WHERE g.event_id=e.id AND g.parent_segment_id=i.before_segment_id AND g.fate<>'retired') OR b.coverage4<>(SELECT SUM(coverage4) FROM stock_epoch_segments g WHERE g.event_id=e.id AND g.parent_segment_id=i.before_segment_id AND g.fate<>'retired'))) THEN 1 ELSE RAISE(ABORT,'epoch split input incomplete') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_quantity_proofs left_side JOIN stock_epoch_events e ON e.id=left_side.event_id LEFT JOIN stock_epoch_quantity_proofs right_side ON right_side.event_id=left_side.event_id AND right_side.group_key=left_side.group_key AND right_side.side=1 WHERE e.operation_id=NEW.operation_id AND left_side.side=0 AND (right_side.event_id IS NULL OR left_side.exact_quantity<>right_side.exact_quantity)) THEN 1 ELSE RAISE(ABORT,'epoch exact quantity partition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_segments g JOIN stock_epoch_events e ON e.id=g.event_id WHERE e.operation_id=NEW.operation_id AND (g.source_id<>e.source_id OR NOT EXISTS(SELECT 1 FROM stock_epoch_fragment_inputs i WHERE i.event_id=e.id AND i.source_id=e.source_id AND i.before_segment_id=g.parent_segment_id) OR g.loss4<>0 OR g.recovery4<>0 OR g.consumed_cost4<>0 OR g.consumed_recovery4<>0 OR g.consumption_id IS NOT NULL OR (g.fate<>'retired' AND NOT EXISTS(SELECT 1 FROM stock_epoch_current_fragments h WHERE h.source_id=e.source_id AND h.segment_id=g.segment_id AND h.event_id=e.id AND h.fate=g.fate AND h.allocation_id=g.allocation_id AND h.branch_id=g.branch_id)))) THEN 1 ELSE RAISE(ABORT,'epoch split output incomplete') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_operations o ON o.id=c.operation_id JOIN stock_epoch_segments g ON g.event_id=e.id AND g.segment_id=json_extract(o.request_json,'$.child_segment_id') JOIN inventory_movements m ON m.id=c.movement_id JOIN stock_epoch_lot_heads h ON h.batch_id=c.batch_id AND h.branch_id=c.branch_id JOIN branch_batch_stock b ON b.batch_id=c.batch_id AND b.branch_id=c.branch_id JOIN branch_stock a ON a.product_id=c.product_id AND a.branch_id=c.branch_id JOIN products p ON p.id=c.product_id WHERE c.operation_id=NEW.operation_id AND (g.fate<>CASE e.kind WHEN 'hold' THEN 'held' ELSE 'sellable' END OR CAST(g.quantity AS REAL)<>json_extract(o.request_json,'$.quantity') OR c.delta_quantity<>CAST(g.quantity AS REAL)*CASE e.kind WHEN 'hold' THEN -1 ELSE 1 END OR b.quantity<>CAST(c.quantity_after AS REAL) OR a.quantity<>CAST(c.branch_after AS REAL) OR p.stock_quantity<>CAST(c.product_after AS REAL) OR h.operation_id<>c.operation_id OR CAST(h.quantity AS REAL)<>CAST(c.quantity_after AS REAL) OR m.product_id<>c.product_id OR m.branch_id<>c.branch_id OR m.batch_id<>c.batch_id OR m.quantity<>c.delta_quantity OR m.reference_id<>c.operation_id OR m.user_id<>o.actor_id OR m.movement_type<>CASE e.kind WHEN 'hold' THEN 'remove' ELSE 'add' END)) AND EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN inventory_movements m ON m.id=c.movement_id WHERE c.operation_id=NEW.operation_id) THEN 1 ELSE RAISE(ABORT,'epoch transition physical effects') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states old_state ON old_state.event_id=c.before_event_id JOIN stock_epoch_source_states next_state ON next_state.event_id=e.id WHERE c.operation_id=NEW.operation_id AND next_state.sellable_net4+COALESCE((SELECT SUM(g.gross4-g.coverage4) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE i.event_id=e.id AND g.fate='sellable'),0)<>old_state.sellable_net4+COALESCE((SELECT SUM(gross4-coverage4) FROM stock_epoch_segments WHERE event_id=e.id AND fate='sellable'),0)) THEN 1 ELSE RAISE(ABORT,'epoch sellable_net4 transition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states old_state ON old_state.event_id=c.before_event_id JOIN stock_epoch_source_states next_state ON next_state.event_id=e.id WHERE c.operation_id=NEW.operation_id AND next_state.held_net4+COALESCE((SELECT SUM(g.gross4-g.coverage4) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE i.event_id=e.id AND g.fate='held'),0)<>old_state.held_net4+COALESCE((SELECT SUM(gross4-coverage4) FROM stock_epoch_segments WHERE event_id=e.id AND fate='held'),0)) THEN 1 ELSE RAISE(ABORT,'epoch held_net4 transition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states old_state ON old_state.event_id=c.before_event_id JOIN stock_epoch_source_states next_state ON next_state.event_id=e.id WHERE c.operation_id=NEW.operation_id AND next_state.loss4+COALESCE((SELECT SUM(g.loss4) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE i.event_id=e.id AND g.fate='disposed'),0)<>old_state.loss4+COALESCE((SELECT SUM(loss4) FROM stock_epoch_segments WHERE event_id=e.id AND fate='disposed'),0)) THEN 1 ELSE RAISE(ABORT,'epoch loss4 transition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states old_state ON old_state.event_id=c.before_event_id JOIN stock_epoch_source_states next_state ON next_state.event_id=e.id WHERE c.operation_id=NEW.operation_id AND next_state.loss_recovery4+COALESCE((SELECT SUM(g.recovery4) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE i.event_id=e.id AND g.fate='disposed'),0)<>old_state.loss_recovery4+COALESCE((SELECT SUM(recovery4) FROM stock_epoch_segments WHERE event_id=e.id AND fate='disposed'),0)) THEN 1 ELSE RAISE(ABORT,'epoch loss_recovery4 transition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states old_state ON old_state.event_id=c.before_event_id JOIN stock_epoch_source_states next_state ON next_state.event_id=e.id WHERE c.operation_id=NEW.operation_id AND next_state.consumed_cost4+COALESCE((SELECT SUM(g.consumed_cost4) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE i.event_id=e.id AND g.fate='consumed'),0)<>old_state.consumed_cost4+COALESCE((SELECT SUM(consumed_cost4) FROM stock_epoch_segments WHERE event_id=e.id AND fate='consumed'),0)) THEN 1 ELSE RAISE(ABORT,'epoch consumed_cost4 transition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states old_state ON old_state.event_id=c.before_event_id JOIN stock_epoch_source_states next_state ON next_state.event_id=e.id WHERE c.operation_id=NEW.operation_id AND next_state.consumed_recovery4+COALESCE((SELECT SUM(g.consumed_recovery4) FROM stock_epoch_fragment_inputs i JOIN stock_epoch_segments g ON g.event_id=i.before_event_id AND g.segment_id=i.before_segment_id WHERE i.event_id=e.id AND g.fate='consumed'),0)<>old_state.consumed_recovery4+COALESCE((SELECT SUM(consumed_recovery4) FROM stock_epoch_segments WHERE event_id=e.id AND fate='consumed'),0)) THEN 1 ELSE RAISE(ABORT,'epoch consumed_recovery4 transition') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM system_flags WHERE key='maintenance') THEN 1 ELSE RAISE(ABORT,'epoch maintenance active') END;
END;

CREATE TRIGGER stock_epoch_state_quantity_shape BEFORE INSERT ON stock_epoch_source_states WHEN (json_valid(NEW.sellable_quantity)=0 OR json_type(NEW.sellable_quantity) NOT IN ('integer','real') OR NEW.sellable_quantity GLOB '*[^0-9.]*' OR (instr(NEW.sellable_quantity,'.')>0 AND length(NEW.sellable_quantity)-instr(NEW.sellable_quantity,'.')>24) OR CAST(NEW.sellable_quantity AS REAL)<0 OR CAST(NEW.sellable_quantity AS REAL)>1000000000) OR (json_valid(NEW.held_quantity)=0 OR json_type(NEW.held_quantity) NOT IN ('integer','real') OR NEW.held_quantity GLOB '*[^0-9.]*' OR (instr(NEW.held_quantity,'.')>0 AND length(NEW.held_quantity)-instr(NEW.held_quantity,'.')>24) OR CAST(NEW.held_quantity AS REAL)<0 OR CAST(NEW.held_quantity AS REAL)>1000000000) OR (json_valid(NEW.disposed_quantity)=0 OR json_type(NEW.disposed_quantity) NOT IN ('integer','real') OR NEW.disposed_quantity GLOB '*[^0-9.]*' OR (instr(NEW.disposed_quantity,'.')>0 AND length(NEW.disposed_quantity)-instr(NEW.disposed_quantity,'.')>24) OR CAST(NEW.disposed_quantity AS REAL)<0 OR CAST(NEW.disposed_quantity AS REAL)>1000000000) OR (json_valid(NEW.consumed_quantity)=0 OR json_type(NEW.consumed_quantity) NOT IN ('integer','real') OR NEW.consumed_quantity GLOB '*[^0-9.]*' OR (instr(NEW.consumed_quantity,'.')>0 AND length(NEW.consumed_quantity)-instr(NEW.consumed_quantity,'.')>24) OR CAST(NEW.consumed_quantity AS REAL)<0 OR CAST(NEW.consumed_quantity AS REAL)>1000000000) BEGIN SELECT RAISE(ABORT,'epoch state quantity'); END;
CREATE TRIGGER stock_epoch_fragment_inputs_no_replace BEFORE INSERT ON stock_epoch_fragment_inputs WHEN EXISTS(SELECT 1 FROM stock_epoch_fragment_inputs WHERE event_id=NEW.event_id AND source_id=NEW.source_id AND before_segment_id=NEW.before_segment_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;
CREATE TRIGGER stock_epoch_commands_no_replace BEFORE INSERT ON stock_epoch_commands WHEN EXISTS(SELECT 1 FROM stock_epoch_commands WHERE operation_id=NEW.operation_id) BEGIN SELECT RAISE(ABORT,'epoch immutable identity'); END;

CREATE TRIGGER stock_epoch_partition_output_shape BEFORE INSERT ON stock_epoch_publications WHEN EXISTS(SELECT 1 FROM stock_epoch_operations WHERE id=NEW.operation_id AND protocol=2 AND kind IN ('hold','repair')) BEGIN
SELECT CASE WHEN EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN stock_epoch_events e ON e.operation_id=o.id JOIN stock_epoch_commands c ON c.operation_id=o.id JOIN stock_epoch_sources source ON source.id=c.source_id JOIN stock_epoch_fragment_inputs i ON i.event_id=e.id JOIN stock_epoch_segments before_leaf ON before_leaf.event_id=i.before_event_id AND before_leaf.segment_id=i.before_segment_id JOIN stock_epoch_segments child ON child.event_id=e.id AND child.segment_id=json_extract(o.request_json,'$.child_segment_id') JOIN stock_epoch_lot_heads h ON h.batch_id=c.batch_id AND h.branch_id=c.branch_id JOIN branch_batch_stock b ON b.batch_id=c.batch_id AND b.branch_id=c.branch_id JOIN branch_stock a ON a.product_id=c.product_id AND a.branch_id=c.branch_id JOIN products p ON p.id=c.product_id JOIN inventory_movements m ON m.id=c.movement_id WHERE o.id=NEW.operation_id AND child.parent_segment_id=i.before_segment_id AND child.source_id=c.source_id AND child.branch_id=source.branch_id AND child.fate=CASE e.kind WHEN 'hold' THEN 'held' ELSE 'sellable' END AND child.allocation_id=CASE WHEN e.kind='hold' AND before_leaf.allocation_id='origin' THEN child.segment_id ELSE before_leaf.allocation_id END AND child.reason=CASE e.kind WHEN 'hold' THEN json_extract(o.request_json,'$.reason') ELSE '' END AND child.segment_id<>i.before_segment_id AND child.segment_id||'-remaining'<>i.before_segment_id) THEN 1 ELSE RAISE(ABORT,'epoch required partition child') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_operations o JOIN stock_epoch_events e ON e.operation_id=o.id JOIN stock_epoch_fragment_inputs i ON i.event_id=e.id JOIN stock_epoch_segments before_leaf ON before_leaf.event_id=i.before_event_id AND before_leaf.segment_id=i.before_segment_id JOIN stock_epoch_segments g ON g.event_id=e.id WHERE o.id=NEW.operation_id AND ((g.fate='retired' AND g.segment_id<>i.before_segment_id) OR (g.fate<>'retired' AND CAST(g.quantity AS REAL)<=0) OR (g.fate<>'retired' AND g.segment_id NOT IN (json_extract(o.request_json,'$.child_segment_id'),json_extract(o.request_json,'$.child_segment_id')||'-remaining')) OR (g.segment_id=json_extract(o.request_json,'$.child_segment_id')||'-remaining' AND (g.fate<>before_leaf.fate OR g.allocation_id<>before_leaf.allocation_id OR g.reason<>before_leaf.reason OR g.branch_id<>before_leaf.branch_id)))) THEN 1 ELSE RAISE(ABORT,'epoch unauthorized partition child') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states s ON s.event_id=e.id WHERE c.operation_id=NEW.operation_id AND (json_extract(c.response_json,'$.totals.event_id') IS NOT s.event_id OR json_extract(c.response_json,'$.totals.source_id') IS NOT s.source_id OR json_extract(c.response_json,'$.totals.funding_generation') IS NOT s.funding_generation OR json_extract(c.response_json,'$.totals.gross4') IS NOT s.gross4 OR json_extract(c.response_json,'$.totals.paid4') IS NOT s.paid4 OR json_extract(c.response_json,'$.totals.debt4') IS NOT s.debt4 OR json_extract(c.response_json,'$.totals.credit4') IS NOT s.credit4)) THEN 1 ELSE RAISE(ABORT,'epoch typed receipt mismatch') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states s ON s.event_id=e.id WHERE c.operation_id=NEW.operation_id AND (json_extract(c.response_json,'$.totals.asset4') IS NOT s.asset4 OR json_extract(c.response_json,'$.totals.cash_in4') IS NOT s.cash_in4 OR json_extract(c.response_json,'$.totals.cash_out4') IS NOT s.cash_out4 OR json_extract(c.response_json,'$.totals.shipping4') IS NOT s.shipping4 OR json_extract(c.response_json,'$.totals.sellable_quantity') IS NOT s.sellable_quantity OR json_extract(c.response_json,'$.totals.held_quantity') IS NOT s.held_quantity OR json_extract(c.response_json,'$.totals.disposed_quantity') IS NOT s.disposed_quantity)) THEN 1 ELSE RAISE(ABORT,'epoch typed receipt mismatch') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states s ON s.event_id=e.id WHERE c.operation_id=NEW.operation_id AND (json_extract(c.response_json,'$.totals.consumed_quantity') IS NOT s.consumed_quantity OR json_extract(c.response_json,'$.totals.sellable_net4') IS NOT s.sellable_net4 OR json_extract(c.response_json,'$.totals.held_net4') IS NOT s.held_net4 OR json_extract(c.response_json,'$.totals.loss4') IS NOT s.loss4 OR json_extract(c.response_json,'$.totals.loss_recovery4') IS NOT s.loss_recovery4 OR json_extract(c.response_json,'$.totals.consumed_cost4') IS NOT s.consumed_cost4 OR json_extract(c.response_json,'$.totals.consumed_recovery4') IS NOT s.consumed_recovery4)) THEN 1 ELSE RAISE(ABORT,'epoch typed receipt mismatch') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN stock_epoch_source_states s ON s.event_id=e.id WHERE c.operation_id=NEW.operation_id AND (json_extract(c.response_json,'$.totals.pending4') IS NOT s.pending4)) THEN 1 ELSE RAISE(ABORT,'epoch typed receipt mismatch') END;
SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id WHERE c.operation_id=NEW.operation_id AND (json_array_length(c.response_json,'$.changed_segments')<>(SELECT COUNT(*) FROM stock_epoch_segments g WHERE g.event_id=e.id AND g.fate<>'retired') OR EXISTS(SELECT 1 FROM stock_epoch_segments g WHERE g.event_id=e.id AND g.fate<>'retired' AND NOT EXISTS(SELECT 1 FROM json_each(c.response_json,'$.changed_segments') j WHERE json_extract(j.value,'$.event_id') IS g.event_id AND json_extract(j.value,'$.segment_id') IS g.segment_id AND json_extract(j.value,'$.allocation_id') IS g.allocation_id AND json_extract(j.value,'$.fate') IS g.fate AND json_extract(j.value,'$.quantity') IS g.quantity AND json_extract(j.value,'$.gross4') IS g.gross4 AND json_extract(j.value,'$.coverage4') IS g.coverage4 AND json_extract(j.value,'$.loss4') IS g.loss4 AND json_extract(j.value,'$.recovery4') IS g.recovery4 AND json_extract(j.value,'$.reason') IS g.reason AND json_extract(j.value,'$.consumption_id') IS g.consumption_id AND json_extract(j.value,'$.consumed_cost4') IS g.consumed_cost4 AND json_extract(j.value,'$.consumed_recovery4') IS g.consumed_recovery4 AND json_extract(j.value,'$.source_id') IS g.source_id AND json_extract(j.value,'$.branch_id') IS g.branch_id AND json_extract(j.value,'$.parent_segment_id') IS g.parent_segment_id)))) THEN 1 ELSE RAISE(ABORT,'epoch changed fragment receipt mismatch') END;
SELECT CASE WHEN (SELECT COUNT(*) FROM stock_epoch_commands c JOIN stock_epoch_events e ON e.operation_id=c.operation_id JOIN audit_logs a ON a.entity='stock_epoch' AND a.entity_id=e.id WHERE c.operation_id=NEW.operation_id)=1 THEN 1 ELSE RAISE(ABORT,'epoch transition audit membership') END;
END;

CREATE TRIGGER stock_epoch_command_quantity_shape BEFORE INSERT ON stock_epoch_commands WHEN (json_valid(NEW.quantity_before)=0 OR json_type(NEW.quantity_before) NOT IN ('integer','real') OR NEW.quantity_before GLOB '*[^0-9.]*' OR (instr(NEW.quantity_before,'.')>0 AND length(NEW.quantity_before)-instr(NEW.quantity_before,'.')>24) OR CAST(NEW.quantity_before AS REAL)<0 OR CAST(NEW.quantity_before AS REAL)>1000000000) OR (json_valid(NEW.quantity_after)=0 OR json_type(NEW.quantity_after) NOT IN ('integer','real') OR NEW.quantity_after GLOB '*[^0-9.]*' OR (instr(NEW.quantity_after,'.')>0 AND length(NEW.quantity_after)-instr(NEW.quantity_after,'.')>24) OR CAST(NEW.quantity_after AS REAL)<0 OR CAST(NEW.quantity_after AS REAL)>1000000000) OR (json_valid(NEW.branch_before)=0 OR json_type(NEW.branch_before) NOT IN ('integer','real') OR NEW.branch_before GLOB '*[^0-9.]*' OR (instr(NEW.branch_before,'.')>0 AND length(NEW.branch_before)-instr(NEW.branch_before,'.')>24) OR CAST(NEW.branch_before AS REAL)<0 OR CAST(NEW.branch_before AS REAL)>1000000000) OR (json_valid(NEW.branch_after)=0 OR json_type(NEW.branch_after) NOT IN ('integer','real') OR NEW.branch_after GLOB '*[^0-9.]*' OR (instr(NEW.branch_after,'.')>0 AND length(NEW.branch_after)-instr(NEW.branch_after,'.')>24) OR CAST(NEW.branch_after AS REAL)<0 OR CAST(NEW.branch_after AS REAL)>1000000000) OR (json_valid(NEW.product_before)=0 OR json_type(NEW.product_before) NOT IN ('integer','real') OR NEW.product_before GLOB '*[^0-9.]*' OR (instr(NEW.product_before,'.')>0 AND length(NEW.product_before)-instr(NEW.product_before,'.')>24) OR CAST(NEW.product_before AS REAL)<0 OR CAST(NEW.product_before AS REAL)>1000000000) OR (json_valid(NEW.product_after)=0 OR json_type(NEW.product_after) NOT IN ('integer','real') OR NEW.product_after GLOB '*[^0-9.]*' OR (instr(NEW.product_after,'.')>0 AND length(NEW.product_after)-instr(NEW.product_after,'.')>24) OR CAST(NEW.product_after AS REAL)<0 OR CAST(NEW.product_after AS REAL)>1000000000) BEGIN SELECT RAISE(ABORT,'epoch command quantity'); END;
