// searchCore.ts -- the one product-search normalizer, term model and matcher.
//
// The canonical copy is cloudflare/src/lib/searchCore.ts and
// frontend/src/utils/searchCore.ts is a generated byte copy: edit the Worker
// copy, then run `node ops/scripts/sync-search-core.mjs`. Both packages carry
// a parity test that fails when the copies differ.
//
// Pure and import-free on purpose, so the Worker and the browser run the
// same code. Design: Records/Lanes/2026-10-05/G37-SEARCH-DESIGN.md section 4.
//
// Matching contract (identical on every executor):
//   - normalize: NFKC, strip zero-width/format characters, fold Latin
//     diacritics, lowercase, joiners to spaces, keep letters, MARKS (Khmer
//     vowel signs and coeng) and numbers, fold o->0 inside code tokens.
//   - a row is indexed by its name (weight 1) and brand (0.8) terms, plus
//     roman aliases (ii->2), letter/digit splits (100ml -> 100, ml) and
//     short-run joins (sk ii -> skii, sk2; bs mall -> bsmall). Category is
//     NOT a search field: the owner narrowed the box to name/code (brand and
//     category have their own filters; see PRODUCT_SEARCH_COLUMNS in
//     searchMatch.ts), and category words flood fuzzy matches ("lipstik"
//     reached every Lip Oil filed under "Lipstick"). Brand stays, weighted
//     below the name, because some names omit it ("Blush Palette Love" is
//     Hourglass's).
//   - each query unit must match (any order, any of the three fields) at
//     one of these levels: exact term 4, term prefix 3, joined-term 2,
//     fuzzy 1. Fuzzy needs 4+ letters, the same first letter and a
//     repeated-letter skeleton within OSA distance 1 (4-7) or 2 (8+).
//     There is no reverse containment: "pallet" never matches "all".
//   - tiers: 0 exact barcode/sku, 1 exact name, 2 name prefix, 3 every unit
//     matched exactly/by prefix/join, 4 some unit matched only fuzzily.

export const SEARCH_CORE_VERSION = 1

export const SEARCH_TIER_EXACT_CODE = 0
export const SEARCH_TIER_EXACT_NAME = 1
export const SEARCH_TIER_NAME_PREFIX = 2
export const SEARCH_TIER_MATCHED = 3
export const SEARCH_TIER_FUZZY = 4

// Query limits shared with the server rewrite (design 4.5): at most 6 comma
// groups of at most 8 tokens each.
export const SEARCH_MAX_GROUPS = 6
export const SEARCH_MAX_TOKENS_PER_GROUP = 8

// Above this many matches a query is "broad" (one or two letters typed):
// only tiers 0-2 are returned, which keeps a first keystroke cheap and its
// list meaningful (design 4.4).
export const SEARCH_BROAD_LIMIT = 1500

const LEVEL_EXACT = 4
const LEVEL_PREFIX = 3
const LEVEL_JOINED = 2
const LEVEL_FUZZY = 1

const WEIGHT_NAME = 1
const WEIGHT_BRAND = 0.8
const WEIGHT_CODE = 0.5

// ---------------------------------------------------------------- normalize

const LIGATURE_FOLD_MAP: Record<string, string> = {
  'æ': 'ae', 'Æ': 'AE',
  'œ': 'oe', 'Œ': 'OE',
  'ø': 'o', 'Ø': 'O',
  'ß': 'ss',
  'ł': 'l', 'Ł': 'L',
  'đ': 'd', 'Đ': 'D',
  'þ': 'th', 'Þ': 'Th',
}

const FORMAT_CHARS = /[​-‍⁠﻿­]/g
const KHMER_CHAR = /[ក-៿᧠-᧿]/

// Latin combining marks only (U+0300-U+036F). Khmer signs live elsewhere and
// survive, which is the whole Khmer fix: the old class stripped \p{M}.
export function foldDiacritics(value: string): string {
  let out = ''
  for (const char of value) out += LIGATURE_FOLD_MAP[char] ?? char
  return out.normalize('NFD').replace(/[̀-ͯ]/g, '')
}

export function normalize(value: unknown): string {
  const base = foldDiacritics(String(value ?? '').normalize('NFKC').replace(FORMAT_CHARS, ''))
    .toLowerCase()
    .replace(/[&+/_.\-’']/g, ' ')
    .replace(/[^\p{L}\p{M}\p{N}\s]/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim()
  if (!base) return ''
  return base
    .split(' ')
    .map((word) => (/[0-9]/.test(word) ? word.replace(/o/g, '0') : word))
    .join(' ')
}

export function isKhmerToken(token: string): boolean {
  return KHMER_CHAR.test(token)
}

// i, v and x are excluded on purpose: "2 x 10ml" and "V" shade codes.
const ROMAN_ALIASES: Record<string, string> = { ii: '2', iii: '3', iv: '4', vi: '6', vii: '7', viii: '8', ix: '9' }

export function romanCanonical(token: string): string {
  return ROMAN_ALIASES[token] ?? token
}

// Repeated letters collapsed: pallet -> palet, palette -> palete.
export function skeleton(token: string): string {
  return token.replace(/(.)\1+/g, '$1')
}

export function fuzzyBudget(skeletonLength: number): number {
  if (skeletonLength < 4) return 0
  if (skeletonLength < 8) return 1
  return 2
}

// Optimal string alignment (Damerau with adjacent transpositions), bounded:
// returns limit + 1 as soon as the distance must exceed `limit`.
export function osaDistance(a: string, b: string, limit: number): number {
  if (a === b) return 0
  if (Math.abs(a.length - b.length) > limit) return limit + 1
  let before: number[] | null = null
  let previous: number[] = []
  for (let j = 0; j <= b.length; j += 1) previous.push(j)
  for (let i = 1; i <= a.length; i += 1) {
    const current: number[] = [i]
    let rowMin = i
    for (let j = 1; j <= b.length; j += 1) {
      let value = Math.min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
      if (before && i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) value = Math.min(value, before[j - 2] + 1)
      current.push(value)
      if (value < rowMin) rowMin = value
    }
    if (rowMin > limit) return limit + 1
    before = previous
    previous = current
  }
  return previous[b.length]
}

// ---------------------------------------------------------------- barcodes
// Same identity rule as searchMatch.ts's barcodeSearchKeys (leading zeros
// folded, placeholder codes ignored, checked UPC-A/UPC-E pairs namespaced).

const MIN_REAL_CODE_LENGTH = 4
const UPC_PAIR_KEY = /^upc[ae]:/

function upcCheckDigit(elevenDigits: string): string {
  let sum = 0
  for (let index = 0; index < 11; index += 1) {
    const digit = elevenDigits.charCodeAt(index) - 48
    sum += index % 2 === 0 ? digit * 3 : digit
  }
  return String((10 - (sum % 10)) % 10)
}

function expandUpcE(raw: string): string {
  if (!/^[0-9]{8}$/.test(raw) || (raw[0] !== '0' && raw[0] !== '1')) return ''
  const [d1, d2, d3, d4, d5, d6] = raw.slice(1, 7).split('')
  const body = d6 === '0' || d6 === '1' || d6 === '2'
    ? `${d1}${d2}${d6}0000${d3}${d4}${d5}`
    : d6 === '3'
      ? `${d1}${d2}${d3}00000${d4}${d5}`
      : d6 === '4'
        ? `${d1}${d2}${d3}${d4}00000${d5}`
        : `${d1}${d2}${d3}${d4}${d5}0000${d6}`
  const eleven = `${raw[0]}${body}`
  const upcA = `${eleven}${upcCheckDigit(eleven)}`
  return raw[7] === upcA[11] ? upcA : ''
}

function compressUpcA(raw: string): string {
  if (!/^[0-9]+$/.test(raw)) return ''
  const upcA = raw.length === 13 && raw[0] === '0' ? raw.slice(1) : raw
  if (upcA.length !== 12 || (upcA[0] !== '0' && upcA[0] !== '1')) return ''
  const m = upcA.slice(1, 6)
  const item = upcA.slice(6, 11)
  const payloads = [
    `${m[0]}${m[1]}${item[2]}${item[3]}${item[4]}${m[2]}`,
    `${m[0]}${m[1]}${m[2]}${item[3]}${item[4]}3`,
    `${m[0]}${m[1]}${m[2]}${m[3]}${item[4]}4`,
    `${m[0]}${m[1]}${m[2]}${m[3]}${m[4]}${item[4]}`,
  ]
  for (const payload of payloads) {
    const candidate = `${upcA[0]}${payload}${upcA[11]}`
    if (expandUpcE(candidate) === upcA) return candidate
  }
  return ''
}

function upcPairKeys(digits: string): string[] {
  if (!/^[0-9]+$/.test(digits)) return []
  if (digits.length === 8) {
    const upcA = expandUpcE(digits)
    return upcA ? [`upce:${digits}`, `upca:${upcA}`] : []
  }
  if (digits.length < 12) return []
  const stripped = digits.replace(/^0+/, '')
  if (stripped.length > 12) return []
  const upcA = stripped.padStart(12, '0')
  const upcE = compressUpcA(upcA)
  return upcE ? [`upca:${upcA}`, `upce:${upcE}`] : []
}

export function codeKeys(value: unknown): string[] {
  const raw = String(value ?? '').trim().toLowerCase().replace(/[\s-]+/g, '')
  if (raw.length < MIN_REAL_CODE_LENGTH) return []
  const primary = raw.replace(/^0+/, '')
  if (!primary) return []
  return [...new Set([primary, ...upcPairKeys(raw)])]
}

// The code keys a typed or scanned box value stands for; [] unless the text
// is one lone code (a multi-word query stays a text search).
export function queryCodeKeys(raw: unknown): string[] {
  const text = String(raw ?? '').trim()
  if (!text || /[\s,]/.test(text)) return []
  return codeKeys(text)
}

export function codeKeySetsMatch(left: readonly string[], right: readonly string[]): boolean {
  if (!left.length || !right.length) return false
  if (left.some((key) => UPC_PAIR_KEY.test(key) && right.includes(key))) return true
  if (left.some((key) => UPC_PAIR_KEY.test(key)) || right.some((key) => UPC_PAIR_KEY.test(key))) return false
  return left.some((key) => right.includes(key))
}

// ---------------------------------------------------------------- terms

function tokensOf(text: unknown): string[] {
  const normalized = normalize(text)
  return normalized ? normalized.split(' ') : []
}

// Every term one field token contributes: itself, its roman alias and the
// pieces of a fused letter/digit token (100ml -> 100, ml).
function tokenTerms(token: string, out: Set<string>): void {
  out.add(token)
  out.add(romanCanonical(token))
  if (isKhmerToken(token)) return
  const pieces = token.match(/[0-9]+|[^0-9]+/g)
  if (pieces && pieces.length > 1) for (const piece of pieces) out.add(piece)
}

const SHORT_TOKEN_LENGTH = 2

// Joined terms. Only two shapes, which is what keeps them quiet:
//   - a run of 2+ consecutive tokens of <= 2 characters, raw and roman:
//     "sk ii" -> skii, sk2; "e l f" -> elf; "3 5" -> 35;
//   - a lone short token joined to the token after it: "bs mall" -> bsmall.
// Joining at every boundary produced noise terms like "flip" (e.l.f. Lip).
function joinTerms(tokens: readonly string[], out: Set<string>): void {
  const isShort = (token: string): boolean => token.length <= SHORT_TOKEN_LENGTH && !isKhmerToken(token)
  for (let start = 0; start < tokens.length;) {
    if (!isShort(tokens[start])) { start += 1; continue }
    let end = start
    while (end < tokens.length && isShort(tokens[end])) end += 1
    const run = tokens.slice(start, end)
    if (run.length >= 2) {
      out.add(run.join(''))
      out.add(run.map(romanCanonical).join(''))
    } else if (end < tokens.length && !isKhmerToken(tokens[end])) {
      out.add(run[0] + tokens[end])
    }
    start = end
  }
}

export interface SearchCoreRow {
  id: number
  name?: unknown
  brand?: unknown
  category?: unknown
  barcode?: unknown
  sku?: unknown
}

interface FieldTerms {
  terms: string[]
  joins: string[]
  text: string
}

function fieldTerms(value: unknown): FieldTerms {
  const tokens = tokensOf(value)
  const terms = new Set<string>()
  for (const token of tokens) tokenTerms(token, terms)
  const joins = new Set<string>()
  joinTerms(tokens, joins)
  for (const term of terms) joins.delete(term)
  return { terms: [...terms], joins: [...joins], text: tokens.join(' ') }
}

// The row's whole search document: every index term, sorted and unique.
// Phase 2 stores this as products.search_doc; phase 1 uses it for parity.
export function docTerms(row: SearchCoreRow): string {
  const all = new Set<string>()
  for (const value of [row.name, row.brand]) {
    const field = fieldTerms(value)
    for (const term of field.terms) all.add(term)
    for (const term of field.joins) all.add(term)
  }
  return [...all].sort().join(' ')
}

// ---------------------------------------------------------------- query units

export interface QueryUnit {
  // Normalized tokens of the unit (one, or a run of short tokens).
  parts: string[]
  // Joined raw and roman forms of a short run; empty for a one-token unit.
  joined: string[]
  // True when the unit ends the group's text, so its last token may still be
  // being typed.
  last: boolean
}

export interface QueryGroup {
  text: string
  units: QueryUnit[]
}

export function queryUnits(raw: unknown): QueryGroup[] {
  const groups: QueryGroup[] = []
  for (const piece of String(raw ?? '').split(',')) {
    const tokens = tokensOf(piece).slice(0, SEARCH_MAX_TOKENS_PER_GROUP)
    if (!tokens.length) continue
    const units: QueryUnit[] = []
    for (let start = 0; start < tokens.length;) {
      let end = start
      while (end < tokens.length && tokens[end].length <= SHORT_TOKEN_LENGTH && !isKhmerToken(tokens[end])) end += 1
      if (end - start >= 2) {
        const parts = tokens.slice(start, end)
        const joined = [...new Set([parts.join(''), parts.map(romanCanonical).join('')])]
        units.push({ parts, joined, last: end === tokens.length })
        start = end
      } else {
        units.push({ parts: [tokens[start]], joined: [], last: start === tokens.length - 1 })
        start += 1
      }
    }
    groups.push({ text: tokens.join(' '), units })
    if (groups.length >= SEARCH_MAX_GROUPS) break
  }
  return groups
}

// ---------------------------------------------------------------- index

type Postings = Map<string, Map<number, number>>

export interface SearchTermIndex {
  version: number
  ids: number[]
  names: string[]
  nameCompacts: string[][]
  // Rank of each doc by (name length, name), so sorting compares integers.
  nameOrder: number[]
  // Docs by the first character of their name, in nameOrder.
  initials: Map<string, number[]>
  terms: Postings
  joins: Postings
  vocab: string[]
  joinVocab: string[]
  fuzzyBuckets: Map<string, Array<[string, string]>>
  khmerDocs: Array<[number, string, number]>
  codeKeysByKey: Map<string, number[]>
  docCodeKeys: string[][]
  codeTexts: Array<[number, string]>
  memo: Map<string, Map<number, UnitHit>>
}

interface UnitHit {
  score: number
  level: number
  // Some name term (weight 1) matched, so the hit survives a titles-only search.
  named: boolean
}

function post(map: Postings, term: string, doc: number, weight: number): void {
  let docs = map.get(term)
  if (!docs) map.set(term, (docs = new Map()))
  if (!((docs.get(doc) ?? 0) >= weight)) docs.set(doc, weight)
}

export interface SearchIndexBuilder {
  add(row: SearchCoreRow): void
  finish(): SearchTermIndex
}

// Incremental so a browser can yield between chunks of rows.
export function createSearchIndexBuilder(): SearchIndexBuilder {
  const index: SearchTermIndex = {
    version: SEARCH_CORE_VERSION,
    ids: [],
    names: [],
    nameCompacts: [],
    nameOrder: [],
    initials: new Map(),
    terms: new Map(),
    joins: new Map(),
    vocab: [],
    joinVocab: [],
    fuzzyBuckets: new Map(),
    khmerDocs: [],
    codeKeysByKey: new Map(),
    docCodeKeys: [],
    codeTexts: [],
    memo: new Map(),
  }
  return {
    add(row: SearchCoreRow): void {
      const doc = index.ids.length
      index.ids.push(Number(row.id))
      const fields: Array<[unknown, number]> = [[row.name, WEIGHT_NAME], [row.brand, WEIGHT_BRAND]]
      let nameText = ''
      for (const [value, weight] of fields) {
        const field = fieldTerms(value)
        for (const term of field.terms) post(index.terms, term, doc, weight)
        for (const term of field.joins) post(index.joins, term, doc, weight)
        if (weight === WEIGHT_NAME) nameText = field.text
        if (field.text && isKhmerToken(field.text)) index.khmerDocs.push([doc, field.text, weight])
      }
      index.names.push(nameText)
      const nameTokens = nameText ? nameText.split(' ') : []
      index.nameCompacts.push([...new Set([nameTokens.join(''), nameTokens.map(romanCanonical).join('')])])
      const keys: string[] = []
      for (const code of [row.barcode, row.sku]) {
        for (const key of codeKeys(code)) if (!keys.includes(key)) keys.push(key)
        const text = String(code ?? '').trim().toLowerCase().replace(/[\s-]+/g, '')
        if (text.length >= MIN_REAL_CODE_LENGTH) index.codeTexts.push([doc, text])
      }
      index.docCodeKeys.push(keys)
      for (const key of keys) {
        const docs = index.codeKeysByKey.get(key)
        if (docs) docs.push(doc)
        else index.codeKeysByKey.set(key, [doc])
      }
    },
    finish(): SearchTermIndex {
      const byName = index.names.map((_, doc) => doc).sort((a, b) => (index.names[a].length - index.names[b].length)
        || (index.names[a] < index.names[b] ? -1 : index.names[a] > index.names[b] ? 1 : 0)
        || (index.ids[a] - index.ids[b]))
      index.nameOrder = new Array(byName.length)
      byName.forEach((doc, rank) => { index.nameOrder[doc] = rank })
      for (const doc of byName) {
        const initial = index.names[doc][0]
        if (!initial) continue
        const docs = index.initials.get(initial)
        if (docs) docs.push(doc)
        else index.initials.set(initial, [doc])
      }
      index.vocab = [...index.terms.keys()].sort()
      index.joinVocab = [...index.joins.keys()].sort()
      for (const term of index.vocab) {
        if (term.length < 4 || !/^\p{L}/u.test(term) || isKhmerToken(term)) continue
        const first = term[0]
        let bucket = index.fuzzyBuckets.get(first)
        if (!bucket) index.fuzzyBuckets.set(first, (bucket = []))
        bucket.push([term, skeleton(term)])
      }
      return index
    },
  }
}

export function buildTermIndex(rows: Iterable<SearchCoreRow>): SearchTermIndex {
  const builder = createSearchIndexBuilder()
  for (const row of rows) builder.add(row)
  return builder.finish()
}

function lowerBound(sorted: readonly string[], value: string): number {
  let lo = 0
  let hi = sorted.length
  while (lo < hi) {
    const mid = (lo + hi) >> 1
    if (sorted[mid] < value) lo = mid + 1
    else hi = mid
  }
  return lo
}

// ---------------------------------------------------------------- matching

function addHit(hits: Map<number, UnitHit>, doc: number, level: number, weight: number): void {
  const score = level * weight
  const named = weight === WEIGHT_NAME
  const existing = hits.get(doc)
  if (!existing) { hits.set(doc, { score, level, named }); return }
  if (existing.score < score) existing.score = score
  if (existing.level < level) existing.level = level
  if (named) existing.named = true
}

function addPostings(hits: Map<number, UnitHit>, docs: Map<number, number> | undefined, level: number): void {
  if (docs) for (const [doc, weight] of docs) addHit(hits, doc, level, weight)
}

function prefixScan(sorted: readonly string[], postings: Postings, prefix: string, level: number, hits: Map<number, UnitHit>, skipExact: boolean): void {
  for (let k = lowerBound(sorted, prefix); k < sorted.length && sorted[k].startsWith(prefix); k += 1) {
    if (skipExact && sorted[k] === prefix) continue
    addPostings(hits, postings.get(sorted[k]), level)
  }
}

// Hits for one token. `last` = the token ends the query text (prefixes of a
// one-letter token are only allowed there); `run` = a joined short run.
function tokenHits(index: SearchTermIndex, token: string, last: boolean, run: boolean): Map<number, UnitHit> {
  const memoKey = `${token}|${last ? 1 : 0}|${run ? 1 : 0}`
  const cached = index.memo.get(memoKey)
  if (cached) return cached
  const hits = new Map<number, UnitHit>()
  addPostings(hits, index.terms.get(token), LEVEL_EXACT)
  if (token.length >= 2 || last) prefixScan(index.vocab, index.terms, token, LEVEL_PREFIX, hits, true)
  if (token.length >= 3 || run) prefixScan(index.joinVocab, index.joins, token, LEVEL_JOINED, hits, false)
  const roman = romanCanonical(token)
  if (roman !== token && !last) addPostings(hits, index.terms.get(roman), LEVEL_EXACT)
  if (isKhmerToken(token)) {
    for (const [doc, text, weight] of index.khmerDocs) {
      if (text.includes(token)) addHit(hits, doc, text.split(' ').includes(token) ? LEVEL_EXACT : LEVEL_PREFIX, weight)
    }
  }
  if (/^[0-9]{5,}$/.test(token)) {
    for (const [doc, text] of index.codeTexts) if (text.includes(token)) addHit(hits, doc, LEVEL_PREFIX, WEIGHT_CODE)
  }
  const shape = skeleton(token)
  const budget = token.length >= 4 && /^\p{L}+$/u.test(token) && !isKhmerToken(token) ? fuzzyBudget(shape.length) : 0
  if (budget > 0) {
    for (const [term, termShape] of index.fuzzyBuckets.get(token[0]) ?? []) {
      if (term === token || term.startsWith(token)) continue
      let near = osaDistance(shape, termShape, budget) <= budget
      // A typo inside a word that is still being typed: compare against the
      // term's prefix of about the same length, the typed head held exact.
      if (!near && last && termShape.length > shape.length + 1) {
        near = osaDistance(shape, termShape.slice(0, shape.length + 1), budget) <= budget
          && shape.slice(0, -1) === termShape.slice(0, shape.length - 1)
      }
      if (near) addPostings(hits, index.terms.get(term), LEVEL_FUZZY)
    }
  }
  if (index.memo.size > 600) index.memo.clear()
  index.memo.set(memoKey, hits)
  return hits
}

function unitHits(index: SearchTermIndex, unit: QueryUnit): Map<number, UnitHit> {
  if (unit.parts.length === 1) return tokenHits(index, unit.parts[0], unit.last, false)
  const joined = new Map<number, UnitHit>()
  for (const form of unit.joined) {
    for (const [doc, hit] of tokenHits(index, form, unit.last, true)) {
      const existing = joined.get(doc)
      if (!existing || existing.score < hit.score) joined.set(doc, { ...hit })
    }
  }
  if (joined.size) return joined
  // No joined form exists anywhere: the run's parts must each match.
  const perPart = unit.parts.map((part, k) => tokenHits(index, part, unit.last && k === unit.parts.length - 1, false))
  perPart.sort((a, b) => a.size - b.size)
  const out = new Map<number, UnitHit>()
  for (const [doc] of perPart[0]) {
    let score = 0
    let level = LEVEL_EXACT
    let named = true
    let ok = true
    for (const hits of perPart) {
      const hit = hits.get(doc)
      if (!hit) { ok = false; break }
      score += hit.score
      level = Math.min(level, hit.level)
      named = named && hit.named
    }
    if (ok) out.set(doc, { score: score / perPart.length, level, named })
  }
  return out
}

interface GroupHit {
  tier: number
  score: number
}

function groupHits(index: SearchTermIndex, group: QueryGroup, titleOnly: boolean): Map<number, GroupHit> {
  const perUnit = group.units.map((unit) => {
    const hits = unitHits(index, unit)
    if (!titleOnly) return hits
    const named = new Map<number, UnitHit>()
    for (const [doc, hit] of hits) if (hit.named) named.set(doc, hit)
    return named
  })
  const out = new Map<number, GroupHit>()
  if (!perUnit.length) return out
  const order = perUnit.map((_, i) => i).sort((a, b) => perUnit[a].size - perUnit[b].size)
  const compactQuery = group.units.flatMap((unit) => unit.parts)
  const compactForms = [...new Set([compactQuery.join(''), compactQuery.map(romanCanonical).join('')])]
  for (const [doc] of perUnit[order[0]]) {
    let score = 0
    let fuzzy = false
    let ok = true
    for (const i of order) {
      const hit = perUnit[i].get(doc)
      if (!hit) { ok = false; break }
      score += hit.score
      if (hit.level === LEVEL_FUZZY) fuzzy = true
    }
    if (!ok) continue
    let tier = fuzzy ? SEARCH_TIER_FUZZY : SEARCH_TIER_MATCHED
    const name = index.names[doc]
    if (!fuzzy && (name.startsWith(group.text) || index.nameCompacts[doc].some((compact) => compactForms.some((form) => compact.startsWith(form))))) tier = SEARCH_TIER_NAME_PREFIX
    if (name === group.text) tier = SEARCH_TIER_EXACT_NAME
    out.set(doc, { tier, score })
  }
  return out
}

export interface SearchHit {
  id: number
  tier: number
  score: number
}

export interface SearchResult {
  total: number
  hits: SearchHit[]
  // True when the match was too broad and only tiers 0-2 are listed.
  broad: boolean
}

export interface SearchOptions {
  // 'OR' unions comma groups; anything else intersects them.
  mode?: string
  // Name only: no brand/category terms and no barcode tier.
  titleOnly?: boolean
}

export function searchTermIndex(index: SearchTermIndex, rawQuery: unknown, options: SearchOptions = {}): SearchResult {
  const titleOnly = Boolean(options.titleOnly)
  const orMode = String(options.mode || '').toUpperCase() === 'OR'
  const groups = queryUnits(rawQuery)
  // First keystroke: one character lists the names that start with it.
  if (groups.length === 1 && groups[0].units.length === 1 && groups[0].units[0].parts.length === 1 && groups[0].text.length === 1) {
    const docs = index.initials.get(groups[0].text) ?? []
    const hits = docs.map((doc) => ({ id: index.ids[doc], tier: index.names[doc] === groups[0].text ? SEARCH_TIER_EXACT_NAME : SEARCH_TIER_NAME_PREFIX, score: 0 }))
    hits.sort((a, b) => a.tier - b.tier)
    return { total: hits.length, hits, broad: true }
  }
  const merged = new Map<number, GroupHit>()
  groups.forEach((group, g) => {
    const hits = groupHits(index, group, titleOnly)
    if (orMode || g === 0) {
      for (const [doc, hit] of hits) {
        const existing = merged.get(doc)
        if (!existing) merged.set(doc, { ...hit })
        else { existing.tier = Math.min(existing.tier, hit.tier); existing.score += hit.score }
      }
      return
    }
    for (const [doc, existing] of merged) {
      const hit = hits.get(doc)
      if (!hit) merged.delete(doc)
      else { existing.tier = Math.max(existing.tier, hit.tier); existing.score += hit.score }
    }
  })
  if (groups.length > 1) for (const hit of merged.values()) hit.tier = Math.max(hit.tier, SEARCH_TIER_MATCHED)
  const queryKeys = titleOnly ? [] : queryCodeKeys(rawQuery)
  if (queryKeys.length) {
    const candidates = new Set<number>()
    for (const key of queryKeys) for (const doc of index.codeKeysByKey.get(key) ?? []) candidates.add(doc)
    for (const doc of candidates) {
      if (!codeKeySetsMatch(queryKeys, index.docCodeKeys[doc])) continue
      merged.set(doc, { tier: SEARCH_TIER_EXACT_CODE, score: Number.MAX_SAFE_INTEGER })
    }
  }
  let ranked = [...merged.entries()]
  const broad = ranked.length > SEARCH_BROAD_LIMIT
  if (broad) ranked = ranked.filter(([, hit]) => hit.tier <= SEARCH_TIER_NAME_PREFIX)
  ranked.sort(([a, x], [b, y]) => (x.tier - y.tier) || (y.score - x.score) || (index.nameOrder[a] - index.nameOrder[b]))
  return { total: ranked.length, hits: ranked.map(([doc, hit]) => ({ id: index.ids[doc], tier: hit.tier, score: hit.score })), broad }
}
