/* eslint-disable no-console */
const fs = require('node:fs/promises')
const path = require('node:path')
const { mapLimit, readJsonAsync, readUtf8Async, toPosix: normalizePath } = require('../lib/fs-utils.js')
const { formatBytes, markdownTable } = require('../lib/report-utils.js')
const ROOT_DIR = path.resolve(__dirname, '../../..')
const REPORT_PATH = path.join(ROOT_DIR, 'ops/docs/reference/GENERATED-BULK-AUDIT.md')
const SUMMARY_PATH = path.join(ROOT_DIR, 'ops/docs/reference/GENERATED-BULK-AUDIT.json')
const CLEAN_GENERATED_PATH = 'ops/scripts/powershell/clean-generated.ps1'
const PACKAGE_MANIFESTS = {
  root: 'package.json',
  frontend: 'frontend/package.json',
  backend: 'backend/package.json',
  ops: 'ops/package.json',
}
const TARGET_MEASURE_CONCURRENCY = 4
const FILE_STAT_CONCURRENCY = 32

const TARGETS = [
  {
    path: 'business-os-data',
    category: 'business data',
    disposition: 'preserve',
    parseAsSource: false,
    protected: true,
    cleanup: 'Retention scripts may prune old backup packages only; never delete the data root.',
    ignoreTokens: ['business-os-data'],
  },
  {
    path: 'business-os-data/organizations/org_leangcosmetics (Leang Cosmetics)/uploads',
    category: 'business uploads',
    disposition: 'preserve',
    parseAsSource: false,
    protected: true,
    cleanup: 'Never delete; reconcile object-store copies instead.',
    ignoreTokens: ['business-os-data'],
  },
  {
    path: 'ops/runtime',
    category: 'runtime state',
    disposition: 'retention',
    parseAsSource: false,
    protected: true,
    cleanup: 'Use prune-storage for reports/backups; preserve secrets and active runtime files.',
    ignoreTokens: ['ops/runtime', '/ops/runtime/'],
  },
  {
    path: 'ops/runtime/secrets',
    category: 'secrets',
    disposition: 'preserve',
    parseAsSource: false,
    protected: true,
    cleanup: 'Never delete or list contents in generated docs.',
    ignoreTokens: ['runtime/secrets', 'ops/secrets'],
  },
  {
    path: 'frontend/node_modules',
    category: 'dependencies',
    disposition: 'reinstallable',
    parseAsSource: false,
    protected: false,
    cleanup: 'Delete only when reinstalling with npm ci immediately after.',
    ignoreTokens: ['node_modules', '**/node_modules'],
  },
  {
    path: 'backend/node_modules',
    category: 'dependencies',
    disposition: 'reinstallable',
    parseAsSource: false,
    protected: false,
    cleanup: 'Delete only when reinstalling with npm ci immediately after.',
    ignoreTokens: ['node_modules', '**/node_modules'],
  },
  {
    path: 'node_modules',
    category: 'dependencies',
    disposition: 'reinstallable',
    parseAsSource: false,
    protected: false,
    cleanup: 'Delete only when reinstalling root packages immediately after.',
    ignoreTokens: ['node_modules', '**/node_modules'],
  },
  {
    path: 'ops/node_modules',
    category: 'dependencies',
    disposition: 'safe cleanup',
    parseAsSource: false,
    protected: false,
    cleanup: 'Safe to delete; reinstall with npm --prefix ops install when needed.',
    ignoreTokens: ['node_modules', '**/node_modules'],
  },
  {
    path: 'frontend/dist',
    category: 'build output',
    disposition: 'regenerable',
    parseAsSource: false,
    protected: false,
    cleanup: 'Regenerate with npm --prefix frontend run build.',
    ignoreTokens: ['frontend/dist'],
  },
  {
    path: 'backend/frontend-dist',
    category: 'build output',
    disposition: 'regenerable',
    parseAsSource: false,
    protected: false,
    cleanup: 'Regenerate through frontend build/package steps.',
    ignoreTokens: ['backend/frontend-dist'],
  },
  {
    path: 'release',
    category: 'release kit',
    disposition: 'regenerable',
    parseAsSource: false,
    protected: false,
    cleanup: 'Regenerate with run/build-release.bat or run/docker/release.bat.',
    ignoreTokens: ['release', '/release/'],
  },
  {
    path: 'output',
    category: 'generated output',
    disposition: 'safe cleanup',
    parseAsSource: false,
    protected: false,
    cleanup: 'Safe to delete when no current manual export is being inspected.',
    ignoreTokens: ['output', '/output/'],
  },
  {
    path: '.playwright-cli',
    category: 'browser artifact',
    disposition: 'safe cleanup',
    parseAsSource: false,
    protected: false,
    cleanup: 'Safe to delete; generated by browser verification tooling.',
    ignoreTokens: ['.playwright-cli'],
  },
  {
    path: 'ops/.playwright-cli',
    category: 'browser artifact',
    disposition: 'safe cleanup',
    parseAsSource: false,
    protected: false,
    cleanup: 'Safe to delete; generated by browser verification tooling.',
    ignoreTokens: ['ops/.playwright-cli', '/ops/.playwright-cli/'],
  },
  {
    path: 'run/cv-render-check-word',
    category: 'local render artifact',
    disposition: 'safe cleanup',
    parseAsSource: false,
    protected: false,
    cleanup: 'Safe to delete after render checks; clean-generated covers it.',
    ignoreTokens: ['run/cv-render-check-word', '/run/cv-render-check-word/'],
  },
]

function parseArgs(argv) {
  const options = {
    policyPath: null,
  }
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === '--policy') {
      options.policyPath = argv[index + 1] || ''
      index += 1
    }
  }
  return options
}

async function walkPathStats(absolutePath) {
  const stack = [absolutePath]
  let files = 0
  let folders = 0
  let bytes = 0
  while (stack.length) {
    const current = stack.pop()
    folders += 1
    let entries = []
    try {
      entries = await fs.readdir(current, { withFileTypes: true })
    } catch (_) {
      continue
    }
    const filePaths = []
    for (const entry of entries) {
      const child = path.join(current, entry.name)
      if (entry.isDirectory()) {
        stack.push(child)
        continue
      }
      filePaths.push(child)
    }
    files += filePaths.length
    const fileSizes = await mapLimit(filePaths, FILE_STAT_CONCURRENCY, async (child) => {
      try {
        return (await fs.stat(child)).size
      } catch (_) {
        // Ignore files that disappear while a runtime process writes reports/logs.
        return 0
      }
    })
    bytes += fileSizes.reduce((total, size) => total + size, 0)
  }
  return { exists: true, files, folders, bytes }
}

async function recursivePathStats(absolutePath) {
  const entries = await fs.readdir(absolutePath, { withFileTypes: true, recursive: true })
  const filePaths = []
  let folders = 1
  for (const entry of entries) {
    if (entry.isDirectory()) {
      folders += 1
      continue
    }
    if (!entry.isFile()) continue
    const parentPath = entry.parentPath || entry.path || absolutePath
    filePaths.push(path.join(parentPath, entry.name))
  }
  const fileSizes = await mapLimit(filePaths, FILE_STAT_CONCURRENCY, async (child) => {
    try {
      return (await fs.stat(child)).size
    } catch (_) {
      // Ignore files that disappear while a runtime process writes reports/logs.
      return 0
    }
  })
  return {
    exists: true,
    files: filePaths.length,
    folders,
    bytes: fileSizes.reduce((total, size) => total + size, 0),
  }
}

async function pathStats(relativePath) {
  const absolutePath = path.join(ROOT_DIR, relativePath)
  try {
    const stats = await fs.stat(absolutePath)
    if (stats.isFile()) {
      return { exists: true, files: 1, folders: 0, bytes: stats.size }
    }
    if (!stats.isDirectory()) {
      return { exists: true, files: 0, folders: 0, bytes: stats.size }
    }
  } catch (_) {
    return { exists: false, files: 0, folders: 0, bytes: 0 }
  }

  try {
    return await recursivePathStats(absolutePath)
  } catch (_) {
    return walkPathStats(absolutePath)
  }
}

function hasAnyToken(source, tokens) {
  return tokens.some((token) => source.includes(token))
}

function toPowerShellTargetToken(relativePath) {
  return normalizePath(relativePath).replace(/\//g, '\\')
}

function compactTargetRows(records) {
  return records
    .filter((record) => record.exists)
    .sort((left, right) => right.bytes - left.bytes || left.path.localeCompare(right.path))
    .slice(0, 8)
    .map((record) => ({
      path: record.path,
      bytes: record.bytes,
      files: record.files,
      folders: record.folders,
      category: record.category,
      disposition: record.disposition,
    }))
}

function compactTimedRows(records) {
  return records
    .filter((record) => record.exists)
    .sort((left, right) => right.measureMs - left.measureMs || right.bytes - left.bytes || left.path.localeCompare(right.path))
    .slice(0, 8)
    .map((record) => ({
      path: record.path,
      measureMs: record.measureMs,
      bytes: record.bytes,
      files: record.files,
      folders: record.folders,
      category: record.category,
      protected: record.protected,
    }))
}

function summarizeByDisposition(records) {
  return records
    .filter((record) => record.exists)
    .reduce((summary, record) => {
      const current = summary[record.disposition] || { bytes: 0, files: 0, folders: 0, targets: 0 }
      summary[record.disposition] = {
        bytes: current.bytes + record.bytes,
        files: current.files + record.files,
        folders: current.folders + record.folders,
        targets: current.targets + 1,
      }
      return summary
    }, {})
}

function dispositionRows(dispositionTotals) {
  return Object.entries(dispositionTotals)
    .sort(([, left], [, right]) => right.bytes - left.bytes)
    .map(([disposition, totals]) => [
      disposition,
      formatBytes(totals.bytes),
      String(totals.files),
      String(totals.folders),
      String(totals.targets),
    ])
}

function isNestedTarget(childPath, parentPath) {
  const child = normalizePath(childPath)
  const parent = normalizePath(parentPath).replace(/\/+$/, '')
  return child !== parent && child.startsWith(`${parent}/`)
}

function collectTargetOverlaps(records) {
  const existingRecords = records.filter((record) => record.exists)
  return existingRecords
    .flatMap((child) => existingRecords
      .filter((parent) => isNestedTarget(child.path, parent.path))
      .map((parent) => ({
        parent: parent.path,
        child: child.path,
        bytes: child.bytes,
        files: child.files,
        folders: child.folders,
        protected: child.protected,
      })))
    .sort((left, right) => right.bytes - left.bytes || left.parent.localeCompare(right.parent) || left.child.localeCompare(right.child))
}

function manifestHasInstallDeps(manifest) {
  return Boolean(
    Object.keys(manifest?.dependencies || {}).length ||
    Object.keys(manifest?.devDependencies || {}).length ||
    Object.keys(manifest?.optionalDependencies || {}).length ||
    Object.keys(manifest?.peerDependencies || {}).length,
  )
}

function recordExists(records, recordPath) {
  return records.some((record) => record.path === recordPath && record.exists)
}

function buildDependencyTopology(records, manifests) {
  const rootPackageHasDependencies = manifestHasInstallDeps(manifests.root)
  return {
    mode: 'separate-install-roots-with-orphan-root-cleanup',
    mergePolicy: 'Do not merge frontend/backend/ops node_modules; their lockfiles, runtime binaries, and release packaging differ. Delete orphan root node_modules when the root package has no install dependencies.',
    installRoots: [
      {
        path: 'frontend',
        lockfile: 'frontend/package-lock.json',
        nodeModules: 'frontend/node_modules',
        active: recordExists(records, 'frontend/node_modules'),
        reason: 'frontend build and UI/test tooling',
      },
      {
        path: 'backend',
        lockfile: 'backend/package-lock.json',
        nodeModules: 'backend/node_modules',
        active: recordExists(records, 'backend/node_modules'),
        reason: 'server, workers, native packages, and Docker release packaging',
      },
      {
        path: 'ops',
        lockfile: 'ops/package-lock.json',
        nodeModules: 'ops/node_modules',
        active: recordExists(records, 'ops/node_modules'),
        reason: 'optional Playwright/operator tooling only',
      },
    ],
    rootPackageHasDependencies,
    rootNodeModulesPresent: recordExists(records, 'node_modules'),
    rootNodeModulesSafeToDelete: recordExists(records, 'node_modules') && !rootPackageHasDependencies,
  }
}

function buildSummary(records, policy, manifests) {
  const generatedAt = new Date().toISOString()
  const existingRecords = records.filter((record) => record.exists)
  const protectedRecords = existingRecords.filter((record) => record.protected)
  const cleanupRecords = existingRecords.filter((record) => !record.protected)
  const nestedTargetOverlaps = collectTargetOverlaps(records)
  const nestedOverlapBytes = nestedTargetOverlaps.reduce((total, overlap) => total + overlap.bytes, 0)
  const nestedProtectedOverlapBytes = nestedTargetOverlaps
    .filter((overlap) => overlap.protected)
    .reduce((total, overlap) => total + overlap.bytes, 0)
  const nestedCleanupOverlapBytes = nestedTargetOverlaps
    .filter((overlap) => !overlap.protected)
    .reduce((total, overlap) => total + overlap.bytes, 0)
  const totalBytes = existingRecords.reduce((total, record) => total + record.bytes, 0)
  const protectedBytes = protectedRecords.reduce((total, record) => total + record.bytes, 0)
  const cleanupCandidateBytes = cleanupRecords.reduce((total, record) => total + record.bytes, 0)
  const generatedBulkCandidateMaxBytes = Number(policy?.cleanup?.generatedBulkCandidateMaxBytes || 0)
  const thresholdExceeded = generatedBulkCandidateMaxBytes > 0 && cleanupCandidateBytes > generatedBulkCandidateMaxBytes
  const missingIgnoreCoverage = records
    .filter((record) => !record.ignoreCovered)
    .map((record) => record.path)
  const protectedCleanupDrift = records
    .filter((record) => record.protected && record.disposition === 'safe cleanup')
    .map((record) => record.path)
  const cleanupCoverageGaps = records
    .filter((record) => !record.protected)
    .filter((record) => !record.cleanGeneratedCovered)
    .map((record) => record.path)
  return {
    generatedAt,
    report: normalizePath(path.relative(ROOT_DIR, REPORT_PATH)),
    summary: normalizePath(path.relative(ROOT_DIR, SUMMARY_PATH)),
    measurementMode: 'bounded-parallel-targets',
    measuredTargetsInParallel: true,
    targetMeasureConcurrency: TARGET_MEASURE_CONCURRENCY,
    fileStatMode: 'recursive-fast-path-with-walk-fallback',
    fileStatConcurrency: FILE_STAT_CONCURRENCY,
    targets: records.length,
    existingTargets: existingRecords.length,
    totalBytes,
    protectedBytes,
    cleanupCandidateBytes,
    nestedTargetOverlaps,
    nestedOverlapBytes,
    adjustedTotalBytes: Math.max(0, totalBytes - nestedOverlapBytes),
    adjustedProtectedBytes: Math.max(0, protectedBytes - nestedProtectedOverlapBytes),
    adjustedCleanupCandidateBytes: Math.max(0, cleanupCandidateBytes - nestedCleanupOverlapBytes),
    largestProtectedTargets: compactTargetRows(protectedRecords),
    largestCleanupTargets: compactTargetRows(cleanupRecords),
    slowestTargetMeasurements: compactTimedRows(existingRecords),
    dispositionTotals: summarizeByDisposition(records),
    generatedBulkCandidateMaxBytes,
    thresholdExceeded,
    missingIgnoreCoverage,
    protectedCleanupDrift,
    cleanupCoverageGaps,
    dependencyTopology: buildDependencyTopology(records, manifests),
  }
}

function renderReport(records, summary) {
  const missingIgnoreRows = records
    .filter((record) => !record.ignoreCovered)
    .map((record) => [record.path, record.ignoreTokens.map((token) => `\`${token}\``).join('<br>')])
  const cleanupCoverageRows = records
    .filter((record) => !record.protected && !record.cleanGeneratedCovered)
    .map((record) => [record.path, `\`${toPowerShellTargetToken(record.path)}\``])

  const rows = records
    .sort((left, right) => right.bytes - left.bytes || left.path.localeCompare(right.path))
    .map((record) => [
      `\`${record.path}\``,
      record.exists ? 'yes' : 'no',
      formatBytes(record.bytes),
      String(record.files),
      `${record.measureMs} ms`,
      record.category,
      record.disposition,
      record.protected ? 'yes' : 'no',
      record.ignoreCovered ? 'yes' : 'no',
      record.cleanGeneratedCovered ? 'yes' : 'no',
      record.cleanup,
    ])

  return `# Generated Bulk Audit

Generated: ${summary.generatedAt}

## Summary

- Targets measured: ${summary.targets}
- Existing targets: ${summary.existingTargets}
- Existing measured bulk: ${formatBytes(summary.totalBytes)}
- Protected measured bulk: ${formatBytes(summary.protectedBytes)}
- Reinstallable/regenerable measured bulk: ${formatBytes(summary.cleanupCandidateBytes)}
- Nested target overlap: ${formatBytes(summary.nestedOverlapBytes)}
- Adjusted non-overlap estimate: ${formatBytes(summary.adjustedTotalBytes)}
- Largest protected target: ${summary.largestProtectedTargets[0] ? `\`${summary.largestProtectedTargets[0].path}\` (${formatBytes(summary.largestProtectedTargets[0].bytes)})` : 'none'}
- Largest cleanup candidate: ${summary.largestCleanupTargets[0] ? `\`${summary.largestCleanupTargets[0].path}\` (${formatBytes(summary.largestCleanupTargets[0].bytes)})` : 'none'}
- Slowest measured target: ${summary.slowestTargetMeasurements[0] ? `\`${summary.slowestTargetMeasurements[0].path}\` (${summary.slowestTargetMeasurements[0].measureMs} ms)` : 'none'}
- Cleanup candidate threshold: ${summary.generatedBulkCandidateMaxBytes > 0 ? formatBytes(summary.generatedBulkCandidateMaxBytes) : 'not configured'}
- Cleanup candidate threshold exceeded: ${summary.thresholdExceeded ? 'yes' : 'no'}
- Measurement mode: ${summary.measurementMode} (${summary.targetMeasureConcurrency})
- File stat mode: ${summary.fileStatMode} (${summary.fileStatConcurrency})
- Source parsing policy: these paths are measured for size and cleanup impact, not treated as maintainable source code.
- Dependency topology: ${summary.dependencyTopology.mode}; root \`node_modules\` safe to delete: ${summary.dependencyTopology.rootNodeModulesSafeToDelete ? 'yes' : 'no'}

## Disposition Totals

${markdownTable(['Disposition', 'Size', 'Files', 'Folders', 'Targets'], dispositionRows(summary.dispositionTotals))}

## Targets

${markdownTable(['Path', 'Exists', 'Size', 'Files', 'Measure', 'Category', 'Disposition', 'Protected', 'Ignored', 'Clean script', 'Cleanup rule'], rows)}

## Nested Target Overlaps

${summary.nestedTargetOverlaps.length ? markdownTable(['Parent', 'Nested target', 'Nested size', 'Files', 'Protected'], summary.nestedTargetOverlaps.map((overlap) => [
    `\`${overlap.parent}\``,
    `\`${overlap.child}\``,
    formatBytes(overlap.bytes),
    String(overlap.files),
    overlap.protected ? 'yes' : 'no',
  ])) : 'No nested generated-bulk target overlaps detected.'}

## Ignore Coverage Gaps

${missingIgnoreRows.length ? markdownTable(['Path', 'Expected ignore token(s)'], missingIgnoreRows) : 'No generated-bulk ignore coverage gaps detected.'}

## Cleanup Script Coverage Gaps

${cleanupCoverageRows.length ? markdownTable(['Path', 'Expected clean-generated target'], cleanupCoverageRows) : 'No non-protected cleanup target is missing from `clean-generated.ps1`.'}

## Cleanup Boundary

- Preserve business data, uploads, secrets, current runtime state, Docker volumes, and current release images.
- Delete generated or reinstallable targets only with the cleanup rule listed above and after exact-path reference checks when a first-party script could depend on the path.
- Use \`prune-storage --docker-safe-prune\` for stopped containers and builder cache; it must not prune Docker volumes, images, or the whole system.
`
}

async function main() {
  const options = parseArgs(process.argv.slice(2))
  const policy = options.policyPath ? await readJsonAsync(path.resolve(ROOT_DIR, options.policyPath), {}) : {}
  const [gitignore, dockerignore, cleanGenerated] = await Promise.all([
    readUtf8Async(path.join(ROOT_DIR, '.gitignore'), ''),
    readUtf8Async(path.join(ROOT_DIR, '.dockerignore'), ''),
    readUtf8Async(path.join(ROOT_DIR, CLEAN_GENERATED_PATH), ''),
  ])
  const manifests = Object.fromEntries(await Promise.all(Object.entries(PACKAGE_MANIFESTS)
    .map(async ([key, manifestPath]) => [key, await readJsonAsync(path.join(ROOT_DIR, manifestPath), {})])))
  const ignoreSource = `${gitignore}\n${dockerignore}`
  const records = await mapLimit(TARGETS, TARGET_MEASURE_CONCURRENCY, async (target) => {
    const startedAt = Date.now()
    const stats = await pathStats(target.path)
    return {
      ...target,
      ...stats,
      measureMs: Date.now() - startedAt,
      path: normalizePath(target.path),
      ignoreCovered: hasAnyToken(ignoreSource, target.ignoreTokens),
      cleanGeneratedCovered: target.protected ? true : cleanGenerated.includes(toPowerShellTargetToken(target.path)),
    }
  })

  await fs.mkdir(path.dirname(REPORT_PATH), { recursive: true })
  const summary = buildSummary(records, policy, manifests)
  await fs.writeFile(REPORT_PATH, renderReport(records, summary), 'utf8')
  await fs.writeFile(SUMMARY_PATH, `${JSON.stringify({
    ...summary,
    records: records.map((record) => ({
      path: record.path,
      exists: record.exists,
      bytes: record.bytes,
      files: record.files,
      folders: record.folders,
      measureMs: record.measureMs,
      category: record.category,
      disposition: record.disposition,
      protected: record.protected,
      ignoreCovered: record.ignoreCovered,
      cleanGeneratedCovered: record.cleanGeneratedCovered,
      parseAsSource: record.parseAsSource,
    })),
  }, null, 2)}\n`, 'utf8')

  console.log(JSON.stringify(summary, null, 2))

  if (summary.missingIgnoreCoverage.length) {
    console.error(`Generated bulk audit failed: ${summary.missingIgnoreCoverage.length} target(s) are missing ignore coverage.`)
    process.exitCode = 1
  }
  if (summary.protectedCleanupDrift.length) {
    console.error('Generated bulk audit failed: protected targets cannot be classified as safe cleanup.')
    process.exitCode = 1
  }
  if (summary.cleanupCoverageGaps.length) {
    console.error(`Generated bulk audit failed: ${summary.cleanupCoverageGaps.length} non-protected target(s) are missing from clean-generated.ps1.`)
    process.exitCode = 1
  }
  if (summary.thresholdExceeded) {
    console.error(`Generated bulk audit failed: cleanup candidates total ${formatBytes(summary.cleanupCandidateBytes)}, above policy threshold ${formatBytes(summary.generatedBulkCandidateMaxBytes)}.`)
    process.exitCode = 1
  }
}

main().catch((error) => {
  console.error(error?.stack || error?.message || String(error))
  process.exitCode = 1
})
